### ISSUE TITLE
Error on validation Array on server

### ISSUE THREAD

**Issue by hmiiro** [ciscoheat/sveltekit-superforms#1]
where i try validate a response of users(and array of users)

[
  {
    id: 1,
    name: 'Important Customer',
    email: 'important@example.com'
  },
  {
    id: 2,
    name: 'Super Customer',
    email: 'super@example.com'
  }
]

const form = await superValidate(users, crudSchema);

I get the following error 
Argument of type 'User[]' is not assignable to parameter of type 'RequestEvent<Partial<Record<string, string>>, string | null> | Request | FormData | Partial<Record<string, unknown>> | null | undefined'.
  Type 'User[]' is not assignable to type 'Partial<Record<string, unknown>>'.

**Comment by ciscoheat** [comment]
Hi, yes, the `crudSchema` only handles a single user (an object, not an array), so you cannot pass the whole users array to it.

**Comment by hmiiro** [comment]
So what happens if the data am returning is an array if users? Hodlw do I attach it to form?

**Comment by ciscoheat** [comment]
Note that this pretty much requires you to use `options.dataType = 'json'` (and `use:enhance` on the form element), otherwise you have to do some complicated string-to-array conversions when posting.

**Comment by hmiiro** [comment]
> The idea is that a schema encapsulates a single form as an object (reflecting `FormData`), so if you need multiple users represented in the form, you should add them as a property to the schema:
> 
> ```ts
> const crudSchema = z.object({
>   users: z.object({
>     name: z.string()
>   }).array()
> })
> ```

I understand this, for posting data from form to the server, this is right. My question is on load function in server when am returning the users to the form(server to client)

**Comment by ciscoheat** [comment]
It's the same, you are representing a form in the load function as well. So you should add your users to an object, and it should work:

```ts
const form = await superValidate({ users }, crudSchema);
```

**Comment by ciscoheat** [comment]
Did you manage to make it work when adding the users to an object?

**Comment by hmiiro** [comment]
The solution you gave meant that if i have a schema of user object, i cant use it to define an array of users.
I dont know whether i understood you correctly, but it meant that i have to write another schema to define an array of users incase i want to return.

My understanding of CRUD, i should be able to use the user schema to create one, read one,read many, update one and delete one or many.

**Comment by ciscoheat** [comment]
The schema passed to `superValidate` is used to validate a single form, not any arbitrary schema.

CRUD can be regarded as `CRUD<T>` where `T` is the entity you want to apply the operations to, so if you want to do `CRUD<T[]>`, you cannot use `superValidate` for that schema because it does not map to validating a single form.

**Comment by hmiiro** [comment]
Okay. I have understood it. That means I will be using the supervalidate to handle form to dB, but any data returned to frontend as long as it's not same format, just pass it as usual and it's handled by sveltekit data prop, not the form from super-form

**Comment by ciscoheat** [comment]
Exactly, if the data isn't going to be used in the form, just pass it as another field than `form`.

**Comment by ciscoheat** [comment]
Closing this, if you don't mind. :)
