### ISSUE TITLE
Form does not exist on type "PageData"

### ISSUE THREAD

**Issue by amorfati254** [ciscoheat/sveltekit-superforms#10]
When using both page.ts and page.server.ts, TS says form does not exist on type of PageData. however when I remove the page.ts the error disappears.
page.ts
```export const load: PageLoad = async (event) => {
	const { id } = event.params;
	const { supabase } = await event.parent();
	const { data: property, error: err } = await supabase
		.from('property_with_units')
		.select('*')
		.eq('id', id)
		.limit(1)
		.single();
	if (err) {
		throw error(500, {
			message: 'Server Error. Please Try Again Later'
		});
	}
	return {
		property
	};
};
```
page.server.ts
```
export const load: PageServerLoad = async (event) => {
	const form = await superValidate(event, formSchema);
	return {
		form
	};
};
```
<img width="1037" alt="Screenshot 2023-03-06 at 17 51 34" src="https://user-images.githubusercontent.com/97120767/223145261-7574d5e1-e958-4a4b-b481-014072a9f828.png">

**Comment by ciscoheat** [comment]
Looks like you haven't passed on the data from the server load function in `+page.ts`. It needs to look something like this:

```ts
import type { PageLoad } from './$types';

export const load = (async ({ data }) => {
  return { ...data, property };
}) satisfies PageLoad;
```

**Comment by amorfati254** [comment]
@ciscoheat Thanks a lot, This should be better documented in the sveltekit docs. This library is very good. It will be huge in the future.
