### ISSUE TITLE
Make the resetForm option accept a function as argument

### ISSUE THREAD

**Issue by ciscoheat** [ciscoheat/sveltekit-superforms#103]
### Discussed in https://github.com/ciscoheat/sveltekit-superforms/discussions/102

<div type='discussions-op-text'>

<sup>Originally posted by **benny856694** April 20, 2023</sup>
I want to dynamically decide whether the form should be reset or not.
use case:
 I have a form to create one or multiple objects. when the user clicks the 'Create multiple objects' button, I don't want to reset the form. but when the user clicks the 'create single object' button, I want to reset the form.
</div>

Add an async callback function to `options.resetForm` that takes the form validation data and should return a boolean.

**Comment by benny856694** [comment]
HI, please hold this requirement, since resetForm can't clear inputs (this is what I need).
The workaround I am using:
```
onUpdated: () => {
			if (shouldBeCleared) {
				$createForm.name = '';
				$createForm.photo = undefined;
                                //more code ......
			}
		}
```

**Comment by ciscoheat** [comment]
It was a small fix, so it's included now in v0.8! There may be a more convenient way of doing this. There's an undocumented function called `defaultData` (for the upcoming 1.0 release) that can be used to get the default values. You can use it to get the empty values, then update the form in `onUpdate`:

On the server:
```ts
import { defaultData } from 'sveltekit-superforms/server'

const emptyData = defaultData(schema)
const form = superValidate(otherData, schema)

return { form, emptyData }
```

On the client:
```ts
const { form, ... } = superForm(data.form, {
  onUpdate({ form }) {
    if(shouldBeCleared) {
      form.data = data.emptyData
    }
  }
})

**Comment by benny856694** [comment]
Cool, with try this

**Comment by ciscoheat** [comment]
Closing this as completed, just make another comment if you can't get it to work.
