### ISSUE TITLE
`$message` is undefined when form was created with `id` set

### ISSUE THREAD

**Issue by samuba** [ciscoheat/sveltekit-superforms#104]
**Description**
Maybe I'm missing something obvious here but:
setting `await superValidate(schema, { id: 'foo' });` will result in `$message` on the client always being undefined.

https://stackblitz.com/edit/sveltekit-superforms-crud-4mxznc?file=src/routes/+page.server.ts
This is the CRUD example with id being set. You can observe that the message `user created` will no longer show.

**Comment by ciscoheat** [comment]
You need to use the same id when you call `superValidate` in the form action as well, so the updated data can be sent to the correct form. So it's a simple fix on line 31 in `+page.server.ts`:

```ts
const form = await superValidate(data, schema, { id: 'foo' });
```

**Comment by samuba** [comment]
🤦‍♂️ That makes a lot of sense. Thanks

**Comment by ciscoheat** [comment]
No problem, easy to overlook. :)
