### ISSUE TITLE
Calling reset after submitting form multiple times

### ISSUE THREAD

**Issue by chrisguerrero** [ciscoheat/sveltekit-superforms#105]
I have a form inside a modal that is using `use:enhance` to submit data client-side. When a user closes the modal without saving, I want to reset the form state back to its initial value. If I call `reset` when the modal is dismissed without saving, this works as expected. However, after submitting the form successfully, calling `reset` sets it back to the origin state rather than the new updated state.

I noticed this behavior is mentioned in [the docs](https://superforms.vercel.app/concepts/enhance#resetform), but I'm not sure how to modify the configuration such that calling `reset` sets the form state back to the last successfully submitted state.

> in Superforms, resetting means **going back to the initial state of the form data, which usually is what you initially sent to the client in PageData**. If this isn’t what you want, you can use [an event](https://superforms.vercel.app/concepts/events) to set $form and $tainted directly.

Any help is greatly appreciated, thanks!

**Comment by ciscoheat** [comment]
Hello, I think you can handle this with events. In the `onUpdated` event you can save the last successful state, then instead of calling reset where you do, set `$form` (and possibly `$tainted`) to the saved state.

```ts
let savedForm : typeof data.form
const { form, tainted } = superForm(data.form, {
  onUpdated({ form }) {
    savedForm = form.data
  }
})

// Instead of reset:
$form = savedForm
$tainted = undefined 
```

You may have to do setTimeout on setting $tainted, if there are many queued updates. This will not be a problem in v0.8.

**Comment by ciscoheat** [comment]
The types may not be correct in the example, but I'm sure you'll get the idea. :)

**Comment by ciscoheat** [comment]
Now that v0.8 is released, you can do this when custom-resetting the form:

```ts
form.set(savedForm, { taint: 'untaint-all' })
```

And you should also do a `savedForm = structuredClone(form.data)`, since form.data is the data that will be modified in the store.

**Comment by chrisguerrero** [comment]
Thanks for the quick reply and follow up! I had worked out that the data would need to be copied, but I was using `Object.assign({}, form.data)`. Will look into upgrading to v0.8 today, the new set API looks better!

**Comment by ciscoheat** [comment]
Closing this, seems to be solved?
