### ISSUE TITLE
Use z.input<T> to create a separate input and output form stores

### ISSUE THREAD

**Issue by tiptenbrink** [ciscoheat/sveltekit-superforms#109]
**Is your feature request related to a problem? Please describe.**

Values in forms can only be strings. If they are not, bind:value uses coercion to make sure they are. Most of the times this isn't a problem because your options will have string values anyway. However, imagine the following case:

You have a `<select>` field with two options that very strongly correspond to a `true` and `false` case. Maybe this would be better represented using type='checkbox' but for UI reasons having a select box can be nicer. Since the option values can only be strings, imagine if we use 'true' and 'false'. If we now set the form schema to have a boolean type for that field, when the user switches the options, the $form value will always stay `true`. This is because 'true' and 'false' strings are both coerced into `true`. This can be solved using a manual transform for that field, so that 'false'->`false` and 'true'->`true`. However, if we for instance had a default value of `true` in the form, since of course there is no way for the form to know that `true` should be 'true', the select will start out with nothing selected. This is because the coercion goes only one way.

This problem could be solved using a booleanProxy, but this means rewriting your component to allow for this specific possibility. Furthermore, since the booleanProxy does not allow setting the false value, you would have to use the empty string '' as the value for the false option, which isn't really nice either.

So there are three options:

* Use a Zod transform and don't use any default values, which allows 'true' and 'false' as option names
* Use a booleanProxy and use 'true' (or anything else) and '' as option names
* Use 'true' and 'false as option names and change the schema to be a literal 'true' or 'false' (however this means I would have to transform the field using this if I ever want e.g. save it to a database, which probably means I have to maintain another schema)

I feel those are all suboptimal.

**Describe the solution you'd like**

Zod allows inferring both an input and output type using `z.input<typeof T>` and `z.output<typeof T>` (`.infer` is the latter). What if we maintain two separate stores, one for actually *holding* the form values, so what is in the HTML (so basically everything will be a string) and one for the parsed and transformed values, which can then be used in JavaScript logic. By using transforms, we can easily convert one and the other and since Zod parses before doing transforms the validity of the input type can still be checked.

This would also solve having to use proxies for i.e. date, since this can now all be handled using Zod transforms right in the schema. Right now for my dateProxy, since I want to show some string if nothing has been input yet, I have to use a separate <input> field because if I would bind directly to that input field, the string would coerce to an invalid date.
Furthermore, you can change $form fields manually to things that technically shouldn't be allowed by the schema, but work due to coercion. This technically breaks type safety. By separating the input form and the output form, you could apply stronger type checking to the input. Probably the output form should also be readonly, since there is no way to go from output -> input and they would get out of sync if you manually changed output types.

Probably this would require quite some work on your end, so if this isn't a realistic option I apologize, I just felt it would be much better if we don't try to use the same object for two different things. This might also break stuff that works fine now.

Regardless, this library is great so far and it's been fun to see it be developed in real-time just as I started work on a project that uses lots of forms in SvelteKit. Thanks!

**Comment by ciscoheat** [comment]
Hi, sorry for the delay, this is a tough one. :) I tinkered with input/output early in the project, but couldn't find the simplicity that I'm striving for with Superforms. Most cases work with infer/output, so I've decided to stick with that for now. Maybe v2.0 could have something like you suggest, but I'm not sure I will be able to handle that by myself.

**Comment by tiptenbrink** [comment]
No worries and thanks for the response! Yes, I can understand this is not a trivial undertaking. Maybe I'll have a look at the code after v1 and see if I can help out in the future.

**Comment by ciscoheat** [comment]
Finally made some progress on this for v2. It's now possible to use the input type in `superValidate`, and the output type is the one to use on the client when updating `$form` programmatically. If you have the time @tiptenbrink, check it out and let me know what you think: https://superforms.rocks/migration-v2/

**Comment by tiptenbrink** [comment]
@ciscoheat Great to see so much effort on your part! Thank you! Really cool to see how you pulled off the validation library-agnostic part! 

I migrated our application to v2. Went very smoothly! One note on the current migration page:

I would maybe first list a bunch of bullet points with no explanation explaining all the breaking pages, which then point to more detailed sections. I had to scroll through a bunch of code examples and explanation before I got to the `onError “message” parameter is removed`, which broke a lot of our code. We also used a lot of types which relied on Zod types used by the previous version, which was actually the majority of our breakage. Some more detail on the new main type changes would also be appreciated!

About this actual issue, I'll get back to you soon once I've tested some more. Is there anywhere where there's more info on where the In and Out types are actually used/matter?

**Comment by ciscoheat** [comment]
I'll see if I can improve the migration guide, but it's not top priority. About the in/out types, it should be pretty much transparent. You can use In for `superValidate`, and the result will be Out, which is also the type `superForm` will be using. It could cause some trouble with client-side validation, since the Out type is what the validation will be checked against. Not sure how big of an issue that is.

**Comment by ciscoheat** [comment]
I did a last fix for this, and now it seems to be quite ok. `superValidate` works as expected with `In` and `Out`, but it's a bit special on the client, since then you already have the correct schema `Out` type, and if you use `bind:value`, there cannot be any transformation, so `In` and `Out` is the same type in most cases on the client.

If that's not the case, you can always replace `options.validators` with another validation schema, as long as its Out type is partially matching `Out` of the schema used to call `superForm`. Partially to make it possible to create multi-step forms with partial data.

Let me know if you have some thoughts about this, otherwise I'm about to close this last milestone issue, and release 2.0!

**Comment by ciscoheat** [comment]
v2 is released, closing this one! Just open another issue if required.
