### ISSUE TITLE
Form ID for multiple forms seems like a implementation detail

### ISSUE THREAD

**Issue by thelinuxlich** [ciscoheat/sveltekit-superforms#111]
And therefore shouldn't need to be handled by the end user. Ideally, sveltekit-superforms would generate a random ID and automatically assign to each form and pass it from client to server and vice-versa.

**Comment by ciscoheat** [comment]
This could actually work automatically with `use:enhance` enabled. Then the client can both generate an id and add it to the payload when posting.

Without `use:enhance`, which is quite rare (especially combined with multiple forms), a requirement would then be to add a hidden field with the magic id variable.

Just have to think if there is some special case where this is not possible.
