### ISSUE TITLE
Errors when using nested data, client side validation and Zod refine

### ISSUE THREAD

**Issue by tobiassern** [ciscoheat/sveltekit-superforms#112]
**Description**
When using nested data and Zod refine I get the following error when client side validation is running -> "caught (in promise) Error: Invalid Zod validator..."

But when submitting the form it works correctly.

I have submitted a small example, the logic is that max value must be greater or equal than the min value. If not an error should be shown.

**If applicable, a MRE**
```
// schema.ts

import { z } from 'zod';

export const schema = z.object({
    tags: z
        .object({
            min: z.number().int().min(5),
            max: z.number().int().min(5)
        }).refine((data) => {
            if (data.min && data.max) {
                return data.min <= data.max;
            }
            return true;
        }, {
            path: ["max"],
            message: "Max must be greater or equal to min",
        })
        .array()
})
```

```
// page.server.ts

import { fail } from '@sveltejs/kit';
import { superValidate } from 'sveltekit-superforms/server';
import type { Actions, PageServerLoad } from './$types';

import { schema } from './schema';

export const load: PageServerLoad = async () => {
    const form = await superValidate(schema);

    return { form };
};

export const actions: Actions = {

    default: async (request) => {

        const form = await superValidate(request, schema);
        console.log(form.valid);
        if (!form.valid) {
            return fail(400, { form });
        }

        return { form };
    },
}
```

```
<!-- page.svelte -->

<script lang="ts">
	import { superForm } from 'sveltekit-superforms/client';
	import { schema } from './schema';

	export let data;

	const { form, enhance, constraints, errors, allErrors } = superForm(data.form, {
		dataType: 'json',
		validators: schema,
		validationMethod: 'onblur',
		defaultValidator: 'clear'
	});

</script>

<form method="POST" use:enhance>
	{#each $form.tags as _, i}
		<div>
			<label for="min">Min</label>
			<input data-invalid={$errors.tags?.[i]?.min} bind:value={$form.tags[i].min} type="number" />
			{#if $errors.tags?.[i]?.min}
				<br />
				<span class="invalid">{$errors.tags[i].min}</span>
			{/if}
		</div>
		<div>
			<label for="max">Max</label>
			<input data-invalid={$errors.tags?.[i]?.max} bind:value={$form.tags[i].max} type="number" />
			{#if $errors.tags?.[i]?.max}
				<br />
				<span class="invalid">{$errors.tags[i].max}</span>
			{/if}
		</div>
	{/each}
	<button on:click={() => ($form.tags = [...$form.tags, { min: 10, max: 5 }])} type="button"
		>Add tag</button
	>
	<button type="submit">Submit</button>
</form>

<style>
	.invalid {
		color: red;
	}
	button {
		background-color: black;
		color: white;
		padding: 5px;
		display: block;
		margin: 5px;
	}
</style>
```

_After onblur event_
![CleanShot 2023-04-25 at 10 08 53](https://user-images.githubusercontent.com/7224143/234214880-fedc3e22-ccdb-4d94-926d-d5012ba5ca64.png)

_After submit event_
![CleanShot 2023-04-25 at 10 09 18](https://user-images.githubusercontent.com/7224143/234215055-d9a2313f-fca2-4f89-b270-9f06d27f4cae.png)

**Comment by ciscoheat** [comment]
The problem has gotten recursively harder, because of the `refine` which is set on the object above the two min/max fields. This means that the whole object above the field in the chain must be used for validation, instead of the per-field approach. The errors can be extracted per field, but a larger part of the schema must be validated when refine or superRefine exists.

**Comment by rburgst** [comment]
I fear the approach to find the "correct" validators for a field is not feasible, imagine a "start-date", "end-date" situation. You would have a validator on the whole object to ensure that `start date` < `end date`. Therefore, I fear you need to perform the full validation on the whole object and then check whether the errors contain fields that the current field is interested in.

**Comment by ciscoheat** [comment]
Yes, this is the approach that will be used, it's unavoidable. Unfortunately it also means that if you call `validate` with `{update: false}`, the whole data structure has to be cloned and tested with the changed field... But I'm doing an optimization at least: If no `ZodEffects` are found, the per-field validation is used.

**Comment by tobiassern** [comment]
Running the full validation on the whole object in this case, does it mean running it on the whole schema given to superform, or just the "numbers" object in this case.

```
export const schema = z.object({
    name: z.string(),
    numbers: z
        .object({
            min: z.number().int(),
            max: z.number().int()
        }).refine((data) => {
            if (data.min && data.max) {
                return data.min <= data.max;
            }
            return true;
        }, {
            path: ["max"],
            message: "Max must be greater or equal to min",
        })
        .array(),
        //... a lot more fields
})
```

**Comment by ciscoheat** [comment]
It will be the whole schema, because you can't know that somewhere else, a `path: ['max']` issue won't be added.

**Comment by ciscoheat** [comment]
v0.8.3 has been released, which makes this work even for related fields, so if you change the `min` field, the error message on `max` disappears. It was quite a hassle, but looks pretty good!

**Comment by tobiassern** [comment]
@ciscoheat it works now, thanks for taking the time to solve this! Closing this bug
