### ISSUE TITLE
zod schema with native enum results in internal error

### ISSUE THREAD

**Issue by demetrius-mp** [ciscoheat/sveltekit-superforms#12]
reproduction:
```ts
const schema = z.object({
	title: z.string(),
	value: z.coerce.number().min(1),
	kind: z.nativeEnum({GRAY: "GRAY", GREEN: "GREEN"}),
	description: z.string().optional()
});

export const load = (async (event) => {
	const form = await superValidate(event, schema);

	return {
		form
	};
}) satisfies PageServerLoad;
```

if i set a `.default("GRAY")` to the enum field, it works ok

not sure if this is intentional, but one problem i noted with setting a default value is that it removes the `required` constraint.

tried submitting the form and got the following error: Error: Unsupported Zod default type: ZodNativeEnum

tried using `z.enum` and it works ok

Is there a plan on adding native enum support? the motivation for this support could be, for example, using the Enum Objects auto generated by prisma when defining an Enum Schema.

**Comment by ciscoheat** [comment]
Hi, you're right that a default value should not remove the required constraint, that is a mistake. Will release a fix for that today, and it will most likely include native enum support as well, it's planned but I haven't had time to implement that yet.

**Comment by demetrius-mp** [comment]
thanks for the quick response!

**Comment by ciscoheat** [comment]
Just released 0.5.18, which fixes the constraint issue and adds support for native enums. Let me know if it works as expected!

**Comment by ollosh** [comment]
Sorry to bump this, but how do you actually build the form with enum? I'm having the same issue where I have a nativeEnum that I'd like to use for schema validation, but I can't get it to work with a select field built from it.

**Comment by ciscoheat** [comment]
Can you make a MRE and post it in a new issue? Use this as a template: https://stackblitz.com/edit/sveltekit-superforms-1-testing?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte
