### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by manupik** [ciscoheat/sveltekit-superforms#123]
The word "with" is repeated twice at [this point](https://superforms.vercel.app/concepts/multiple-forms#:~:text=This%20prevents%20them%20from%20interfering%20with%20with%20each%20other%2C%20which%20can%20happen%20since%20they%20all%20update%20the%20same%20%24page.status%20and%20%24page.form.)  of the docs.

**Comment by ciscoheat** [comment]
Thank you, will fix soon!

**Comment by ciscoheat** [comment]
Done, did some clarifications as well. The good news is that the current way of manually setting form.id will be in most cases not needed in v1.0.

**Comment by manupik** [comment]
Amazing, thank you!
