### ISSUE TITLE
Show error when "validator" is failing

### ISSUE THREAD

**Issue by saturnonearth** [ciscoheat/sveltekit-superforms#134]
**Is your feature request related to a problem? Please describe.**
Sometimes I am testing things out and the data that I am passing to Superforms is not correct, like the object structure, so when I try to submit the form it just does nothing. No error, just halts from submitting.

**Describe the solution you'd like**
A console error or something to inform me at least that that the form is not setup correctly.

**Comment by ciscoheat** [comment]
I'm thinking how to determine whether something went wrong, to avoid false positives. Can you make a MRE here so I can see how a silent error would look like? https://stackblitz.com/edit/sveltekit-superforms-testing?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte

**Comment by saturnonearth** [comment]
Here is an example:

https://stackblitz.com/edit/sveltekit-superforms-testing-oxddy6?file=src/routes/+page.server.ts

I was thinking about it, and maybe having more diagnostic info in SuperDebug (or an error in the console), would be the best solution.

**Comment by ciscoheat** [comment]
In this case everything works, it's just that the `alias` error that is being generated isn't displayed anywhere on the page. It's hard for the program to figure out that this constitutes an error (tracking unused store fields on a svelte page), so I think it's best to just add more stores to SuperDebug to see what happens:

```svelte
<SuperDebug data={{$form, $errors, $message}} />
```

**Comment by ciscoheat** [comment]
Closing this, difficult to make a general solution.
