### ISSUE TITLE
"Submitting" tracking. Similar to 'delayed', but instant.

### ISSUE THREAD

**Issue by saturnonearth** [ciscoheat/sveltekit-superforms#136]
Would be cool to have a store like the delay, timeout, etc but for the initial submit start. My use case is that I want to set my button to "disabled" immediately, but not show a loading spinner until `delayed` kicks in.

**Comment by ciscoheat** [comment]
Did you read the timers page? :) https://superforms.vercel.app/concepts/timers

**Comment by saturnonearth** [comment]
> Did you read the timers page? :) https://superforms.vercel.app/concepts/timers

omg I must of missed that, thanks!
