### ISSUE TITLE
Improve support for Svelte's "bind:group"

### ISSUE THREAD

**Issue by TrentBurroughs** [ciscoheat/sveltekit-superforms#138]
**Description:**
When using Svelte's "bind:group" for multiple checkboxes sharing the same field along with client-side validation (schema being an array of enums), we currently get some odd behavior. 
It works partially, in that the group binding array values are correctly updated in the "$form" store. However, upon interacting with a checkbox in the group, "$errors.MY_FIELD_NAME" will contain an object with numbered keys and "undefined" as the values (per-touched checkbox). Despite this object existing in "$errors", form submission succeeds on both the client-side and server-side.

An example of this behavior below:
```
<!-- +page.svelte -->

<script lang="ts">
	import CheckboxGroup from './CheckboxGroup.svelte';
	import { schema } from './schema';
	import SuperDebug from 'sveltekit-superforms/client/SuperDebug.svelte';
	import { superForm } from 'sveltekit-superforms/client';

	export let data;

	const mySuperForm = superForm(data.form, {
		validators: schema
	});

	const { form, enhance } = mySuperForm;

	const options = [
		{
			value: 'option_1',
			label: 'Option 1'
		},
		{
			value: 'option_2',
			label: 'Option 2'
		},
		{
			value: 'option_3',
			label: 'Option 3'
		}
	];

	$: console.log($errors);

</script>

<SuperDebug data={$form} />

<form method="POST" use:enhance>
	<CheckboxGroup {options} field="options" superForm={mySuperForm} />
	<button>Submit</button>
</form>
```
```
<!-- CheckboxGroup.svelte -->

<script lang="ts">
	import type { z, AnyZodObject } from 'zod';
	import type { FieldPath, UnwrapEffects } from 'sveltekit-superforms';
	import { formFieldProxy, type SuperForm } from 'sveltekit-superforms/client';

	type T = $$Generic<AnyZodObject>;
	export let superForm: SuperForm<UnwrapEffects<T>, unknown>;
	export let field: keyof z.infer<T> | FieldPath<z.infer<T>>;

	const { value, errors, constraints } = formFieldProxy(superForm, field);

	export let options: {
		value: string;
		label: string;
	}[];
</script>

<div>
	<div>
		{#if $errors}
			{#each Object.entries($errors) as error, idx}
				<div>
					Option {Number(error[0]) + 1}: {error[1]}
				</div>
			{/each}
		{/if}
	</div>
	{#each options as { value: checkboxValue, label }}
		<label>
			<input
				type="checkbox"
				value={checkboxValue}
				bind:group={$value}
				{...$constraints}
				{...$$restProps}
			/>
			{label}
		</label>
	{/each}
</div>
```
```
//+page.server.ts

import { schema } from './schema';
import { fail } from '@sveltejs/kit';
import { superValidate } from 'sveltekit-superforms/server';

export const load = async () => {
    const form = await superValidate(schema);
    return { form };
};

export const actions = {
    default: async ({ request }) => {
        const form = await superValidate(request, schema);
        console.log(form);

        if (!form.valid) {
            return fail(400, { form });
        }

        return { form };
    },
};
```
```
//schema.ts

import { z } from 'zod';

export const schema = z.object({
    options: z.enum(['option_1', 'option_2', 'option_3']).optional().array()
});
```

Using this example, if you were to check all three checkboxes, the top-level "$errors" will be this object: 
`{ options: {0: undefined, 1: undefined, 2: undefined}}`

![image](https://user-images.githubusercontent.com/85240479/236554915-8793e459-3d84-4c61-9c1c-d98bf020c95d.png)

**Preferred functionality:**
Client-side validation would ideally automatically remove the property for a given field from the "$errors" object if validations pass (i.e. In this example, the top-level $errors object would have no properties)

**Comment by ciscoheat** [comment]
This is a hidden "feature" used to track what fields have been touched, so errors can be displayed directly during client-side validation, instead of waiting until on:blur. You should make an extra falsy check for each field.

**Comment by TrentBurroughs** [comment]
> This is a hidden "feature" used to track what fields have been touched, so errors can be displayed directly during client-side validation, instead of waiting until on:blur. You should make an extra falsy check for each field.

Ahh that makes sense. Thank you for clearing that up, and thank your work on this awesome library!
Closing this issue.
