### ISSUE TITLE
Errors not returned upon submitting form

### ISSUE THREAD

**Issue by tswerve** [ciscoheat/sveltekit-superforms#139]
**Description**
Error not returned upon submitting form in v0.8.5. If I rollback to v0.8.4 everything works as expected.

https://stackblitz.com/edit/sveltekit-superforms-bug-reporting?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment]
Is the link correct? It's linking to the non-forked version, and I get the error message when submitting the form with 0.8.5.
<img width="532" alt="2023-05-05 23_31_55-Superforms bug reporting (forked) - StackBlitz" src="https://user-images.githubusercontent.com/130450/236572296-956e840c-7dff-439c-83ec-c62c81e5d0e8.png">

**Comment by ciscoheat** [comment]
There were some problems when javascript was disabled in the browser. Check if version 0.8.6 works now.

**Comment by tswerve** [comment]
Looks like that fixed it. Thank you.
