### ISSUE TITLE
SPA - Values are removed from the form until `onUpdate` resolves

### ISSUE THREAD

**Issue by AhmadMayo** [ciscoheat/sveltekit-superforms#149]
**Description**
In a SPA application, values are removed from the form until `onUpdate` resolves. The result is a weird UX for the end user.

**If applicable, a MRE**
https://stackblitz.com/edit/sveltekit-superforms-bug-reporting-gpc2pm?file=src%2Froutes%2F%2Bpage.ts,src%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment]
Submit behavior can be customized with these options: https://superforms.vercel.app/concepts/submit-behavior

**Comment by AhmadMayo** [comment]
None of the submit options changed this behavior. `clearOnSubmit` is about errors and messages, not values, and `multipleSubmits` is not related to the Issue.
I also tried `defaultValidator: 'keep'` and `resetForm: false`

**Comment by akkie** [comment]
You can call `form.clear()`: https://stackblitz.com/edit/sveltekit-superforms-bug-reporting-4jfvgg?file=src/routes/+page.svelte

**Comment by ciscoheat** [comment]
The values shouldn't be removed on submit, I'll take a look and see what can be done.

**Comment by ciscoheat** [comment]
Finally had some time to investigate this. It turned out onUpdate didn't wait for page invalidation, so the page was invalidated, loading the data again, clearing the form. I'll release a patch update for this soon.

**Comment by AhmadMayo** [comment]
@ciscoheat if you can guide me on what to change and where, I can open a PR

**Comment by ciscoheat** [comment]
Thanks, but no need to do that, I've already fixed it. Will release an update tomorrow.

**Comment by ciscoheat** [comment]
This should be fixed now in 0.8.7, just released. Let me know if that's the case!

**Comment by AhmadMayo** [comment]
@ciscoheat Fixed
