### ISSUE TITLE
Does not allow to chain regex

### ISSUE THREAD

**Issue by jKm00** [ciscoheat/sveltekit-superforms#150]
**Description**
Zod allows for chaining regex, but when used with superforms it gives the error: "Only one regex is allowed per field".

**If applicable, a MRE**
https://stackblitz.com/edit/sveltekit-superforms-bug-reporting-tphkb6?file=src/routes/+page.server.ts

**Comment by ciscoheat** [comment]
This is because the constraints only allows one regexp value, so the mapping will fail otherwise, but in 1.0 it will be possible with a warning, that can be turned off.

**Comment by ciscoheat** [comment]
Closed as a duplicate of #115

**Comment by ciscoheat** [comment]
Opening again, until 1.0 is released!
