### ISSUE TITLE
Errors not populated until form changes

### ISSUE THREAD

**Issue by liegeandlief** [ciscoheat/sveltekit-superforms#153]
When there are client-side errors in my form I disable the submit button.

I'm currently checking if `$allErrors` has length > 0 to disable the button.

But `$allErrors` is not populated until validation occurs based on `validationMethod`.

My form starts off in an invalid state (required fields are empty etc.) and so I'd like `$allErrors` to be populated immediately so that I can disable the submit button.

Is this possible?

**Comment by ciscoheat** [comment]
Would it work to set the option `errors: true` when you call `superValidate`? That would add errors to the form directly, and `allErrors` should be populated as well.

**Comment by liegeandlief** [comment]
That would be perfect!

**Comment by ciscoheat** [comment]
Try it out and see if it works. :) (It's already available)

**Comment by liegeandlief** [comment]
That seems to do the trick. Thank you!

**Comment by liegeandlief** [comment]
I've reopened this because I've realised `errors: true` does not do quite what I what.

I want to be able to set the initial field values on the client, not the server, and have the client-side validation run immediately to check the initialised values.

Is this possible?
