### ISSUE TITLE
inconsistent $error behaviour with client validators

### ISSUE THREAD

**Issue by david-roeger** [ciscoheat/sveltekit-superforms#154]
**Description**
When using client side validators the error store shows some inconsistent behavior before and after form submits.
 Looking at these two examples:

---

### The error store after the inputs have been validated (blur event has fired for both inputs)
<img width="467" alt="Screenshot 2023-05-17 at 19 38 32" src="https://github.com/ciscoheat/sveltekit-superforms/assets/61949735/db2032be-800b-4faa-95b3-05010f8b088a">

The store has keys for **both** fields - including one with the value of undefined for the name field. (`Object.keys($errors.length) === 2`)

---

### The error store  after submit
<img width="465" alt="Screenshot 2023-05-17 at 19 38 36" src="https://github.com/ciscoheat/sveltekit-superforms/assets/61949735/415c4b10-90d7-434f-aa5c-2d977239c3bd">

The store has only one key for the error field (`Object.keys($errors.length) === 1`)

---

I would expect the error store to have the same values (and same amount of keys) before and after submit. 

**MRE**
https://stackblitz.com/edit/sveltekit-superforms-bug-reporting-fcqmbd?file=README.md

**Comment by ciscoheat** [comment]
This is similar to #138 , it's a hidden "feature" used to track what fields have been touched, so errors can be displayed directly during client-side validation, instead of waiting until on:blur. 

You should make an extra falsy check for each field, to avoid surprises. Will add a note to the documentation about this!

**Comment by ciscoheat** [comment]
Docs added in the upcoming 1.0 release.
