### ISSUE TITLE
data` has been deprecated in favor of `formData`. `data` will be removed in a future version. (Called from use:enhance submit function)

### ISSUE THREAD

**Issue by happysalada** [ciscoheat/sveltekit-superforms#158]
there are 2 future deprecation warning when using latest version of sveltekit with latest version of sveltekit superform.
here is the second warning
```
ient.js?v=a41a0c67:1974 `form` has been deprecated in favor of `formElement`. `form` will be removed in a future version. (Called from use:enhance submit function)
```

just thought you might be interested.

**Comment by ciscoheat** [comment]
Yes, this will be fixed in v1.0, which isn't too far away!

**Comment by ciscoheat** [comment]
Warnings removed in v1.0.0-rc.1

**Comment by dyleeo** [comment]
Hello!  

 I am seeing the 2 deprecation warnings in version **2.14.0** while using "use:enhance" on a form. 

- `data` has been deprecated in favor of `formData`. `data` will be removed in a future version. (Called from use:enhance submit function)
- `form` has been deprecated in favor of `formElement`. `form` will be removed in a future version. (Called from use:enhance submit function
