### ISSUE TITLE
Error: Function called outside component initialization

### ISSUE THREAD

**Issue by eric-naguras** [ciscoheat/sveltekit-superforms#160]
**Description**

Edit: I got it to work, see below! I think this still might be a bug.

I downloaded Huntabyte's example code from here: https://github.com/huntabyte/superforms-demo
I installed the dependencies and ran vite dev.
Everything seems to work.

Then I updated all dependencies to the latest version (via ncu) and now the code crashed in the browser with this error: "Function called outside component initialization"

I have the same issue in my own app but I thought it was caused by maybe a complicated zod schema or something else in my app.

So I tried Hyntabyte's example which runs fine as is but crashes when all dependencies are updated.
 
I hope this can be solved or a workaround comes available is I really want to use this.
Thanks for all the work done.

Here are my updated dependencies:
"devDependencies": {
		"@playwright/test": "^1.34.3",
		"@sveltejs/adapter-auto": "^2.1.0",
		"@sveltejs/kit": "^1.18.0",
		"@typescript-eslint/eslint-plugin": "^5.59.7",
		"@typescript-eslint/parser": "^5.59.7",
		"autoprefixer": "^10.4.14",
		"daisyui": "^2.51.6",
		"eslint": "^8.41.0",
		"eslint-config-prettier": "^8.8.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"postcss": "^8.4.23",
		"postcss-load-config": "^4.0.1",
		"prettier": "^2.8.8",
		"prettier-plugin-svelte": "^2.10.0",
		"prettier-plugin-tailwindcss": "^0.3.0",
		"rome": "^12.1.2",
		"svelte": "^3.59.1",
		"svelte-check": "^3.3.2",
		"svelte-preprocess": "^5.0.3",
		"sveltekit-superforms": "^0.8.7",
		"tailwindcss": "^3.3.2",
		"tslib": "^2.5.2",
		"typescript": "^5.0.4",
		"vite": "^4.3.8",
		"vitest": "^0.31.1",
		"zod": "^3.21.4"
	},

Update: I got it working now by making one small change to the code.
I was looking at this example: https://superforms.vercel.app/get-started and saw that in the load event of the +page.server.ts the call to superValidate only has the zod schema as an argument while Huntabyte's code also adds the event as an argument. When I removed the event everything works like a charm.  Same is true form my own app which is a bit more complicated.

**Comment by ciscoheat** [comment]
Ok, it was using the old syntax. Great that you found the solution, if you can do a quick PR on the Huntabyte repo I'm sure it'll be appreciated. :)

**Comment by eric-naguras** [comment]
For some weird reason I cannot reproduce this error anymore so a PR might not be a good idea.
