### ISSUE TITLE
question: how to combine the snapshot feature with a componentized form

### ISSUE THREAD

**Issue by dmoebius** [ciscoheat/sveltekit-superforms#162]
I want to combine the [snapshot feature](https://superforms.vercel.app/concepts/snapshots) with [componentization](https://superforms.vercel.app/components), but I cannot get it to work.

For example, I have a component `Editor.svelte` which contains a form:
```
<script lang="ts">
    ...
    const {form, errors, enhance, capture, restore} = superForm(data)

    export const snapshot = { capture, restore }  // this won't work alone since it's not in +page.svelte
    ...
</script>

<form method="POST" action="?/myaction" use:enhance>
...
```
and `+page.svelte` contains:
```
<script lang="ts">
  import { Editor } from '$lib/components/Editor.svelte'
  import type {PageData, Snapshot} from './$types'

    export let data: PageData

    export const snapshot : Snapshot // = ??? would like to use capture/restore from Editor.svelte but cannot
</script>
<Editor data={data.form}/>
```

How is this support to work together?

**Comment by ciscoheat** [comment]
Do you get a SvelteKit-specific error when using capture and restore outside `+page.svelte`?

**Comment by dmoebius** [comment]
No. But the problem is with the types. In my component `$lib/components/Editor.svelte` I cannot import the Snapshot type:
```
import type {Snapshot} from './$types' // error: there is not $types in directory $lib/components
```
I could of course import the $types from the corresponding page, but this breaks encapsulation (and doesn't work if the component is added to more than one page).

I could omit types:
```
const { form, capture, restore } = superForm(data)
export const snapshot = { capture, restore }
```
Hmm... this seems to work: when I navigate away and back to the component, the entered data is displayed for a millisecond, then vanishes. Somehow the values get overridden immediately. 
I'll have to create a MCE to demonstrate this.

**Comment by ciscoheat** [comment]
Is this still an issue you'd like addressed? Closing this otherwise.

**Comment by dmoebius** [comment]
Sorry for not taking the time to create an MCE. My customer's requirements changed so I could get away without using snapshots; there was no longer a need to save the data when navigating back and forth to the page.
I reported the error for the very old version 0.8.x, so chance is that it has been fixed.
I think you can close it.

**Comment by ciscoheat** [comment]
Ok, thanks for getting back, closing this then!
