### ISSUE TITLE
$valid store doesn't reflect validation status

### ISSUE THREAD

**Issue by ciscoheat** [ciscoheat/sveltekit-superforms#163]
**Description**
When errors are updated client-side, `valid` isn't reflecting whether there are errors or not.

**Comment by ciscoheat** [comment]
This behavior will stay the same, `valid` will reflect the last *posted* validation status, not just form errors.

**Comment by dmoebius** [comment]
Is there any other way to check the current _client_ validation status? For e.g. to enable/disable the submit button. (Given that I don't have any async validation in my form).

**Comment by ciscoheat** [comment]
In 1.0.0-rc.2 `$valid` is removed and replaced with a `$posted` store, which should work even better to determine if the button should be posted. Something like:
```svelte
disabled={!$posted || !$allErrors.length}
```
