### ISSUE TITLE
Server superValidate mutates the zod number type field on invalid

### ISSUE THREAD

**Issue by kevbook** [ciscoheat/sveltekit-superforms#166]
**Description**
When I have a zod number type schema, after running through server `superValidate`, it mutates the field with `NaN` if the field value is invalid. 

This creates a problem because I want to send the untouched field values back to the client so that we can display the error message and allow the user to edit the field.

```js
import { z } from 'zod';
import { superValidate } from 'sveltekit-superforms/server';

const input = new URLSearchParams({ num: 'abc', str: 'abc' });
const schema = z.object({ num: z.number(), str: z.string().min(5) });
const formData = await superValidate(input, schema);
console.log('formData', formData);

// Console output
formData {
  valid: false,
  errors: {
    num: [ 'Expected number, received nan' ],
    str: [ 'String must contain at least 5 character(s)' ]
  },
  data: { num: NaN, str: 'abc' },
  empty: false,
  constraints: { num: { required: true }, str: { minlength: 5, required: true } }
}
```

**Comment by ciscoheat** [comment]
This is by design, since the schema type for `num` is number, no other value than a number will be set on it, to preserve type safety. If you really need the value to stay the same, you need to use `z.string()` instead, and perhaps an extended schema with [z.coerce.number()](https://zod.dev/?id=coercion-for-primitives) that will do the final validation.

In #109 there is an idea to separate the input and output schemas, but this requires quite a bit of design changes, so it won't be made in the near future.

**Comment by kevbook** [comment]
Got it; I tried using `zod.pipe` to solve these coerce issues -- see [zod.pipe](https://zod.dev/?id=pipe). But `superValidate` doesn't support  ZodPipeline. Is that an easy addition?

```
"Unsupported Zod default type: ZodPipeline"
```

**Comment by ciscoheat** [comment]
Adding support for ZodPipeline with default values is no problem (will be added for 1.0), but it still won't solve the type issue unfortunately. The schema output type is number, so a number must be set on the data. 

What I was thinking about is a secondary schema that will do the coercion, and if it's not valid, return the data of the first schema (that contains the strings).

**Comment by kevbook** [comment]
We can do `input` field validations on the client side. But the issue is when client-side JS isn't working (the case that Rich Harris constantly talks about with mobile), then if a user sends a non-numeric value on input, then the server overrides the value on the input field as `NaN` on validation.

**Comment by ciscoheat** [comment]
Yes, hence my suggestion to use a secondary schema for the data processing, and the first one containing strings for validation. Both schemas are used on the server.

**Comment by kevbook** [comment]
Something like this

```
z.string().nonempty().regex(/^\d{1,7}$/).transform((str) => Math.abs(Number(str))
```

**Comment by gurpreetatwal** [comment]
@kevbook The following has worked pretty well for me and doesn't require the use of regular expressions: 

```js
const schema = z.object({
  example: z.preprocess((x) => (x ? x : undefined), z.coerce.number().int().min(1)),
});
```
Unfortunately it does still require making the actually input element a text input and not a number input

**Comment by ciscoheat** [comment]
There is a `preprocessed` option for `superValidate` that passes through the value as it is, if that's helpful. Something like:

```ts
const form = await superValidate(data, schema, { preprocessed: ['example'] });
```
