### ISSUE TITLE
Message function statuses

### ISSUE THREAD

**Issue by josuetorr** [ciscoheat/sveltekit-superforms#167]
The `message` only considers a status of `404`. It would be awesome if we could also return other statuses when successful. For exemple, when a user has created in a dashboard, we don't necessarily want to redirect. I'd like to return a status of `201` in order to show a success toast

**Comment by ciscoheat** [comment]
You can set any status code with `message`: https://superforms.vercel.app/concepts/messages#the-message-helper

**Comment by josuetorr** [comment]
But it will only return a status of `200` on sucess

```js
export function message<T extends AnyZodObject, M>(
  form: Validation<T, M>,
  message: M,
  options?: {
    status?: number;
    valid?: boolean;
  }
) {
  form.message = message;
  if (options?.valid !== undefined) form.valid = options.valid;

  const failure =
    (options?.status !== undefined && options.status >= 400) || !form.valid;

  return failure ? fail(options?.status ?? 400, { form }) : { form };
}
```
I want to return a status of `201` when a user was created successfully.

Maybe something like:
```js
...
return failure ? fail(options?.status ?? 400, { form }) : { form, status: options?.status };
```

**Comment by ciscoheat** [comment]
I think that's a SvelteKit thing, if you look at the examples, there is no obvious way of returning a different status code than 200 from a form action unless using fail: https://kit.svelte.dev/docs/form-actions#anatomy-of-an-action

**Comment by ciscoheat** [comment]
You can of course add any message to `form` yourself, and return extra data with `{ form, status }` at the end.
