### ISSUE TITLE
Validation throws with async refinement

### ISSUE THREAD

**Issue by alejandroperezpujante** [ciscoheat/sveltekit-superforms#170]
## Description
I was validating some data for a Log In route, and decided to add the check to know if an email is present or not in the database directly in the Zod Schema by adding a '.refine' property to the schema.

But when the validation runs, it always throws with the error ``Async refinement encountered during synchronous parse operation. Use .parseAsync instead.`` By the text I assume that the actual method call to validate the schema is not asynchronous and that is why I'm having this error.

After reading trought SvelteKit Superforms documentation without finding a way of fixing this behaviour, I decided to report it here. Am I missing something like a property I have to pass to the validation function or I just founded a problem that need to be fixed? Thanks in advance for the help and the amazing work.

## Reproduction of the error in SvelteLab

https://www.sveltelab.dev/0fomm1kdbyceva8

**Comment by ciscoheat** [comment]
Are you using 1.0.0-rc.1? This will be fixed in the next RC, released very soon.

**Comment by alejandroperezpujante** [comment]
Yes, I am using 1.0.0-rc.1

In that case, I'll just wait for the next release for the fix.
Thanks a lot for the explanation!

**Comment by ciscoheat** [comment]
RC 2 has just been released, try it out and see if it's fixed!
