### ISSUE TITLE
Setting dataType to json does not allow you to set values in the onSubmit event

### ISSUE THREAD

**Issue by stefandevo** [ciscoheat/sveltekit-superforms#177]
**Description**
Setting dataType to json does not allow you to set values in the onSubmit event

**If applicable, a MRE**

https://stackblitz.com/edit/sveltekit-superforms-testing-2z9amt?file=src%2Froutes%2F%2Bpage.svelte

Om the `page.svelte` I added the dataType: 'json' , but this is causing the `formid` value to be set. When I remove that feature, it is working.

Not sure if it is a bug, but there should be another way to add a "calculated" value in the object that I pass to the server. A hidden field is not an option for me in this case.

**Comment by ciscoheat** [comment]
With `dataType: 'json'`, the form data itself isn't posted, so you can modify `$form` directly to set what should be posted. See the docs here: https://superforms.vercel.app/concepts/nested-data#datatype

If you want to set data without tainting the form, update the store instead of assigning directly to $form:

```ts
form.update($form => {
  $form.formid = ...
  return $form
}, { taint: false })
```

**Comment by stefandevo** [comment]
Not sure I understand completely where to place this code, sorry.

My need is that a kind of unique value is calculated on the client, and added the form upon submit (so the value should not be set in the form action itself).

So I tried to add the snippet to the StackBlitz code:
https://stackblitz.com/edit/sveltekit-superforms-testing-mfnbxh?file=src%2Froutes%2F%2Bpage.svelte

Without success, as it complains about using the stores not at the top level component. Any idea, or am I using the form.update method at a wrong place?

**Comment by ciscoheat** [comment]
You were using the `form` argument from `onSubmit`, not the store returned from `superForm`. And it was a spelling mistake as well further down. This works: https://stackblitz.com/edit/sveltekit-superforms-testing-fqdbsq?file=src%2Froutes%2F%2Bpage.svelte

**Comment by stefandevo** [comment]
Just wondering how I could use this in a more generic way.

Because I don't want to set all the settings over and over again in each page, I created a function for creating an instance of the SuperForm.

This looks like this:

```

export function hSuperForm<T extends AnyZodObject>(
	form: SuperValidated<T>,
	submit?: (...params: Parameters<SubmitFunction>) => unknown | void,
	loadLayout?: boolean
) {
	if (!loadLayout) loadLayout = false;

	return superForm(form, {
		dataType: 'json',
		invalidateAll: loadLayout,
		delayMs: 250,
		applyAction: loadLayout,
		onResult({ result }) {
			if (result.type === 'redirect') {
				goto(result.location);
			}
		},
		onSubmit(input) {
			if (submit) {
				submit(input);
			}
		}
	});
}

```

Before, when dataType was not `json` I could use my function to set a unique formid in the `onSubmit`.

However, now I can't get the correct variables / stores inside this generic function anymore as explained by you to set the underlying `$form`.

Any suggestions how I could re-use this code

```
      form.update($form => 
      { 
        $form.formid = Date.now().toString();
        return $form;
      }, { traint: false });
```

in this way?

**Comment by ciscoheat** [comment]
Instead of returning superForm directly, take the return value and use `form` from there.
