### ISSUE TITLE
Unsupported Zod default type: ZodPipeline

### ISSUE THREAD

**Issue by OllieJT** [ciscoheat/sveltekit-superforms#179]
Is there an escape hatch, or recommended workaround for using zod schemas with unsupported features, like `.pipe()` or `.refine()`?

I understand there may be more boiler plate I have to take care of myself, but I'd like to parse my form values using these conventions, while returning errors in the same format (via superforms).

### Error code
```sh
SuperFormError: Unsupported Zod default type: ZodPipeline

# ( stack trace ) 
```

### Example desired usage
```ts
export const username_schema = z
   .string()
   .min(3)
   .max(128)
   .refine((val) => !/\s/.test(val), {
   	  message: 'Username cannot contain spaces',
   })
   .refine((val) => !/[^a-zA-Z0-9-_]/.test(val), {
   	  message: 'Username can only contain letters, numbers, underscores, and dashes',
   });

export const user_schema = z.object({
   // I've simplified this, but I need to pass the schema via the pipe method
   username: z.string().pipe(username_schema),
   // ...
});

// then I would use user_schema with superforms
```

**Comment by OllieJT** [comment]
Also - took me a sec to adopt superforms because of how many opinions it brought that I needed to groq... but it's now a default install in most projects.

❤️

**Comment by ciscoheat** [comment]
Hi, refine should work in 0.8, and pipe should work in the 1.0.0 RC, have you tried the latest version?

Here's the fix: https://github.com/ciscoheat/sveltekit-superforms/blob/28a1bcc291b38e4f754d6ee3d8f3b2838b61c4a4/src/lib/schemaEntity.ts#L116

**Comment by OllieJT** [comment]
Thanks @ciscoheat!
