### ISSUE TITLE
access to tainted state on server-side

### ISSUE THREAD

**Issue by xmlking** [ciscoheat/sveltekit-superforms#181]
I have a `Boolean` form field (e.g., `shared`). 
On server-side, I need to do some custom business logic if its value is changing from `false` to `true`.

I have to add an extra form field (e.g., `originalShared`) to tract if its value is change from  `false`=> `true`
Is there a better option to know previous value of a form field on server-side?

**Comment by ciscoheat** [comment]
That kind of state management is outside the scope of Superforms, I'm afraid. Perhaps you can serialize the `$tainted` store in `onSubmit` and send it to the server.
