### ISSUE TITLE
Error: Only Zod schema objects can be used with superValidate. 

### ISSUE THREAD

**Issue by xmlking** [ciscoheat/sveltekit-superforms#182]
I am getting `Only Zod schema objects can be used with superValidate. Define the schema with z.object({ ... }) and optionally refine/superRefine/transform at the end.`  error
Only  first time when I access `http://localhost:5173/dashboard/policies/[id]` route.
[code](https://github.com/xmlking/svelte-starter-kit/tree/main/src/routes/(app)/dashboard/policies/%5Bid%5D)

<img width="1115" alt="image" src="https://github.com/ciscoheat/sveltekit-superforms/assets/627951/7058173c-fe27-44a5-b3ab-d0175abf5a89">
<img width="1125" alt="image" src="https://github.com/ciscoheat/sveltekit-superforms/assets/627951/fe22dd29-0b78-4a54-8680-4b41e1518407">
Wonder if I doing something wrong!

**Comment by ciscoheat** [comment]
Can you debug what you're sending to `superValidate`? As the message say, if it's not a Zod schema, an error will be thrown.

**Comment by ciscoheat** [comment]
Did you find out what was wrong?

**Comment by xmlking** [comment]
The issue seems resolve. Not sure what I changed :(
https://github.com/xmlking/svelte-starter-kit/tree/main/src/routes/(app)/dashboard/policies
Nice to use superforms with FORMs with GET method.this is something I didn’t expected work. :)

**Comment by ciscoheat** [comment]
It's made to be very flexible. :) Have you tried using it to parse URL's? You can send a `URL` to `superValidate` and the query parameters will be validated.

**Comment by xmlking** [comment]
> It's made to be very flexible. :) Have you tried using it to parse URL's? You can send a `URL` to `superValidate` and the query parameters will be validated.

Yes using URL.  saw one of example in your repo that inspired me.
