### ISSUE TITLE
Do not add errors for fields that are not present when partially initializing 

### ISSUE THREAD

**Issue by douglasward** [ciscoheat/sveltekit-superforms#184]
**Description**

If you partially initialize a form like the documentation states you can, the other fields that are not initialized are loaded with their errors already present.

For example, in a "new address" form we need to have an id field that is hidden from the user, but that contains the id of the customer we want to add a new address for. But if we just provide the id as the inital value for the superform then the other fields that are required will be loaded with their required state shown which is not wanted. We want the form to be clean like it would be if the id wasn't provided as an initial value.

Here a simplified repo:

https://stackblitz.com/edit/sveltekit-superforms-bug-reporting-aerdzm?file=src%2Froutes%2F%2Bpage.server.ts

Is there a different way to handle this? Or can it be fixed so that only the fields that are initially provided are validated?

**Comment by ciscoheat** [comment]
You can do this quite easily with an option in superValidate:

```ts
const form = await superValidate({ id: '1' }, schema, { errors: false });
```

This was hidden in the API docs before, but now when 1.0 is released there is a section explaining some details: https://superforms.rocks/concepts/error-handling#initial-form-errors

**Comment by douglasward** [comment]
Ahh super!! Thank you very much
