### ISSUE TITLE
Return custom data

### ISSUE THREAD

**Issue by hanssonduck** [ciscoheat/sveltekit-superforms#188]
According to the docs (https://superforms.rocks/faq#how-can-i-return-additional-data-together-with-the-form) should custom data be available on `PageData`, but this seems to be incorrect. Per standard SvelteKit actions is this data available on `ActionData` instead and this is what I see when testing. Are the docs wrong or should the data be available there as stated?

Really good library and congratulations on the Svelte Hack 2023 win!

**Comment by ciscoheat** [comment]
When returning extra data in the load function, it will be available in PageData. If in form actions, ActionData.

**Comment by hanssonduck** [comment]
> When returning extra data in the load function, it will be available in PageData. If in form actions, ActionData.

Thanks that's what I though. Just had to ask when the docs said otherwise. Should be a quick fix in the docs.

**Comment by ciscoheat** [comment]
Docs are updated now, thank you for noticing.
