### ISSUE TITLE
Form is not updated as tainted when changing zod sets.

### ISSUE THREAD

**Issue by Jabronironi** [ciscoheat/sveltekit-superforms#194]
When you have a zod schema like:

``` const schema = z.object({ things: z.set(z.number()) }); ```

... and you modify that collection through add/delete (or even through assigning a new set), like:

```$form.things.add(1);```

... or

``` $form.things = new Set($form.things);```

...  the form is not marked as tainted.  e.g.:

``` let isTainted = $tainted;```

...will === false in the onSubmit super form function.

**Comment by ciscoheat** [comment]
It's working now in 1.1.0, but to taint a set when using only its methods, requires the use of `form.update` instead of just assignment:

```ts
form.update($form => {
  $form.things.add(1);
  return $form;
})
```

Direct assignment will taint as usual: `$form.things = new Set(...)`
