### ISSUE TITLE
Add scroll mechanism to scrollToError

### ISSUE THREAD

**Issue by ciscoheat** [ciscoheat/sveltekit-superforms#199]
### Discussed in https://github.com/ciscoheat/sveltekit-superforms/discussions/198

<div type='discussions-op-text'>

<sup>Originally posted by **AntonPavlenkov** June 21, 2023</sup>
> I encountered an issue where the window does not have a scroll, while its children do. As a result, scrolling to an error does not work since the window itself lacks a scroll functionality.

> In order to address this, I propose the following enhancements to improve the functionality:

> Add an option in the configuration to specify the element for scrolling.
Utilize the Element.scrollIntoView() function.
The second option seems preferable as it reduces the amount of code required for calculations such as getBoundingClientRect(), centering the element, and removing the sticky header, among other things.</div>

That's just an extra option for `scrollToError`, so that should be no problem.

**Comment by ccll** [comment]
Same here using Skeleton UI's AppShell, which scrolls an element instead of the entire window.

For now, I'm doing customized scrolling in `onUpdated()` event callback.
```ts
const { form, errors, enhance } = superForm(data.form, {
    scrollToError: 'off',
    onUpdated({ form }) {
        if (!form.valid) {
            document.querySelector('[data-invalid]')?.scrollIntoView({ behavior: 'smooth' })
        }
    },
})
```

Hope this is useful to anyone running into the same issue before official solution is landed.

**Comment by ciscoheat** [comment]
Added now in 1.2.0: https://github.com/ciscoheat/sveltekit-superforms/releases/tag/v1.2.0

**Comment by ciscoheat** [comment]
Closing this, the tests are passing.
