### ISSUE TITLE
SvelteKit $navigating store does not update when form submitted

### ISSUE THREAD

**Issue by liegeandlief** [ciscoheat/sveltekit-superforms#201]
When submitting a form I would expect the SvelteKit `$navigation` store to be updated and to have a type of `form` as described at https://kit.svelte.dev/docs/types#public-types-navigation.

But submitting a Superforms form does not update the store.

**Comment by ciscoheat** [comment]
I thought this happened automatically with form actions, but if not, do you know how it works?

**Comment by liegeandlief** [comment]
I think this might be a bug in SvelteKit itself so I've opened this issue https://github.com/sveltejs/kit/issues/10237

**Comment by ciscoheat** [comment]
The timers are probably what you want: https://superforms.rocks/concepts/timers

**Comment by liegeandlief** [comment]
I'm aware of the timers but as far as I can tell they only indicate if a particular form is submitting. I want to know if _any_ form is submitting, ideally without having to add logic to every individual form.

**Comment by ciscoheat** [comment]
Each superForm is a separate instance, so to do that you need to make a derived store that looks at `submitting` for each form on the page, and return a value depending on whether any of them is true. Look at the end of this section for an example: https://svelte.dev/docs/svelte-store#derived

**Comment by liegeandlief** [comment]
Yes I understand I can implement it this way but I was wondering if it could be built into the library itself e.g.

```svelte
<script>
import { anyFormsSubmitting } from 'sveltekit-superforms/client'
import GlobalLoadingIndicator from '$lib/components/GlobalLoadingIndicator.svelte'
</script>

<!-- where $anyFormsSubmitting is a boolean -->
{#if $anyFormsSubmitting}
    <GlobalLoadingIndicator />
{/if}
```

This would save having to manually add logic to every form on the website which could easily be forgotten as there are many different forms across different pages of the site and there will be more in future.

**Comment by ciscoheat** [comment]
It could be possible with a Set, and removing the reference in onDestroy. Can you open a new feature issue about it?
