### ISSUE TITLE
Suggestion: provide zod utilities for processing form string data (or, process in the library, similar to checkboxes and numbers)

### ISSUE THREAD

**Issue by fnimick** [ciscoheat/sveltekit-superforms#205]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a utility which maps empty strings to undefined, meaning we can use required/optional in zod schema rather than checking for string length.

Optionally, the library could map this behavior by default, similar to how checkboxes (booleans) and numerical types are already explicitly converted in `superValidate`. https://github.com/ciscoheat/sveltekit-superforms/blob/main/src/lib/superValidate.ts#L149

**Describe the solution you'd like**
I'd love a `superforms/zod-utilities` containing a `formText()` utility which coerces empty string to undefined, for example, or to have this handled in `superValidate` by default.

**Describe alternatives you've considered**
I've implemented this myself as a zod preprocessor to use in my schemas: `formText(z.string(....))`, inspired by `zod-form-data`:
```
type InputType<DefaultType extends ZodTypeAny> = {
  (): ZodEffects<DefaultType>;
  <ProvidedType extends ZodTypeAny>(
    schema: ProvidedType
  ): ZodEffects<ProvidedType>;
};
const stripEmpty = z.literal("").transform(() => undefined);
const preprocessIfValid = (schema: ZodTypeAny) => (val: unknown) => {
  const result = schema.safeParse(val);
  if (result.success) return result.data;
  return val;
};
export const formText: InputType<ZodString> = (schema = z.string()) =>
  z.preprocess(preprocessIfValid(stripEmpty), schema) as any;
```

**Comment by ciscoheat** [comment]
On the client you can do this with proxies, they have an option for handling empty values: https://superforms.rocks/api#proxy-objects

If you rather need this as a zod helper, I try to keep things simple, so it's best if you provide your own helpers in this case, as you've done. But if you still think it's a useful general addition, can you show the difference in implementation and how much more convenient it would be to use, compared to the current method?

**Comment by fnimick** [comment]
Am I correct in understanding that proxy objects only work when Javascript is enabled on the client and the form is enhanced? The Boolean handling is done in the `superValidate` call, so that it applies on the server side as well even when `use:enhance` is not enabled. In order to have a similar experience (strings coerced to undefined when empty) we need to either handle it in `superValidate` or in a zod type. Handling it in `superValidate` is a breaking change though, so I completely understand if that is off the table.

Would you support me creating a companion library of "useful zod types" in that case? (analogous to `text`, and probably other ones for arrays of checkboxes, etc since I believe `superValidate` won't handle nested booleans)

**Comment by ciscoheat** [comment]
Proxy objects are stores, so they should work in all cases.

**Comment by fnimick** [comment]
@ciscoheat  apologies for the delay getting back, I was on vacation and completely missed this!

I believe the proxy object doesn't work in the case where the form is submitted via HTML, no? Where `use:enhance` is not present, or the client does not have javascript enabled, the raw value of the HTML input is sent. That's my reasoning for needing the processing of empty string -> undefined to happen on the server side.

**Comment by ciscoheat** [comment]
Proxies are also processed in SSR, so as long as you bind to it, it should work even without use:enhance, as with all other stores. If not, can you put up a MRE at [Stackblitz](https://stackblitz.com/edit/sveltekit-superforms-1-testing?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte)?

**Comment by fnimick** [comment]
It actually doesn't appear to work at all - what am I doing wrong? https://stackblitz.com/edit/sveltekit-superforms-1-testing-3bbqbz

The stringProxy does convert the field to undefined in the form store, but there are two issues:
- the default value of the form field is still "", and the proxy doesn't convert to undefined until after you fill it and then clear it
- the server still receives the empty string and therefore the zod schema validation passes, even though the field is not marked as optional (so an undefined value should be rejected). This occurs whether `use:enhance` is present or not.

**Comment by ciscoheat** [comment]
If the schema field is not optional, `undefined` cannot be set on the field. Change the schema to `z.string().optional()` and it will work.
