### ISSUE TITLE
How to build select field from native enum

### ISSUE THREAD

**Issue by ollosh** [ciscoheat/sveltekit-superforms#208]
As mentioned in this [comment](https://github.com/ciscoheat/sveltekit-superforms/issues/12#issuecomment-1601821919) how do you actually build the form using enum value? 

Link to MRE https://stackblitz.com/edit/sveltekit-superforms-1-testing-ik1vsy?file=src%2Froutes%2F%2Bpage.server.ts

**Comment by ciscoheat** [comment]
There was a problem with native enums when specifying the actual value, will be fixed in the next version.
