### ISSUE TITLE
Allow ActionResult errors

### ISSUE THREAD

**Issue by oganexon** [ciscoheat/sveltekit-superforms#209]
**Is your feature request related to a problem? Please describe.**
Quoting from the documentation :
> The biggest difference is that **any [ActionResult](https://kit.svelte.dev/docs/types#public-types-actionresult) with status error is transformed into failure** to avoid form data loss, which will happen when the nearest +error.svelte page is rendered, it will wipe out the form and all data that was just entered.

I would like my errors to stay errors and not transformed into failure, as data loss is not an issue in my case.
I don't want to create custom error logic to undo what has been done by superforms.

**Describe the solution you'd like**
Maybe as a parameter in the `superForm` function
```ts
const { form, enhance } = superForm(data.form, {
  errorIntoFailure: false
})
```

**Describe alternatives you've considered**
I tried to catch failures in the frontend, but it's very sketchy.

**Comment by ciscoheat** [comment]
You do that by setting onError to `apply`, described here: https://superforms.rocks/concepts/events#onerror

**Comment by oganexon** [comment]
Thank you ! I suggest linking to this function in the "difference" section of the documentation

**Comment by ciscoheat** [comment]
Opening this until it's added to the docs.
