### ISSUE TITLE
Form reset doesn't clear message

### ISSUE THREAD

**Issue by nickyhajal** [ciscoheat/sveltekit-superforms#210]
**Description**
When the form resets, the message doesn't also reset and I can't seem to find a way to clear the message

**Comment by ciscoheat** [comment]
Before you `return { form }`, you can set `form.message` to anything with [message](https://superforms.rocks/concepts/messages) or directly. On the client, you can deconstruct the `reset` function and it will remove the message.

**Comment by ciscoheat** [comment]
Clarified reset behavior in documentation.
