### ISSUE TITLE
"No form data sent to superForm, schema type safety cannot be guaranteed." ERROR

### ISSUE THREAD

**Issue by trulycool** [ciscoheat/sveltekit-superforms#212]
**Description**

Thank you so much for this excellent package!

I am very pleased w/ it, and had a working project set up w/ SuperForms 0.6.18, and several forms.

Am just now going thru to update npm packages, and updated to SuperForms 1.1.2...

After the update, I receive the following error when running in dev & preview modes:

> "No form data sent to superForm, schema type safety cannot be guaranteed. Also, no constraints will exist for the form. Set the warnings.noValidationAndConstraints option to false to disable this warning."

The forms actually seem to work & submit. I have been thru the documentation and migration guide, as well as searching the web for that particular error message, but can find nothing.

I am loading SuperValidate from +page.server.js files, not using client side SPA setup. From the documentation, and the fact that the forms submit, it would seem this is fine.

I have tried to match both the documentation, and the code w/in the stackblitz repl, but receive that same error.

The <SuperDebug> component works fine, and shows the input values as entered.

Any insight you might provide on the error will be greatly appreciated 😌🙏

**Comment by ciscoheat** [comment]
Hello, thank you for hanging on since the beginning! It happens because somewhere, null or undefined is being sent to superForm. You need to call superValidate with the schema, usually in the load function, and pass its output on to superForm.

**Comment by ciscoheat** [comment]
Migration guide updated: https://superforms.rocks/migration#superform

**Comment by trulycool** [comment]
Thanks for your quick reply; inspires a great deal of trust in you as the creator 🙏

I don't think this is closed yet however...I've just tried the upgrade again, with same results. Even weirder, 1 of my forms works fine, and the one that doesn't was copied from that and looks identical but for the data fields.

Both load schema from a "schema.js" in the same directory as the +page files.

The 3rd form, that also generates that error on page load has an embedded form, with all the same fields as the working 'contact-us', and loads that same schema.

Recap:
- I have 3 SuperForms
- 1 of them works fine, SuperValidate in +page.server.ts
- 1 embedded in another page, which submits to the above working one, but generates the error
- 3rd one also generates error, but it's +page.server.ts is basically identical to the first form that works, but for different form fields

![image](https://github.com/ciscoheat/sveltekit-superforms/assets/821458/1a14a8fc-85b7-486c-847e-cb56118edd61)

## contact-us | Works fine, no error
```
import { message, superValidate } from 'sveltekit-superforms/server';

let PUBLIC_CONTACT_URL = import.meta.env.VITE_CONTACT_URL;

import { schema } from './schema.js';

export const load = async (event) => {
	// Server API:
	const form = await superValidate(event, schema);
	// Always return { form } in load and form actions.
	return { form };
};

export const actions = {
	default: async (event) => {
		// Same syntax as in the load function
		const form = await superValidate(event, schema);
		// console.log('POST', form);

		// Convenient validation check:
		if (!form.valid) {
			// Again, always return { form } and things will just work.
			// return fail(400, { form });
			// Will return fail(400, { form }) since form isn't valid
			return message(form, 'Invalid form!');
		}

		// TODO: Do something with the validated data
		let data = new FormData();
		data.append('your-name', form.data.name);
		data.append('your-email', form.data.email);
		data.append('your-company', form.data.company);
		data.append('your-telephone', form.data.phone);
		data.append('comments', form.data.comments);
		data.append('newsletter', form.data.newsletter === 'on' ? 'SUBSCRIBE' : 'UNSUBSCRIBE');
		// console.log('MLX page server data: ', data);
		try {
			// console.log('Form URL: ', PUBLIC_CONTACT_URL);
			const response = await fetch(PUBLIC_CONTACT_URL, {
				method: 'POST',
				body: data
			});
			// console.log('MLX Form Response: ', response );
			// handle successful response
			form.data.response = response.status; // add server response to form data object
			// console.log('MLX Form Success: ', form);
			// return { form };
			return message(form, 'Message submitted!');
		} catch (error) {
			// handle error
			console.log('MLX Form Error: ', error);
			console.log('Form URL: ', PUBLIC_CONTACT_URL);
			// return message(form, 'Error submitting form!');
			return { form };
		}
		// Yep, return { form } here too
		// return { form };
	}
};

// test error.html w/ below
// export function load() {
//     throw new Error('😫');
// }

```

## Generates Error, basically the same afaict
```
import { message, superValidate } from 'sveltekit-superforms/server';

let PUBLIC_CONTACT_URL = import.meta.env.VITE_REQUEST_QUOTE_URL;

import { schema } from './schema.js';

export const load = async (event) => {
	// Server API:
	const form = await superValidate(event, schema);
	// Always return { form } in load and form actions.
	return { form };
};

export const actions = {
	default: async (event) => {
		// Same syntax as in the load function
		const form = await superValidate(event, schema);
		// console.log('POST', form);

		// Convenient validation check:
		if (!form.valid) {
			// Again, always return { form } and things will just work.
			// return fail(400, { form });
			// Will return fail(400, { form }) since form isn't valid
			return message(form, 'Invalid form!');
		}

		// TODO: Do something with the validated data
		let data = new FormData();
		// Contact Form DB automatically takes the first 4 values for columns
		// so the order here affects what will be seen there
		data.append('your-name', form.data.full_name);
		data.append('your-email', form.data.email);
		if (form.data.unlisted_product) {
			// use the manually entered proeduct instead
			data.append('product-name', form.data.unlisted_product);
		} else {
			// use the prodcut label instead of product_name, which is actually ACF ID on submit
			data.append('product-name', form.data.product_label);
		}		
		data.append('qty', form.data.product_qty);
		// end Contact Form 7 DB auto columns
		data.append('product-kit', form.data.product_kit);
		data.append('product-number', form.data.product_number);
		data.append('purpose', form.data.purpose);
		data.append('organisation-name', form.data.organisation_name);
		data.append('phone-number', form.data.phone);
		data.append('your-city', form.data.city);
		data.append('your-state', form.data.state);
		data.append('country', form.data.country);
		data.append('special-requirements', form.data.special_requirements);
		data.append('newsletter', form.data.newsletter === 'on' ? 'SUBSCRIBE' : 'UNSUBSCRIBE');
		try {
			// console.log('Form URL: ', PUBLIC_CONTACT_URL);
			const response = await fetch(PUBLIC_CONTACT_URL, {
				method: 'POST',
				body: data
			});
			// console.log('MLX Form Response: ', response );
			// handle successful response
			form.data.response = response.status; // add server response to form data object
			// console.log('MLX Form Success: ', form);
			return message(form, 'Request for Quote submitted!', { status: 200 });
		} catch (error) {
			// handle error
			console.log('MLX Form Error: ', error);
			console.log('Form URL: ', PUBLIC_CONTACT_URL);
			if (!form.valid) {
				return message(form, 'Failed to submit form!', { status: 403 });
			}
		}
		// Yep, return { form } here too
		// return { form };
	}
};

// test error.html w/ below
// export function load() {
//     throw new Error('😫');
// }

```

...the form load code is identical in the contact-us (works) & request-for-quote (which doesn't)

### contact-us & request-for-quote
```
	import { superForm } from 'sveltekit-superforms/client';
	// import SuperDebug from 'sveltekit-superforms/client/SuperDebug.svelte';
	export let data;
	import { schema } from './schema.js';
	const { form, valid, enhance, reset, errors, constraints, delayed, message } = superForm(
		data.form,
		{
			applyAction: true,
			invalidateAll: true,
			clearOnSubmit: 'errors',
			resetForm: true,
			multipleSubmits: 'prevent',
			taintedMessage: 'Are you sure you want leave?',
			validators: schema,
			autoFocusOnError: 'detect'
		}
	); // Client API
```

...so, completely open to my missing something obvious. And if both contact-us forms, which submit to the same place, and use the same schema.js worked, that would be more sensible...

Anything there leap out to you?

Thanks much,
Morgan
🙏

**Comment by trulycool** [comment]
@ciscoheat Thank you so much for responding so quickly!

Your confidence that this was pretty simple fix encouraged me to continue on...and problem is now FIXED!

For SuperForms 1.1.3, there is a breaking change from 0.6.18. The earlier version was more lax about requiring a SuperValidated form on initial page load...

## For embedded forms, you **_must_**:
- include SuperValidate & return form in the +page.js/+page.server.js
- although you may already do this in the actual form page to which you submit the embedded form, the loading page where the form is embedded will have no idea about this validated form object

## For complex forms where you have +page.server.js for the form actions, _and_ +page.js to load data for dependent select drop downs, etc., you **_must_**:
- include SuperValidate & return form in the +page.js/+page.server.js
- YES, that's in both files. While earlier version were fine when it was just included in +page.server.js, in the SuperForms 1.x series, this now causes an error

Thanks again for this most excellent package, and for your timely and helpful response to the issue queue...much appreciated!

All the best,
Morgan
😌🙏

![image](https://github.com/ciscoheat/sveltekit-superforms/assets/821458/133e2f9b-a0d7-4774-84c1-86e07d5e9610)

**Comment by ciscoheat** [comment]
Glad you could fix it! But when you say include (and call?) superValidate in both `+page.js` and `+page.server.js`, did you know that you can use the data from the server load function with the `data` parameter, so you can just pass it on? Docs here: https://kit.svelte.dev/docs/types#public-types-loadevent

The `+page.js` function would look something like this:

```ts
export const load = ({ data }) => {
  return data
}
```

**Comment by trulycool** [comment]
So if I'm understanding you correctly, you are suggesting that by returning data from +page.js I would then avoid importing and running superValidate again in +page.server.js?

Currently I am returning an object from +page.js which itself has 2 objects; form, and another object that has the data I need to build my selects. It was by adding the SuperValidate import & form to the return here that I was able to correct the SuperForms 1.1.3 error.

Some of the automagic of the data load & passing sequence is rather fuzzy to me. I have an alright sense of how the +page.*.js files magically populate data for the +page.svelte files, but have seen nothing about how +page.js & +page.server.js might pass the data object around to each other...

I started with the +page.server.js, and added the +page.js later because I don't need the queries that build the product select dropdown to be server only. That's why originally I didn't do anything w/ superValidate in +page.js, and SuperForms 0.6.18 had no issue w/ that...

I don't want to burn too many of your CPU cycles w/ this, and I am quite happy to have working code & a current version of SuperForms now. However, I really appreciate your responses and insight, and do want to make sure I am using SuperForms as correctly and efficiently as possible...

+page.server.js
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/821458/0958aa3a-df15-4617-8f67-6ce646500ef2)

+page.js
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/821458/8e7ef211-4f55-42fe-9fd7-f8578e8d7eff)

Thanks again,
Morgan

**Comment by ciscoheat** [comment]
In `+page.js` you can deconstruct the `data` parameter, which will contain the form, since you returned `{ form }` in `+page.server.js`. Then just pass it on at the end with `form: data.form`, or, if you want to pass on all server data:

```ts
return { 
  ...data, 
  rfqData: {
    // The other fields
  }
}
```

**Comment by trulycool** [comment]
Perfect, that works great, and no more double schema loading & SuperValidate calls for that route!

Once more, thank you so much! The package is great, and your timely responses and engagement are greatly appreciated!

Am very pleased to have all my frontend dependencies up to date for go live this coming week. Forms are an important part of that, and your quick turn around and help give me **loads** of confidence that I have chosen the right lib for this 😌🙏
