### ISSUE TITLE
formFieldProxy has wrong types for nested data

### ISSUE THREAD

**Issue by caidanw** [ciscoheat/sveltekit-superforms#214]
**Description**
I want to preface with saying this is non-blocking as the issues are type related and can be ignored until a permanent fix is implemented. All the logic for this works beautifully and does work as expected, just the types are weird.

When following the docs for [componentization](https://superforms.rocks/components) I encountered a few weird type issues with `zod.array()` values when trying to use them with `formFieldProxy`.

Here is the schema I'm using (adapted to match the docs)
```typescript
// tagsSchema.ts

import { z } from 'zod';

export const schema = z.object({
  tags: z.string().array().nonempty()
})
```

This is my svelte route, and works almost as expected. We get a type error on the `FormMultiSelect` `field` prop:
`Type '"tags"' is not assignable to type 'FormPathLeaves<{ tags: [string, ...string[]] }>`
```svelte
<!-- +page.svelte -->

<script lang="ts">
  import FormMultiSelect from '$lib/components/ui/FormMultiSelect.svelte';
  import { superForm } from 'sveltekit-superforms/client';
  import type { PageData } from './$types';
  import { schema } from '$lib/models/tagsSchema';
  
  export let data: PageData;
  
  const form = superForm(data.form, {
    dataType: 'json',
    validators: schema,
  });
  const {form: formData, enhance} = form;

  const validTags = ['a', 'b', 'c'];
</script>

<form method="POST" use:enhance>
  <FormMultiSelect
    {form}
    field="tags"
    options={validTags}
    label="Tags"
  />
</form>
```

One way I found to stop the type error is to create a union type on `field` with `FormPathLeaves<z.infer<T>> | any`. Now this works as expected and the logic doesn't have any issues, but I know that adding `| any` is a poor way to handle type errors.

In addition, I found another issue with nested data specifically with the `errors` returned from `formFieldProxy`. The returned type is `Writable<string[] | undefined>` which is incorrect for arrays and should be `Writable<{ _errors: string[] | undefined }>`. I can get around this by just ignoring the error using `@ts-ignore` above a dynamic declaration (can't `@ts-ignore` in the html part of the file).
```svelte
<!-- FormMultiSelect.svelte -->

<script lang="ts">
  import type { Writable } from 'svelte/store';
  import type { FormPathLeaves, ZodValidation } from 'sveltekit-superforms';
  import { formFieldProxy, type SuperForm } from 'sveltekit-superforms/client';
  import type { AnyZodObject, z } from 'zod';
  import AlertError from './AlertError.svelte';
  import MultiSelect from './MultiSelect.svelte';
  
  type T = $$Generic<AnyZodObject>;
  
  export let form: SuperForm<ZodValidation<T>, unknown>;
  export let field: FormPathLeaves<z.infer<T>> | any;
  export let options: string[];
  export let label: string = field;
  
  const { value, errors, constraints } = formFieldProxy(form, field);
  
  // Similar type casting hack as used in docs for checkboxes
  $: selectedValue = value as Writable<any[]>;

  // Required to ignore the type and pull out the errors anyway
  // @ts-ignore
  $: _errors = $errors?._errors;
</script>

<div class="flex flex-col gap-2">
  <label for={field}>{label}</label>
  <MultiSelect
    id={field}
    name={field}
    {options}
    bind:selected={$selectedValue}
    {...$constraints}
    {...$$restProps}
  />
  {#if _errors}
    <AlertError message={_errors} />
  {/if}
</div>
```

**If applicable, a MRE**
Here is my stackblitz MRE, keep in mind the code may be slightly different than what is present in the code blocks above.
https://stackblitz.com/edit/sveltekit-superforms-bug-reporting-rdoi2d?file=src%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment]
Hi, there's a reason for the typing error, it's because the `tags` field isn't a form field, it's an array, and arrays are not supported by `formFieldProxy`. The migration guide explains it here: https://superforms.rocks/migration#seterror-again-validate-proxy-functions

I'll move the documentation for this to the componentization page after the 1.0 release period.

**Comment by ciscoheat** [comment]
Docs updated now: https://superforms.rocks/components#using-a-formfieldproxy
