### ISSUE TITLE
Abstract ``''`` away from consumers as second parameter in setError when wanting to set a top level error

### ISSUE THREAD

**Issue by Hugos68** [ciscoheat/sveltekit-superforms#216]
Current behaviour:
```js
setError(form, '', 'This is an error!');
```
Desired behaviour:
```js
setError(form, 'This is an error!');
```

I believe this can be achieved by checking if the second parameter is a string that matches with any of the zod schema entries, if it doesn't we can safely assume it's the error message instead since no error message will just contain the name of an input (or atleast I hope people aren't that crazy lol)

**Comment by ciscoheat** [comment]
This will be added in the next feature release.

**Comment by ciscoheat** [comment]
Added now in 1.2.0: https://github.com/ciscoheat/sveltekit-superforms/releases/tag/v1.2.0
