### ISSUE TITLE
TextField Component from docs is crashing

### ISSUE THREAD

**Issue by alexfrancavilla** [ciscoheat/sveltekit-superforms#219]
**Description**
The docs about [Componentization](https://superforms.rocks/components) shows a `TextField` component, which when copied as is, results in the following error:
```
TypeError: Cannot read properties of undefined (reading 'toString')
```

Furthermore, inspecting the code with an IDE, shows a longer typescript error on the `{form}` prop:
```
Type '{ subscribe: (this: void, run: Subscriber<{ email: string; password: string; }>, invalidate?: Invalidator<{ email: string; password: string; }> | undefined) => Unsubscriber; set(this: void, value: { ...; }, options?: { ...; } | undefined): void; update(this: void, updater: Updater<...>, options?: { ...; } | undefine...' is missing the following properties from type 'SuperForm<ZodValidation<AnyZodObject>, unknown>': form, formId, errors, constraints, and 14 more.ts(2740)
```

**If applicable, a MRE**
Here is a stackblitz example to reproduce the issue:
https://stackblitz.com/edit/vitest-dev-vitest-xqw4v1?file=src%2Froutes%2FLoginForm.svelte

**Comment by ciscoheat** [comment]
You haven't followed all the instructions, the `form` prop for `TextField` takes the whole SuperForm, not the form store inside its object. And the other prop is called `field`, not `name`.

With these changes, everything works: https://stackblitz.com/edit/vitest-dev-vitest-rj4hhb?file=src%2Froutes%2FTextField.svelte,src%2Froutes%2FLoginForm.svelte

**Comment by alexfrancavilla** [comment]
@ciscoheat You're absolutely right, looks like I really need a break. Thanks for your quick help and nice library :)

**Comment by ciscoheat** [comment]
I know the feeling. :) Glad you like it!
