### ISSUE TITLE
When a non-json response is received by the client, form is unable to provide a useful error with `onError` event handler

### ISSUE THREAD

**Issue by diericx** [ciscoheat/sveltekit-superforms#227]
**Description**
When using a SuperForm with `use:enhance`, if the client receives a request such as a `413` with a string body (e.g. `Body is too large`) the form is unable to provide a useful error message. The value provided to the `onError` event handler is simply `SyntaxError`. 

**If applicable, a MRE**
https://github.com/diericx/sveltekit-superforms-parse-error

As noted in the README, my browser in production was not giving me the `413` message which made this difficult to debug. 

This is the code in the node adapter that I was hitting
https://github.com/sveltejs/kit/blob/23d1df702f0fd77983040404352d8d83fd1dd8a1/packages/kit/src/exports/node/index.js#L27

There is a note here about bypassing some sveltekit error handling, maybe that is why?
https://github.com/sveltejs/kit/blob/23d1df702f0fd77983040404352d8d83fd1dd8a1/packages/kit/src/exports/index.js#L21

**Comment by ciscoheat** [comment]
There's not much to do, since Superforms uses SvelteKit's `use:enhance`, which returns an `error` ActionResult with the message set to the exception message, in case of failed parsing.

**Comment by ciscoheat** [comment]
I've added a FAQ question about it, can't do much more except bypassing the whole `use:enhance` behavior from SvelteKit, and that's quite a big task.

https://superforms.rocks/faq#im-getting-jsonparse-errors-as-response-when-submitting-a-form-why
