### ISSUE TITLE
Error received when submitting a non-superform that has inherited an Superform within its Layout

### ISSUE THREAD

**Issue by saturnonearth** [ciscoheat/sveltekit-superforms#230]
**Description**
I am using a Superform inside a navbar that the user has access to. This navbar is located in the Layout. I noticed that if I have a normal run of the mill Svelte progressively enhanced form on a +page.svelte that inherits the Layout, and in turn, the Superform, I will get an error when trying to submit the "normal" form.

**If applicable, a MRE**
Go here: https://stackblitz.com/edit/sveltekit-superforms-1-testing-v3y6fy?file=src%2Froutes%2Fnormal-form%2F%2Bpage.svelte

And navigate to `/normal-form` in the URL. Then try to submit the bottom form (within the green box), and view the browser console window.

**Comment by ciscoheat** [comment]
Thanks, will take a look asap! Got some other updates coming soon as well.
