### ISSUE TITLE
dateProxy problem - Type of property 'prototype' circularly references itself 

### ISSUE THREAD

**Issue by ftognetto** [ciscoheat/sveltekit-superforms#237]
Hello, I have a problem using dateProxy, but in general with any kind of proxy.

When I try to use a dateProxy like

```
const startAt = dateProxy(form, 'startAt',  { format: 'datetime-local' });
```

I get an error

```
Type of property 'prototype' circularly references itself in mapped type '{ [K in keyof Blob]-?: K extends string ? NonNullable<Blob[K]> extends object ? `${K}${NonNullable<Blob[K]> extends unknown[] ? "" : "."}${NonNullable<...> extends Date | Set<...> ? never : StringPath<...> & string}` : never : never; }'.ts(2615)
```

I also add the image, maybe it's a typescript problem but I tried to update typescript and svelte version without success.

The form is working fine, but the problem is that this error isn't passing in `svelte check`

<img width="1048" alt="Screenshot 2023-07-24 alle 09 59 28" src="https://github.com/ciscoheat/sveltekit-superforms/assets/47910896/c5f8fe2a-7c7d-44ef-9637-e0e31c4f8d64">

Someone has experiences this or has a solution?
Thank you

**Comment by ciscoheat** [comment]
Hi, I see no errors like this in the test suite. Does the same problem occur if you test it in a new SvelteKit project? If you can make a MRE of this, I can take a closer look.

**Comment by ftognetto** [comment]
Hi @ciscoheat sorry but I’m not finding a way to reproduce this. It also happen on setError server side.

Anyway if I start a new project it doesn’t happen, also it doesn’t happen on other projects where I use superforms even on the same machine and with same npm packages version…

So there should be something strange on my side, which is not related to the library. I will close the issue thank you anyway
