### ISSUE TITLE
Superforms and sveltekit-flash-message integration examples

### ISSUE THREAD

**Issue by benquan** [ciscoheat/sveltekit-superforms#238]
I am currently using superforms and have been playing around with sveltekit-flash-messages at the same time, according to [https://superforms.rocks/flash-messages](https://superforms.rocks/flash-messages) the two projects should work seamless between each other, but do you have a working sample of such a project? I browsed through you list of playgrounds, but only found normal superforms projects. This would help a lot.

Thanks!

Ben

**Comment by ciscoheat** [comment]
Unfortunately sveltekit-flash-message doesn't play well with Stackblitz, but using it is just as simple as setting it up and throw its redirect function. Here's a gist: https://gist.github.com/ciscoheat/ad9e5c6279fb3502514df1964f67c577

That should work in most cases, but if you need some form-specific integration, see if the documentation helps.

**Comment by benquan** [comment]
Managed to work it out based on documentation.
