### ISSUE TITLE
Validator relying on the value of another field

### ISSUE THREAD

**Issue by antony** [ciscoheat/sveltekit-superforms#240]
**Is your feature request related to a problem? Please describe.**
Reading through [the docs](https://superforms.rocks/concepts/client-validation) for client-side validation, it isn't apparent how to make one validator dependent on another field's value.

For example, I have two dates, start and end. I want to validate that end is always after start.

Is this something missing, or is it just not clear from the documentation?

**Describe the solution you'd like**
Something like a second param to the validator which has the value of other fields within the form.

**Describe alternatives you've considered**
None, really - trying to depend on $form wouldn't work as the validation declaration is part of the initialisation for it.

**Comment by ciscoheat** [comment]
You can do that with refine: https://superforms.rocks/concepts/error-handling#setting-field-errors-with-refine

**Comment by ciscoheat** [comment]
Closing this, the issue seems to be resolved?

**Comment by antony** [comment]
Hey Andreas, yep! Sorry I'm not super familiar with zod, so I'll take a look.

Thanks
