### ISSUE TITLE
Introduce ErrorMessage helper component for rendering form validation messages

### ISSUE THREAD

**Issue by mcmxcdev** [ciscoheat/sveltekit-superforms#242]
**Is your feature request related to a problem? Please describe.**

I am trying out this amazing lib for the first time and noticed that I would have to specify the index to get a string as error message:
```
{#if $errors.foo}
	<div class="text-error">{$errors.foo[0]}</div>
{/if}
```

It's understandable since there can be multiple validation errors inside the `$errors` array.

As I have learned from the usage of `react-hook-form`, there was https://react-hook-form.com/docs/useformstate/errormessage which automatically picked the error message even if there were multiple triggered by zod.

The implementation looked like this:
```
<ErrorMessage
        errors={errors}
        name="singleErrorInput"
        render={({ message }) => <p>{message}</p>}
      />
```

**Describe the solution you'd like**
It would be great to have this for `sveltekit-superforms` as well

**Describe alternatives you've considered**
Write a wrapper ourselves

**Comment by ciscoheat** [comment]
Thanks for the suggestion, I have decided to keep the library UI-agnostic though, so there may be some example components on the website in the future, but they won't be a part of the library itself.
