### ISSUE TITLE
Help: Forms with dynamically generated fields inside dynamically generated accordeon

### ISSUE THREAD

**Issue by ic-dominic** [ciscoheat/sveltekit-superforms#247]
I've been struggling with implementing the following logic using superforms in my sveltekit app:

My database has certain entities and another table with some columns that define goals for those entities.
These columns might change in the future so I need to dynamically generate input elements for them.
Naturally, I also need to loop over the entities to create the accordeon, since they will definitely change in the future.

That is what I have as so far:

![image](https://github.com/ciscoheat/sveltekit-superforms/assets/141314468/9cbeffde-2e00-40d6-bc72-dbff0762897b)

## The goal
I want to allow users to open one of the accordeons at a time to edit the goal values for that entity. By clicking the `Save` button, a server action is called which updates the database based on the `ID` of the entity I received through the form.

## Problem

Do I generate a form per entity? If so, how can I link any given entity to the given form? I've read up about [nested data](https://superforms.rocks/concepts/nested-data) but I'm not entirely sure that solves my issue since all the actual fields are *also* dynamic.

Currently, I display the entities and the relevant goals using

```svelte
<Accordion>
    {#each entities as entity}
        <AccordionItem>
            {#each Object.entries(entity) as [goal, value]}
                <Input type="number" name={goal} {placeholder} bind:value />
...
```

but I'm not sure what the correct way to link one or more forms is, or how to handle this in general, especially since typescript won't just let me grab any field off of the `entity` object.

**Comment by ciscoheat** [comment]
Any problems with this still, or can it be closed?

**Comment by ic-dominic** [comment]
Shoot, I totally forgot I opened this issue!

I've gone on to work on another feature in the meantime since I was stuck but I'll see if I can get back to this today and then I'll update you on whether or not I need any further assistance.

Thank you so much for your help!

**Comment by ic-dominic** [comment]
After continuing to work on this feature I've decided it to be easier to implement UI to allow editing each parent entity individually, which makes working with the form much easier.
I suppose this would have been the cleaner approach all along anyways 😄 

Not sure if you want to keep the issue open or just have someone reopen it if they encounter the same problem in the future.

**Comment by ciscoheat** [comment]
Ok, good to hear you've managed to simplify things! I'll close it then.
