### ISSUE TITLE
DateProxy not working for specific date

### ISSUE THREAD

**Issue by Josh-Nicholson** [ciscoheat/sveltekit-superforms#250]
**Description**
Typing the date 10/08/1994 into a date field that is using dateProxy for the bind value does not work

**If applicable, a MRE**
Go to the following link https://superforms.rocks/concepts/proxy-objects

Before typing:
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/9265897/14e1d844-375e-4417-be7f-29feb53af66b)

Typed in date and month:
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/9265897/7b332d1b-b99c-4290-9102-ac26b172e9a2)

As soon as you type the 1 digit from 1994 the following happens:
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/9265897/dd9160a7-fd90-4bf2-ad37-355a7ad60f4f)

Trying this on my own input proves it is an issue with dateProxy.
Without using the proxy the date input allows 10/08/1994

**Comment by ciscoheat** [comment]
The problem is that the date input will clear all input when it encounters a valid but non-supported date. In this case 10/08/1 (Year 1). So the bi-directional communication with bind:value and the proxy won't work in this case. You have to do something like:

```svelte
<input
  type="date"
  name="proxyDate"
  value={$proxyDate}
  on:blur={(e) => ($proxyDate = e.currentTarget.value)}
/>
```

**Comment by ciscoheat** [comment]
Updated documentation for the date input field and proxies now. https://superforms.rocks/concepts/proxy-objects#date-input-issues
