### ISSUE TITLE
Persist files after validation

### ISSUE THREAD

**Issue by Lzadhito** [ciscoheat/sveltekit-superforms#254]
**Is your feature request related to a problem? Please describe.**
https://superforms.rocks/faq#how-to-handle-file-uploads
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/25606110/bd5a56ba-3e20-4075-81b7-5dfc9bb3db6b)

Firstly, thank you very much for the great library, I really appreciate your hard work on this. 

The problem is getting undefined for files after validation results the file need to be reupload when the form failed. It is very frustrating when the user need to reupload the file everytime the form failed. Is it something wrong with my implementation or this is a feature of superforms?

**Describe the solution you'd like**
validation need to persist all form value.

**Comment by ciscoheat** [comment]
[Devalue](https://github.com/Rich-Harris/devalue) doesn't handle file uploads, so it's just not possible to re-send the whole file, which would be an awful waste of traffic as well. It's a general problem for all form handling, so you'll have to save the file temporarily on the server, based on what was posted in FormData.

**Comment by ciscoheat** [comment]
Closing this, as it's an issue not directly related to Superforms.

**Comment by ciscoheat** [comment]
Just an additional note, that [client-side validation](https://superforms.rocks/concepts/client-validation) is the best way to prevent potentially large file uploads before all form data is valid.
