### ISSUE TITLE
Message doesn't seem to be updated when using form as component

### ISSUE THREAD

**Issue by perostlin** [ciscoheat/sveltekit-superforms#255]
- [x] Before posting an issue, read the FAQ at https://superforms.rocks/faq and search the previous issues.

**Description**
When using the form as a component, the message store doesn't get updated with the value passed from the action on the server-side.
Others work inside the form component, like submitting, but unable to get the message updated.

This is how the form component look like:
```svelte
<script lang="ts">
  import type { SuperValidated } from "sveltekit-superforms";
  import { superForm } from "sveltekit-superforms/client";
  import type { ZodObject } from "zod";

  export let data: SuperValidated<ZodObject<any>>;
  export let method: "POST" = "POST";
  export let action: string;

  const { enhance, message } = superForm(data);
</script>

<form {method} {action} use:enhance>
  <div class="flex flex-col gap-9">
    <slot />
  </div>
  {#if $message}
    {$message}
  {/if}
</form>
```

And this is how I'm using it on my page:
```svelte
<script lang="ts">
  import { superForm } from "sveltekit-superforms/client";
  import type { PageData } from "./$types";
  import Form from "$src/components/form/actions/form.svelte";

  export let data: PageData;
  const form = superForm(data.form);

  const { submitting } = form;
</script>

<Form data={data.form} action="?/login">
  // submitting is used in here
</Form>
```

**Comment by ciscoheat** [comment]
Every call to `superForm` creates a separate instance, so "mixing" them as you do can create undefined behavior. It's recommended that you use only one instance for each property of `PageData`, and in general follow these recommendations on how to use it with components: https://superforms.rocks/components

Here's a [Stackblitz example](https://stackblitz.com/edit/sveltekit-superforms-componentization?file=src%2Flib%2FForm.svelte) of a form component, for example.

Try that out and see if it works better.

**Comment by perostlin** [comment]
That worked better, thank you!
