### ISSUE TITLE
How to change the type of form.data after submission?

### ISSUE THREAD

**Issue by NikoKS** [ciscoheat/sveltekit-superforms#256]
Hello, thank you for this awesome library! I'm trying to figure out how to change the type of form.data after a form is submitted.

Consider the following:
server:
```js
const schema = z.object({ id: z.optional(z.string()) }
const schemaArray = z.array(schema.required())

export const load: PageServerLoad = async () => {
  const form = await superValidate(schema)
  pageData: z.array(z.infer<typeof schemaArray>()
  return { form, pageData }
}

export const actions: Actions = {
  default: async ({ request }) => {
    const form = await superValidate(request, schema);
    // assign id
    form.data.id = 'asdf'
    return { form }
  }
}

```

client:
```ts
export let data;

const { form, enhance } = superForm(data.form, {
  onUpdated({ form }) {
    if (form.valid) {
      // form.data.id cannot be undefined anymore, but still giving type error
      data.pageData.push(form.data) // typescript error here
      data.pageData = data.pageData
    }
  }
});
```

in the example above, form.data.id cannot be undefined anymore, but still giving type error since in pageData, `id` can't be undefined, but in form.data, `id` can be undefined. Id needs to be able to be undefined since it will be assigned by the server (database) when submitted.

I am relatively new to typescript, so any input is welcomed.

**Comment by ciscoheat** [comment]
Hi, please make a MRE at Stackblitz, and describe how to reproduce the problem, and I'll take a look. Use this as a template: https://stackblitz.com/edit/sveltekit-superforms-1-testing?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte

**Comment by NikoKS** [comment]
never mind, apparently I can just push the data in the page.server.ts
