### ISSUE TITLE
Type of params not inferred for onSubmit

### ISSUE THREAD

**Issue by jdreben** [ciscoheat/sveltekit-superforms#259]
Hello! Love Superforms. I have a question.

I do not see the type of the onSubmit function's input `params` being inferred, and because of that I can't de-structure it without an as assertion to make the type checker happy. This is relevant for TypeScript only. Example code --

```typescript
const { form, errors, submitting, enhance } = superForm(someSchema, {
  id: 'etc',
  dataType: 'json',
  invalidateAll: true,
  onSubmit(params) {
     // etc
  }
}
```
This results in `params: unknown`. The signature of the function is `onSubmit?: ((...params: unknown[]) => MaybePromise<unknown>) | undefined`	

I believe this is the relevant line. Instead of doing a spread operator if this function's signature can be made to follow the form of the others maybe?
https://github.com/ciscoheat/sveltekit-superforms/blob/11f2775d794eeeeb0d209c7329757e7ff6445e68/src/lib/client/index.ts#L89C5-L89C42

Relevant documentation here https://superforms.rocks/concepts/events#onsubmit

**Comment by ciscoheat** [comment]
This is what I get with a simple SvelteKit project when using onSubmit:

<img width="562" alt="2023-09-11 13_06_53-Window" src="https://github.com/ciscoheat/sveltekit-superforms/assets/130450/d57bdf88-04b5-4c89-b344-cc5aceb45b8e">

So it seems to work, what do you get if you create a new project with just the onSubmit event?

**Comment by jdreben** [comment]
That indeed does seem to work… I think updating will resolve this problem in the project I encountered it in. My apologies for raising a false flag. Thanks for the response.
