### ISSUE TITLE
Type error when using status messages and formFieldProxy

### ISSUE THREAD

**Issue by Gerschtli** [ciscoheat/sveltekit-superforms#260]
- [x] Before posting an issue, read the FAQ at https://superforms.rocks/faq and search the previous issues.

**Description**
When you define a custom type for the status messages and set this when calling `superValidate` (https://github.com/Gerschtli/superforms-message/blob/master/src/routes/%2Bpage.server.ts#L9), then typescript will report an error when you use this form and a `formFieldProxy` (https://github.com/Gerschtli/superforms-message/blob/master/src/routes/%2Bpage.svelte#L13).

The current workaround is to cast the form to the message type `unknown`.
```js
const formData = superForm(data.form);

// This type cast should not be necessary, it should infer the type SuperForm<typeof schema, Message>
const x = formFieldProxy(formData as SuperForm<typeof schema, unknown>, 'name');
```

**If applicable, a MRE**
Based on the stackblitz example: https://github.com/Gerschtli/superforms-message

It was not possible to completely build this in stackblitz because typescript did not seem to work in *.svelte files.

**Comment by ciscoheat** [comment]
Will be fixed in the next release.
