### ISSUE TITLE
Global type for status messages

### ISSUE THREAD

**Issue by Gerschtli** [ciscoheat/sveltekit-superforms#261]
**Is your feature request related to a problem? Please describe.**

In my app that I am currently building, I am using the superforms status messages. I defined a type like
```ts
export type SuperFormsMessage = { type: 'error' | 'success'; message: string };
```
and everytime I call `superValidate`, I need to call it like 
```ts
superValidate<typeof schema, SuperFormsMessage>(schema)
```
to ensure type safety. In my case, this is unnecessary boilerplate code because every form uses the same `SuperFormsMessage` type for the status messages.

**Describe the solution you'd like**

I would like to see the possibility to define a global type for the status message (similar to how the flash-message library handles it), e.g.:
```ts
declare global {
	declare namespace Superforms {
		type Message = {
			type: 'error' | 'success';
			message: string;
		}
	}
}
```
This type (whenever it is defined) will then be used automatically as the default type when calling `superValidate`. As long as this type would be undefined, the current behaviour can remain. When you want to use a different message type, you could still manually override it like
```ts
superValidate<typeof schema, SpecialMessage>(schema)
```
I think this could help a lot for apps where you want to use the same status message type for all forms (to help creating reusable components or to keep things consistent and simple).

**Describe alternatives you've considered**

I could create a wrapper function around
```ts
superValidate<typeof schema, SuperFormsMessage>(schema)
```
but I think, it could be helpful for others too, to get it supported upstream.

**Comment by ciscoheat** [comment]
Should be working now, define it in `App.Superforms.Message`:

**src/app.d.ts**

```ts
declare global {
  namespace App {
    // interface Error {}
    // interface Locals {}
    // interface PageData {}
    // interface Platform {}
    namespace Superforms {
      type Message = {
        type: 'error' | 'success';
        message: string;
      }
    }
  }
}
```
