### ISSUE TITLE
How to prefill some values but don't trigger any validation for the other fields?

### ISSUE THREAD

**Issue by Gerschtli** [ciscoheat/sveltekit-superforms#262]
I have an use case where I want to prefill one form field with a value like
```ts
const schema = z.object({
	name: z.string().min(1),
	email: z.string().email()
});

const form = await superValidate({ name: 'default' }, schema);
```
but I don't want any error messages (in this example "email is required") to appear for this form yet. The form should only be validated on form submit.

My current workaround is to manually set `$value` to my initial value in the component, but it feels like there should be a better solution.

https://stackblitz.com/edit/sveltekit-superforms-1-testing-h1w3mq?file=src%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment]
You can use the errors option for that: https://superforms.rocks/concepts/error-handling#initial-form-errors

**Comment by Gerschtli** [comment]
Thank you very much for the quick reply, this option is exactly what I needed!
