### ISSUE TITLE
 Error: No Superforms validator found:

### ISSUE THREAD

**Issue by happysalada** [ciscoheat/sveltekit-superforms#266]
- [X] Before posting an issue, read the FAQ at https://superforms.rocks/faq and search the previous issues.

**Description**
when using `    dataType: 'json'`
and controlling the form programatically,  I get the error
```
Error: No Superforms validator found: shareholders,1,id_issuance_date
    at _validateField (clientValidation.js:319:19)
    at validateField (clientValidation.js:190:26)
    at validateChange (formEnhance.js:69:33)
    at HTMLFormElement.checkBlur (formEnhance.js:98:13)
```

for context, here is my form
```
const shareholdersSchema = z.object({
  business_id: z.string(),
  shareholders: z.object({
    first_name: z.string().optional(),
    middle_name: z.string().optional(),
    id_issuance_date: z.date().max(new Date()).optional(),
  }).array()
})
```

and I have a button that adds form fields for new shareholders
```
          on:click={() =>
            ($form.shareholders = [...$form.shareholders, {}])}
```
when I show the new form fields for the new shareholder, I get this error message.
I don't have the error message about other field, just the id_issuance_date.

**Comment by ciscoheat** [comment]
It looks like you're using validators, which expects properties for the object in the schema, even if they are `undefined`, but you're adding an empty object to the shareholders array. What does the call to `superForm` look like?

Can you try adding the properties to the object, set them to undefined and see what happens?

**Comment by happysalada** [comment]
oh it looks like
```
  const { form, errors, constraints, enhance, submitting } = superForm(formData, {
    dataType: 'json',
    taintedMessage: null,
    validators: {
      business_id: (input) => (input ? undefined : 'Please fill business name first')
    },
    onError({ result, message }) {
      console.log('error');
      console.log(result);
      console.log(message);
    }
  });
```
what should a validator look like for an array ?

**Comment by ciscoheat** [comment]
It should be just another object inside the validators, but I think I need a reproduction of this error at Stackblitz for figuring this out. You can use this as a template: https://stackblitz.com/edit/sveltekit-superforms-1-testing?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte

**Comment by happysalada** [comment]
thanks for the quick answer, I'm going to try to put some time into this, this weekend.

**Comment by happysalada** [comment]
oh wow, you're amazing!

**Comment by ciscoheat** [comment]
Should be fixed now in 1.7.0! Here's how the validators should look for arrays and nested objects:

```ts
validators: {
  business_id: (id) => id ? null : 'Please fill in business name',
  shareholders: {
    id_issuance_date: (date) => (date ? null : 'Fill in date')
  }
}
```

**Comment by ciscoheat** [comment]
Any confirmation that it works now?

**Comment by happysalada** [comment]
I don't want to leave you waiting for this, so I'm going to close this now and I will re-open if there is any problem.
Thanks again for the quick feedback!
