### ISSUE TITLE
Type of property 'prototype' circularly references itself in mapped type

### ISSUE THREAD

**Issue by ftognetto** [ciscoheat/sveltekit-superforms#267]
Hello, I have already asked this question but didn't manage to reproduce it, so I open a new issue.

This is what is happening:

```
Type of property 'prototype' circularly references itself in mapped type '{ [K in keyof Blob]-?: K extends string ? NonNullable<Blob[K]> extends object ? `${K}${NonNullable<Blob[K]> extends unknown[] ? "" : "."}${StringPathLeaves<...> & string}` : never : never; }'.
```
<img width="882" alt="Screenshot 2023-09-14 alle 15 09 08" src="https://github.com/ciscoheat/sveltekit-superforms/assets/47910896/6cc9e501-f7f1-4d96-a679-304c4e14d9f9">

And it happen when I add a file field to the schema. 
eg:
```
export const customerSchema = z.object({
	id: z.string(),
	name: z.string(),
        ....
        logo: z.string().nullable(),
	_logo: z.instanceof(File).optional(),
});
```

Ps. I'm using shadcn-svelte in the screenshot but it's the same if I use super forms directly.

Is someone experiencing this and found a solution? It also breaks svelte check, so I cannot deploy without removing the file from schema.

**Comment by ciscoheat** [comment]
Closing, as files aren't supported in the schema.
