### ISSUE TITLE
Make the "tainted" store more accurate

### ISSUE THREAD

**Issue by saturnonearth** [ciscoheat/sveltekit-superforms#268]
**Is your feature request related to a problem? Please describe.**
I want to tell if the data in the form is "stale" or "dirty" in the sense that it does not match what was there on Load or when the form was initialized. If the user adds something, and then erases it, or enters in the exact same thing, this is not "dirty" or "tainted" in my mind.

**Describe the solution you'd like**
Adjust the "tainted" store so it would remove the property associated with the field if the data in the field matches exactly what was already there before.. Aka, if I type a letter, and then backspace, it should no longer be tainted.

**Describe alternatives you've considered**

I was using [just-compare](https://www.npmjs.com/package/just-compare) to previously do this myself, but saw that the "tainted" store was "almost" what I needed, but just needed the above change.

**Comment by ciscoheat** [comment]
That would be a breaking change unfortunately, and the tainted status is also tied to the error display, so you have to do this manually. Hopefully not too much work. :) I'll keep this open for v2.0!

**Comment by ciscoheat** [comment]
This one is ready for testing, migration guide at: https://superforms.rocks/migration-v2/

**Comment by ciscoheat** [comment]
Passing all the tests in alpha version, so closing this.
