### ISSUE TITLE
Get fields of nested objects

### ISSUE THREAD

**Issue by happysalada** [ciscoheat/sveltekit-superforms#274]
**Is your feature request related to a problem? Please describe.**
I have a nested form and I would like to display a count of the remaining fields to complete.
So something like 7/13 (completed/total) to indicate to the user how much progress he has made.

**Describe the solution you'd like**
My solution for a non nested form is to use the fields attribute and the errors attribute.
For nested data, the fields attribute returns the following
<img width="700" alt="Screen Shot 2023-10-05 at 1 51 33 PM" src="https://github.com/ciscoheat/sveltekit-superforms/assets/5317234/14a2968e-a80e-40b0-ad0f-f135162bd129">

the "shareholders" field lacks the inner fields information.
It would be good to have those just so I could get a full count of how many fields are left to fill out.

**Describe alternatives you've considered**
I don't know of an alternate way to achieve this but I would be happy to have suggestions.

**Additional context**
I'm using two forms here. A schema containing only optional fields to enable the user to "save" the form to the database midway.
Then I'm using another "strict" schema that will return errors for missing fields. The errors will inform the number of fields left to fill.

**Comment by ciscoheat** [comment]
Can you use [allErrors](https://superforms.rocks/concepts/error-handling#listing-errors) on the strict schema to do the counting?

**Comment by happysalada** [comment]
using allErrors should give me a count of what is left to do.
I won't get the count of elements already filled.
I'm going to change the ui a bit to just show the fields left and not the total field counts to simplify things a bit here.

**Comment by happysalada** [comment]
Actually having an allFields store could help in this case, not only a store that provides the fields on the errors like allErrors does, but also the other fields as well.
I realise that the use case is a little weird, so I really think about dropping trying to get the total field count, and just showing the user the errors left in the form.

**Comment by ciscoheat** [comment]
Ok, in any case I think using the [Object methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) on `$form` can get you a long way, eventually together with `$tainted`.

**Comment by happysalada** [comment]
I'm just going to close this issue.
It would be nice to have the nested fields available as well, but I'm going to process differently for now.
