### ISSUE TITLE
Create or Update use case.

### ISSUE THREAD

**Issue by happysalada** [ciscoheat/sveltekit-superforms#277]
Hi, first of all, thank you for the library!

I'm asking about a use case when making a create or update for a resource.
If the object has been created already, the docs talk about populating the supervalidate function with data from the database.
On the client side, the data from the database shows.
If the user modifies the data (say a single field), then only a single field is tainted. If your validation has required fields that are other than the tainted field, validation will fail.
So I'm guessing that the code on the server side has to handle the update.

while the load function would be something like
```
    const form = await superValidate(data, schema);
```

what does the submit action server code look like though ?
something like 
```
    const form = await superValidate(request, schema);

    if (!form.valid) {
      return fail(400, { form });
    }

    try {
      const existing_id = form.data.id;
      if (existing_id) {
        // make an update of the object with form data
      } else {
        // create a new object with form data
      }
```
The problem with that code is that on an update that doesn't contain the necessary fields from the schema, then the validation fails, and a 400 is returned.

I'm wondering if I'm making an anti pattern here or if I'm missing something obvious.

**Comment by ciscoheat** [comment]
Hey, did you check the CRUD tutorial on the website? It could be related: https://superforms.rocks/crud

**Comment by happysalada** [comment]
I had followed a similar approach but wasn't using bind in some of the form values.
Sometimes the content doesn't get submitted if it's not bound to the form value (for example if it's just a string value).
Thank you for the recommendation.
