### ISSUE TITLE
derived() expects stores as input, got a falsy value

### ISSUE THREAD

**Issue by boian-ivanov** [ciscoheat/sveltekit-superforms#278]
**Description**
First of all I have to say that I've been loving the experience with the library. So when I looked into componentization of the code and found a full on example it was great. Issue comes when I set up the example as an input component and reached the following error:
```
index.js:137 Uncaught (in promise) Error: derived() expects stores as input, got a falsy value
    at derived (index.js:137:9)
    at formFieldProxy (proxies.js?v=d0b35fe4:147:26)
    at Input.svelte:27:39
    at run (utils.js:41:9)
    at Array.map (<anonymous>)
    at Component.js:47:48
    at flush (scheduler.js:99:5)
    at init (Component.js:164:3)
    at new Root (root.svelte:21:25)
    at createProxiedComponent (svelte-hooks.js?v=d0b35fe4:341:9)
```
I assumed that at some place the store is not properly setup (I had it as a server fed form with `dataType: 'json'`), but irregardless of what I did, I could not find out what issue was causing. I've gone through most of the related issues here, but apart from one of the issue that was regarding the updated docs, I found nothing. 
I'd be really grateful if you have any ideas regarding the topic.

### More info regarding the issue
I'm trying to setup a component such as this one for my forms `<Input {form} field="name" />`. 
I've tried to run it `onMount` or as a computed value, neither of them helped. 
Based on the error, it seems that the value passed to the `formFieldProxy` is not a store, yet it's a fully functional store coming from a `const { form } = superForm(data.form, {dataType: 'json'});`

**Comment by boian-ivanov** [comment]
On a second look in the source code of the proxy function I think that the issue might be due to the lack of the `form.tainted`. Since the form was setup on the server & passed to the client to get the expected methods via `superForm(data.form)` it seems that the `tainted` property wasn't there. 
After a bit more looking around, I figured previously the recommended approach for setting up the fields was like this:
```
const { form } = superForm(data.form);
```

Yet the if you're willing to setup a component around this, you need to pass in all the superForm properties like so:
```
const form = superForm(data.form);
...
<Input {form} field="name" />
```

To be fair, I don't think it's a bug, but it might be a good idea to add it in the examples for setting components 😅 
I'll leave this open for a bit, just so you can have a look if it's worth adding it in the docs.

**Comment by boian-ivanov** [comment]
From a third look in the docs, you technically had it shown in one of the examples, so I'll just close this issue as it seems to be resolved :)

**Comment by ciscoheat** [comment]
Hey, glad to hear that you like the library, and that you eventually found the solution! Using `form` as an identifier for both the `superForm` object and the form data store can be a bit confusing. I haven't found a better way to name them though, if you have any ideas, let me know.

**Comment by boian-ivanov** [comment]
@ciscoheat Maybe a specific warning that for a `formFieldProxy` you need the whole object that `superForm` will provide, as opposed to just the destructed form value for a `fieldProxy`. Or you could just rename it to `formObject` or `formData` or maybe even `superFormData`. 
Either way, it does work, but if you're reading between the lines of the documentation, it's easy to miss. Anyway, once more thank you for developing this library 🙏
