### ISSUE TITLE
SuperDebug component - collapsibled by default

### ISSUE THREAD

**Issue by ltdletrungduc** [ciscoheat/sveltekit-superforms#279]
**Is your feature request related to a problem? Please describe.**
I read that we have `collapsible` prop to make the SuperDebug component collapsible. So can we make it collapsed by default

**Describe the solution you'd like**
Add a boolean prop named `collapsed` for default collapsed or not
```svelte
<SuperDebug data={posts} display={dev} collapsible collapsed={true} />
```
**Additional context**
I think the component already has a `collapsed` variable to control opened or collapsed but it's not exported
```svelte
<script>
  // Line 105
  /**
   * Will show a collapse bar at the bottom of the component, that can be used to hide and show the output.
   *
   * Default is `false`.
   */
  export let collapsible = false;

  let collapsed = false;
  if (browser && collapsible) setCollapse();
 // The rest of component
</script>
```

**Comment by ciscoheat** [comment]
Sure, that can be added to the next release. I'm just wondering how to treat the state if it is uncollapsed and thereby saved in `sessionStorage`: Should it take precedence over the hardcoded value in the prop, or should it always be collapsed, as `{true}` signifies?

**Comment by ltdletrungduc** [comment]
@ciscoheat I think 1st render the component will be take the prop, next render will take the state in `sessionStorage`.

**Comment by ciscoheat** [comment]
Added now with 1.9.0:

```svelte
<SuperDebug data={$form} collapsible collapsed />
```
