### ISSUE TITLE
HTTP4.. is not considered as an onError() event

### ISSUE THREAD

**Issue by rogiervandenberg** [ciscoheat/sveltekit-superforms#292]
**Description**
I have a global authorization hook in my `hooks.server.ts` that throws a 403 when not being allowed to do something on a specific route. When using Superforms and posting to a URL that is not allowed, the returned 403 is not recognized as an error and can thus not be caught in the UI (my request is blocked though, but there is just nothing happening for the user). Superforms just stops after onSubmit().

My `hooks.server.ts` creates a response of HTTP 403 with the contents of:

```json
{
    "message": "You have not the right permissions"
}
```

This is an HTTP error, but it is not being seen as one by superforms. I suspect Superforms to be looking for `"type":"error"` inside the response message, but **I would expect to have Superforms also pay attention to the HTTP statuscode**, especially in scenario's where you cannot use `fail` (because that's not working in a server hook).

## Example
See my Stackblitz example: https://stackblitz.com/edit/sveltekit-superforms-1-testing-w6lmdl?file=src%2Froutes%2F%2Bpage.svelte

In the `+page.server.ts` is an arbitrary 403 triggered (in my case totally outside of the action scope, so I cannot use `fail`).

To reproduce my issue:
* Just hit the "Submit" button.
* If you open the browser inspector, you can see the 403 is coming back to the browser when submitting the form. SuperDebug also shows a 403 coming back.
* But, the `onError` in the superForm in `+page.svelte` is not being triggered.

How would I know that I am dealing with an error now?

**Comment by ciscoheat** [comment]
Hi, I'm not sure I understand, the message in `onError` appears for me when I click submit in the example:

<img width="482" alt="2023-11-30 20_01_01-Superforms playground (forked) - StackBlitz" src="https://github.com/ciscoheat/sveltekit-superforms/assets/130450/df8cc1d4-044e-4b6e-a7e2-5685e17b991b">

**Comment by rogiervandenberg** [comment]
Thanks for your reply @ciscoheat You are right and I was indeed not very clear in my example and tried to simplify my issue, but undid my actual case by that 🙈  Sorry.. 😬  But now the full example, set up with the server hook:
https://stackblitz.com/edit/sveltekit-superforms-1-testing-w6lmdl?file=src%2Fhooks.server.ts

Again:

* Open the browser inspector
* Hit the "Submit" button.
* A POST is done by Superforms, but the `hooks.server.ts` intercepts it and throws a 403.
* The 403 is shown in te inspector, but the `onError` console.log('We have an error (the 403)'.. is not executed. 🤷

**Comment by ciscoheat** [comment]
In the next version, soon to be released, this will be handled properly as an `error` actionResult. So no need to return `actionResult` there anymore. Unfortunately the status message isn't propagated, so the status code will always be 500.
