### ISSUE TITLE
zod `.transform` doesn't update the `$form` data.

### ISSUE THREAD

**Issue by macmillen** [ciscoheat/sveltekit-superforms#298]
**Description**
When using zods `.transform` the `$form` data doesn't get updated. (See link below)

**If applicable, a MRE**
https://www.sveltelab.dev/byiw2jsdeofnijv?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment]
This has always been a bit problematic since it's bad UX to modify the fields as they are updated by the user. But I'll bite the bullet, if everything seems to work with the test suite, I'll add this to the next release.

**Comment by macmillen** [comment]
Thank you @ciscoheat! Can you tell me why it's bad UX? Sometimes form values change based on others (for example when setting different options in a radio input, other input fields are shown (or hidden) based on these options)

**Comment by ciscoheat** [comment]
For radio buttons and checkboxes, it's ok, but changing text fields in the middle of user input can be quite annoying...! Also, if there are transformations like `trim`, it means that no space can be added to the end of a text field. So it can be a bit complicated to make it work for real-time validation.

**Comment by macmillen** [comment]
Ok got it, that makes sense, thanks. I'm using it only for Radio buttons anyway.

**Comment by ciscoheat** [comment]
I may be able to discern between the type of input fields, so there's a chance it will both for immediate updates (radio, checkbox, select) and text fields.

**Comment by unlocomqx** [comment]
Hi,

When an empty array `[]` is passed and I want to transform it into an empty object `{}`, the transform callback is not executed.

The empty array is coming from the json stringified response of the backend, I just hardcoded in this example to show the issue.

I'm doing something wrong?

repro
https://www.sveltelab.dev/ee16fh7502saisp

Thank you
