### ISSUE TITLE
upgrading to sveltekit 2 problem

### ISSUE THREAD

**Issue by delay** [ciscoheat/sveltekit-superforms#299]
sveltekit 2 was just released. I am getting an error.  Could you update your peer dependency to support sveltekit 2?

`npm ERR! Could not resolve dependency:
npm ERR! peer @sveltejs/kit@"1.x" from sveltekit-superforms@1.11.0`

**Comment by ciscoheat** [comment]
Will be updated in the next release in a few hours.
