### ISSUE TITLE
Error: Unsupported type for strict values on field "x": ZodEnum.

### ISSUE THREAD

**Issue by hmiiro** [ciscoheat/sveltekit-superforms#3]
Error: Unsupported type for strict values on field "interestMethod": ZodEnum. Add default, optional or nullable to the schema, or use the "defaults" option.

i have zod Enums, but the validation fails with above error.

the validation also fails for ZodUnion. for Unsupported type for strict values on field "createdAt": ZodUnion.

I am doing something wrongly?

**Comment by ciscoheat** [comment]
I will make a note about this in the documentation (it needs a bit of work!), thank you for reporting!
