### ISSUE TITLE
use z.input<> instead of z.infer<> to infer field types

### ISSUE THREAD

**Issue by demetrius-mp** [ciscoheat/sveltekit-superforms#30]
i have the following schema:
```ts
const schema = z.object({
  tags: z
    .string()
    .nullish()
    .transform((v, ctx) => {
      const commaDelimitedListRegex = /(\d+)(,\s*\d+)*/;

      if (!v) return;

      if (!commaDelimitedListRegex.test(v)) {
        ctx.addIssue({
          code: 'custom',
          message: 'Tags must be separated by comma'
        });
      }

      return v.split(',');
    }),
});
```

when doing

```ts
const { form } = superForm(data.form);
```

on the client, `form.tags` is inferred as `string[]`, which is the "output", instead of `string`, which is the input

this is bad because when doing 

```svelte
<input type="text" bind:value={$form.tags} />
```

typescript complains that it cant bind string to string[]

a way to get this working would be to do the transformation on the post request (similar to #11).

**Comment by ciscoheat** [comment]
Of course, using input and output makes perfect sense! Thank you for this, version 0.6.0 is going to be quite an improvement. :)

**Comment by ciscoheat** [comment]
It's a bit more complicated than I thought. The thing is that `z.output<T>` is also what is sent to the client, as the `form.data` contains the transformed data. Which makes sense when you want to display the data, to have the correct types.

So if the input is `string` and output is `string[]` for a field in the schema, the client will receive `string[]` and can't really know that it's supposed to send a `string` back, and even if it knew, how should it be transformed? That would mean that an inverse of the (server-side) transformation function needs to be applied client-side when posting, or provide an `input` and `output` property on the validation data, but that complicates things for sure.

I cannot figure out a way that handles this and still keeps things simple. Maybe you have some ideas? 

Your use case seems simple enough however to just transform the data to tags after validation, thereby avoiding changing the type of the schema. Do the same checks in `transform`, but return the same string. Then do something like:

```ts
const form = await superValidate(data, schema)
if (!form.valid) return fail(400, { form });

const validData = { ...form.data, tags: form.data.tags.split(',') }
```

But the easiest way, if you are ok with javascript being a requirement, is probably to use `z.string().array()` in the schema, set `dataType = 'json'` and leave the string transformations behind. Then you need to do nothing but this:

```svelte
  <input
    name="tags"
    value={$form.tags.join(',')}
    on:input={(e) => ($form.tags = e.currentTarget.value.split(','))}
  />
```

**Comment by demetrius-mp** [comment]
> It's a bit more complicated than I thought. The thing is that `z.output<T>` is also what is sent to the client, as the `form.data` contains the transformed data. Which makes sense when you want to display the data, to have the correct types.

yeah, i wasnt sure if the data that is sent to the client had shape `z.output` or `z.input`, but since it is `z.output`, theres not much to do

im going to end up just transforming the data after validation, and using `setError` if my transformation fails.

what do you think of adding a section to the readme, regarding transformed/refined/superrefined schemas?

again, thank you so much for responding very quickly, and thanks for the lib

**Comment by ciscoheat** [comment]
I think it's not much more to do, since the data you get from a DB would also be in the `z.output` shape. I'll add a section about this for sure. Glad you like it, anyway. :)
