### ISSUE TITLE
structuredClone not working in Svelte 5

### ISSUE THREAD

**Issue by ciscoheat** [ciscoheat/sveltekit-superforms#300]
- [x] Before posting an issue, read the FAQ at https://superforms.rocks/faq and search the previous issues.

**Description**
With Svelte 5, Superforms crashes due to `structuredClone` not being able to handle `Proxy`.

A possible fix is to use a different way of cloning, like [klona](https://github.com/lukeed/klona).

**Comment by ciscoheat** [comment]
Related to get things working with Svelte 5: https://github.com/sveltejs/svelte/issues/9947

**Comment by divmgl** [comment]
Made a quick fork that uses `klona`. https://github.com/divmgl/sveltekit-superforms

```json
// package.json
{
  "dependencies": {
    "sveltekit-superforms": "github:divmgl/sveltekit-superforms#ea546c3",
  }
}
```

**Comment by ciscoheat** [comment]
That works, but also need the bind:group fix to get things working on Svelte 5. Go to https://github.com/sveltejs/svelte/issues/9947 and give some cheer. :)

**Comment by ciscoheat** [comment]
It seems like klona doesn't handle Proxy objects well, so it will probably be [just-clone](https://www.npmjs.com/package/just-clone) in the end. It will also be a v2 feature, since it is quite close to release.

**Comment by ciscoheat** [comment]
2.0.0-alpha.37 is using just-clone now and it seems to work well in both Svelte 4 and 5.
