### ISSUE TITLE
How to populate a form in SPA with dynamic data

### ISSUE THREAD

**Issue by gschurck** [ciscoheat/sveltekit-superforms#305]
I use SvelteKit and Superforms in SPA mode, and I want to populate a form in a modal that is called on the same page, and I want the form to be populated with data depending on what I click on. How can I load this data dynamically ? I see that we have to use the `+page.ts` file to get the initial data when loading page, but in my case I want to change the populated superforms data dynamically on client-side. How could I do it in a clean way ?
Thanks.

**Comment by ciscoheat** [comment]
You can assign to `$form` directly ([example](https://superforms.rocks/concepts/tainted#tainted-store)), or use the `reset` method.

**Comment by gschurck** [comment]
Oh I didn't know that, thank you.
