### ISSUE TITLE
SvelteDebug props Svelete5

### ISSUE THREAD

**Issue by GimpMaster** [ciscoheat/sveltekit-superforms#306]
**Description**
I just tried this great project out in my Svelte5 sample app. I realize Svelte5 isn't out yet but I'm getting this error

SuperDebug.svelte:18:2 Cannot use `export let` in runes mode — use $props instead

I looked and noticed you have a Svelte5-Comp branch but I didn't see any changes to address this. Is there a work around for this?

Thanks

**Comment by ciscoheat** [comment]
Hello, there's another issue #300 about svelte 5, that I don't know when it's going to be fixed, so I cannot say anything about svelte 5 compatibility yet.

**Comment by GimpMaster** [comment]
Interesting. I was able to get working what I needed. Just that SuperDebug doesn’t work. Perhaps I’m not using Proxy or something. 

Either way I’m excited to use superforms going forward. I can tell you put a lot of thought into it. I built something very similar for react and was glad to see I could just use this instead of porting my form manager over.

**Comment by ciscoheat** [comment]
Glad to hear you like it. :) I haven't dived deep into Svelte 5 yet, but maybe setting runes mode to false for SuperDebug will help: https://svelte-5-preview.vercel.app/docs/runes#how-to-opt-in

**Comment by GimpMaster** [comment]
I could be wrong but it seems like you would have to place this inside SvelteDebug


<svelte:options runes={true} />

or I make a wrapper component. Still very new to svelte

**Comment by GimpMaster** [comment]
I will so I found a work around. The issues comes because I have the force runes mode in my svelte.config.ts. 

Unfortunately this forces all node_modules to also be in runes mode. However you can pass a function to the config and exclude certain files or folders. 

When I get to my computer I’ll post the code

**Comment by ciscoheat** [comment]
Great, will add this as a note in a future Svelte 5 upgrade page. Thanks for trying it out!

**Comment by ciscoheat** [comment]
Will leave it here, as it probably will be fixed soon (if not already).

**Comment by Tyson910** [comment]
Is anyone else still having this issue? Current versions below

```
# devDependencies:
@sveltejs/kit 2.9.0
@sveltejs/vite-plugin-svelte 4.0.2
svelte 5.10.0
sveltekit-superforms 2.21.1
````
