### ISSUE TITLE
support union types in `SuperForm` for similar schemas

### ISSUE THREAD

**Issue by macmillen** [ciscoheat/sveltekit-superforms#309]
[DEMO](https://www.sveltelab.dev/cadxx2z3vv3nc8c)

Sometimes I have a form on two different pages (e.g. `create-order` and `update-order` page) and obviously these two pages share almost the same schema. 

``` ts
export const createOrderSchema = z.object({
	name: z.string()
});
export const updateOrderSchema = z.object({
        id: z.string(),
	name: z.string()
});
```

Now I want to keep my code DRY so that I don't need to have two different forms that look the same except one has additionally an `id` field.

That's why I want to create one `Form` component that accepts a `superForm` object as a prop. To do that my idea was to create a union type of both schemas. However if I want to pass it down to my `TextInput` component I get an error

``` ts
export let superForm: SuperForm<typeof createUserSchema> | SuperForm<typeof updateUserSchema>;

...

<TextInput {superForm} field="name" />
```

```
Type 'SuperForm<ZodObject<{ email: ZodString; pw: ZodString; }, "strip", ZodTypeAny, { email: string; pw: string; }, { email: string; pw: string; }>> | SuperForm<...>' is not assignable to type 'SuperForm<ZodValidation<ZodObject<{ email: ZodString; pw: ZodString; }, "strip", ZodTypeAny, { email: string; pw: string; }, { email: string; pw: string; }>>, unknown>'.
  Type 'SuperForm<ZodObject<{ email: ZodString; pw: ZodString; id: ZodString; }, "strip", ZodTypeAny, { email: string; pw: string; id: string; }, { email: string; pw: string; id: string; }>>' is not assignable to type 'SuperForm<ZodValidation<ZodObject<{ email: ZodString; pw: ZodString; }, "strip", ZodTypeAny, { email: string; pw: string; }, { email: string; pw: string; }>>, unknown>'.
    Types of property 'restore' are incompatible.
      Type '(snapshot: SuperFormSnapshot<ZodObject<{ email: ZodString; pw: ZodString; id: ZodString; }, "strip", ZodTypeAny, { email: string; pw: string; id: string; }, { email: string; pw: string; id: string; }>, any>) => void' is not assignable to type '(snapshot: SuperFormSnapshot<ZodObject<{ email: ZodString; pw: ZodString; }, "strip", ZodTypeAny, { email: string; pw: string; }, { email: string; pw: string; }>, unknown>) => void'.
        Types of parameters 'snapshot' and 'snapshot' are incompatible.
          Type 'SuperFormSnapshot<ZodObject<{ email: ZodString; pw: ZodString; }, "strip", ZodTypeAny, { email: string; pw: string; }, { email: string; pw: string; }>, unknown>' is not assignable to type 'SuperFormSnapshot<ZodObject<{ email: ZodString; pw: ZodString; id: ZodString; }, "strip", ZodTypeAny, { email: string; pw: string; id: string; }, { email: string; pw: string; id: string; }>, any>'.
            Types of property 'data' are incompatible.
              Property 'id' is missing in type '{ email: string; pw: string; }' but required in type '{ email: string; pw: string; id: string; }'.
ts
```

**Describe the solution you'd like**
I need to have a way to create superForms unions

**Describe alternatives you've considered**
-

**Comment by ciscoheat** [comment]
Can the [CRUD tutorial](https://superforms.rocks/crud/) be of any help?

**Comment by macmillen** [comment]
Not really because we actually want to have a union type (and not optional fields like with `id: userSchema.shape.id.optional()`)

The use case we have is that we have a component which can be used in multiple forms as only a part of the schema

```
const eventSchema = z.object({
  id: z.string().optional(),
  published: z.boolean(),
});
```

```
const tagSchema = z.object({
  id: z.string().optional(),
  name: z.string(),
});
```



```
export let superForm: SuperForm<typeof createUserSchema>;
```

 that accepts a SuperForm with two different schema types and then we want to do some type narrowing to check which fields can be passed down to our TextInput based on the [componentization](https://superforms.rocks/components)

**Comment by macmillen** [comment]
Unfortunately, not really. The use case we have is that we have a component (e.g. `PublishedComponent`) which can be used in multiple forms as only a part of the schema.

``` ts
  const publishedSchema = z.object({
    published: z.boolean(),
  });
  const tagSchema = z.object({
    id: z.string(),
    name: z.string(),
  });
  const eventSchema = publishedSchema.extend({
    id: z.string(),
    tags: z.array(tagSchema),
  });
```

``` svelte
<script lang="ts">
  // PublishedComponent
  export let superForm: SuperForm<typeof publishedSchema>;
</script>
```

**Comment by ciscoheat** [comment]
I'll see what can be done for version 2.

**Comment by ciscoheat** [comment]
This one is ready for testing, migration guide at: https://superforms.rocks/migration-v2/

**Comment by ciscoheat** [comment]
@macmillen Did you have time to test this yet?

**Comment by macmillen** [comment]
@ciscoheat Thank you so much for implementing this feature!

I just tested it and it seems partially working but I still get two errors.

You can test it out here:
https://www.sveltelab.dev/cadxx2z3vv3nc8c

First I get an error because `The types of 'options.onUpdate' are incompatible between these types.` But only for one route (it works for `/create` but not for `/update` because update has the `id` field as well).

![Screenshot_20240130_161126](https://github.com/ciscoheat/sveltekit-superforms/assets/33156526/18a4afbb-bb12-4257-88f6-be8f17cbc044)

```
Type 'SuperForm<{ id: string; email: string; pw: string; }, any>' is not assignable to type 'SuperForm<{ email: string; pw: string; } | { id: string; email: string; pw: string; }, any>'.
  The types of 'options.onUpdate' are incompatible between these types.
    Type '((event: { form: SuperValidated<{ id: string; email: string; pw: string; }, any>; formEl: HTMLFormElement; cancel: () => void; }) => unknown) | undefined' is not assignable to type '((event: { form: SuperValidated<{ email: string; pw: string; } | { id: string; email: string; pw: string; }, any>; formEl: HTMLFormElement; cancel: () => void; }) => unknown) | undefined'.
      Type '(event: { form: SuperValidated<{ id: string; email: string; pw: string; }, any>; formEl: HTMLFormElement; cancel: () => void; }) => unknown' is not assignable to type '(event: { form: SuperValidated<{ email: string; pw: string; } | { id: string; email: string; pw: string; }, any>; formEl: HTMLFormElement; cancel: () => void; }) => unknown'.ts(2322)
```

And the second thing I can't get to work is the generic TextInput component. The `field` type is always `never`.

![Screenshot_20240130_154504](https://github.com/ciscoheat/sveltekit-superforms/assets/33156526/92507ae8-b274-406c-8da0-bbba12e68126)

**Comment by ciscoheat** [comment]
Thank you, will test this locally and see what can be done.

**Comment by ciscoheat** [comment]
There's an incorrect prop name, it should be `superForm`, not `form`.

**Comment by macmillen** [comment]
Ah right, that solves one of the errors. Thank you :+1:

**Comment by ciscoheat** [comment]
The other is unfortunately quite a bit more complicated, but I hope it can be fixed.

**Comment by ciscoheat** [comment]
Check if it works now with alpha.40!

**Comment by macmillen** [comment]
Amazing, it works!!! :rocket: 
Thank you @ciscoheat
