### ISSUE TITLE
FormFieldProxy not working in Svelete 5

### ISSUE THREAD

**Issue by GimpMaster** [ciscoheat/sveltekit-superforms#314]
I was trying to follow the componentization documentation using Svelte 5. 

Docs here:  https://superforms.rocks/components

But I was getting these typescript errors.

![image](https://github.com/ciscoheat/sveltekit-superforms/assets/7818200/d1f72bd0-77cb-4c10-b6e5-2acf228a224e)

As well as Sveltekit crashing with this error.

![image](https://github.com/ciscoheat/sveltekit-superforms/assets/7818200/df1744fc-ddc5-43e3-b868-926d3f3360eb)

Any one get FormFieldProxy working in Svelte5 yet?

**Comment by ciscoheat** [comment]
Just tested, and it works fine in the latest v2 version (2.0.0-alpha.37). Can you try again with that?

**Comment by ciscoheat** [comment]
It's working fine on this repo, so I'm closing this as it seems to work. https://stackblitz.com/edit/superforms-2-testing-5jhp1p?file=package.json,src%2Froutes%2F%2Bpage.svelte%3AL10
