### ISSUE TITLE
superValidateSync and v2

### ISSUE THREAD

**Issue by Hebilicious** [ciscoheat/sveltekit-superforms#316]
Hi @ciscoheat, thanks for creating this awesome library.

According to the v2 migration guide, it's no longer possible to validate data using superValidateSync. 

https://superforms.rocks/migration-v2/#supervalidatesync-is-renamed-to-defaults

Could you expand on why you're making this change? 

If I understand correctly, you are removing a feature that was working (validating in components) without introducing an alternatives. 

There's many SPA out there that don't need/want to use load functions. In our use case (graphQL), we are sending request directly to our endpoint... 

In your GitHub search you can see a lot of people are relying on this behaviour, and there's many more non open-source projects as well.

I would like to upgrade to v2, and maybe I'm missing something. How would you recommend we deal with components deep down the tree that are posting data to our API ? Creating a load function for the parent route that can handle multiple forms feels wrong. The validation logic should be colocated with the components that are submitting the forms.

**Comment by ciscoheat** [comment]
Hi, it's because not all validation libraries use synchronous validation, so they cannot be used on the top-level of a svelte component. But it works anywhere else, so you can use superValidate anywhere down the tree.

**Comment by Hebilicious** [comment]
> Hi, it's because not all validation libraries use synchronous validation, so they cannot be used on the top-level of a svelte component. But it works anywhere else, so you can use superValidate anywhere down the tree.

Thanks for explaining. Could you add `superValidateSync` but only for the validation libraries that supports it then ?

**Comment by ciscoheat** [comment]
I'm hesitant to have both. It's more work to manage async and sync codebases (it was bad enough in v1), but also because validation on the client is more of a convenience than something reliable. All input sent to `superValidate(Sync)` on the client can be tampered with anyway, so knowing if the initial data is valid or not is not really possible. 

If you really need initial errors, you can make a `validate({ update: true })` call as early as possible.

**Comment by Hebilicious** [comment]
> I'm hesitant to have both. It's more work to manage async and sync codebases (it was bad enough in v1), but also because validation on the client is more of a convenience than something reliable. All input sent to `superValidate(Sync)` on the client can be tampered with anyway, so knowing if the initial data is valid or not is not really possible.
> 
> If you really need initial errors, you can make a `validate({ update: true })` call as early as possible.

Yes, data needs to be validated on the server.

In our case we are using a graphql API, and our validation happens at the schema level and in the resolver for more advanced use cases, hence why we do not use load functions. 

We're still using client validation because of the instant feedback it can provide on form fields. 
Actually I think I'm confused by what `superValidateSync` did in the first place...
I was under the impression that this was the only way to validate a form that does *not* have a load function. 

Is this use-case still supported with v2 ?

**Comment by ciscoheat** [comment]
If you're using a graphql API, shouldn't you be able to validate with `superValidate`, when you receive the data? Or is it also called in top-level?

**Comment by Hebilicious** [comment]
> If you're using a graphql API, shouldn't you be able to validate with `superValidate`, when you receive the data? Or is it also called in top-level?

Our API is not part of the svelte-kit app and therefore doesn't need to know about superform.
What we use superform for is client side validation, and zod schemas are great at that.
Imo they are not great when you get into refine territory, need to do asynchronous logic that may need permissions or have side effects.

Anyways, my point is that this use-case got removed and we have to stay on v1. Is that correct?

**Comment by ciscoheat** [comment]
I don't understand, you want to make an initial validation of graphql data? To display initial errors, or because you're not sure about the data integrity? Again, if you don't need initial errors and the graphql data is trustworthy, you can use `defaults` as a replacement.

**Comment by Hebilicious** [comment]
> I don't understand, you want to make an initial validation of graphql data? To display initial errors, or because you're not sure about the data integrity? Again, if you don't need initial errors and the graphql data is trustworthy, you can use `defaults` as a replacement.

What I want is when I click the submit button, the form should be validated client side according to the zod schema without going to the server at all.

**Comment by ciscoheat** [comment]
`superValidate(Sync)` and `defaults` has nothing to do with client-side validation. They are returning the data required for instantiating a `superForm` object. Of course, client-side validation will work just as before: https://superforms.rocks/concepts/client-validation

If you need initial validated data, you'll need a `+page.ts` file, or a `validate({ update: true })` call as early as possible. I hope that is clear now.

**Comment by Hebilicious** [comment]
> `superValidate(Sync)` and `defaults` has nothing to do with client-side validation. They are returning the data required for instantiating a `superForm` object. Of course, client-side validation will work just as before: https://superforms.rocks/concepts/client-validation
> 
> If you need initial validated data, you'll need a `+page.ts` file, or a `validate({ update: true })` call as early as possible. I hope that is clear now.

Understood, apologies for the mis-understanding. I would say that it is clear now, and that we can replace all `superValidateSync(zod(schema))` with `defaults(zod(schema))`, and manually call `validate()` after we populate the forms form after a mutation result.

Maybe this is worth a documentation page as this would apply generally for graphql users? Happy to contribute that.

**Comment by ciscoheat** [comment]
That would be nice, the web repository [is here](https://github.com/ciscoheat/superforms-web). And of course, if your company is using it in a commercial product, [donating](https://superforms.rocks/contributing#donations) is much appreciated. It has taken plenty of time to get this far.

**Comment by Hebilicious** [comment]
> That would be nice, the web repository [is here](https://github.com/ciscoheat/superforms-web). And of course, if your company is using it in a commercial product, [donating](https://superforms.rocks/contributing#donations) is much appreciated. It has taken plenty of time to get this far.

Will definitely look into contributing a page after we migrate to v2 and are happy with the setup.
I contribute regularly to open-source projects and maintain a few, so this is important for me personally. I'll try to get a sponsorship initiative going for all oss libraries that we are using once we have users, but right now the product is not even out 😅 

Thanks for your time!
