### ISSUE TITLE
Ability to remove "File" upon form return in V2

### ISSUE THREAD

**Issue by saturnonearth** [ciscoheat/sveltekit-superforms#317]
After calling "removeFiles" and returning the form data, the file data remains, even if I try to set it to "undefined" on the backend. The reason I want to do this is, if I re-submit the form, my code still thinks an image is attempting to be uploaded.

**Comment by ciscoheat** [comment]
Yes, they should be removed when `resetForm` is true (default in v2). Will fix that.

**Comment by ciscoheat** [comment]
Check if it works now with alpha 29.

**Comment by saturnonearth** [comment]
> Check if it works now with alpha 29.

It works now :)

If I can ask, if I have `restForm` set to `false`, and I return a validated form object from the backend which includes the property associated with the File set to `undefined`, why does it seemingly ignore it?

For example...

```ts
form.data.avatarFile = undefined; // <-- Does not work
form.data.name = 'test'; //  <-- Works

return {
    ...removeFiles({ form }),
}

**Comment by ciscoheat** [comment]
Maybe the check should be for key existence instead of just undefined. I'll have to check if that works.

**Comment by ciscoheat** [comment]
Amazingly, it worked straight away. See if alpha.31 works with your example now.

**Comment by saturnonearth** [comment]
> Amazingly, it worked straight away. See if alpha.31 works with your example now.

Works!
