### ISSUE TITLE
Snapshot not working

### ISSUE THREAD

**Issue by galaczi** [ciscoheat/sveltekit-superforms#320]
**Description**
Snapshots don't seem to work. 

```
const { form, errors, enhance, capture, restore } = superForm(data.form);
export const snapshot = { capture, restore };
```

All other features of Superforms works so the setup is correct. Tainted message on navigation should be disabled according to the docs. It is not, and snapshot is not taken.

Node v20.10.0
@sveltejs/kit@2.5.0
sveltekit-superforms@1.13.4

**Comment by galaczi** [comment]
Ah ok, I misunderstood the docs. 

After disabling though snapshots still don't work for me. Can't think of anything other than I have ``beforeNavigate`` and ``afterNavigate`` set up in my layout for smooth scrolling. Can those interfere with snapshots?

**Comment by ciscoheat** [comment]
It's hard to tell, I recommend creating a MRE here, then I can take a closer look if you are able to reproduce it: https://stackblitz.com/edit/sveltekit-superforms-1-testing?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte

(I hope it's possible to do with Stackblitz)

**Comment by galaczi** [comment]
I couldn't reproduce it. Closing for now.
