### ISSUE TITLE
isTainted is always false in ^2.0.0-alpha.45

### ISSUE THREAD

**Issue by mpost** [ciscoheat/sveltekit-superforms#324]
**Description**
Using the latest alpha `^2.0.0-alpha.45`, the `isTainted()` callback always returns `false`. This is the case even when the `$tainted` store contains entries.

**Comment by ciscoheat** [comment]
Are those entries set to `undefined`, or `true`? If they are undefined, isTainted will return false.

**Comment by mpost** [comment]
Ah, sorry you are right. I missread the intended behavior.

I am trying to do ```<button disabled={isTainted()}>Save</button>``` which would not be retriggered when `isTainted()` would return a different value. Is there any recommended way to achieve such an effect? Aka. only allow save on tainted.

**Comment by mpost** [comment]
What i came up with is:

```
$: formDirty = false
$: $tainted, (formDirty = isTainted())
```
  
and in the button:

```
<button disabled={!formDirty}>Save</button>
```

But that looks verbose. Any better practices?

**Comment by ciscoheat** [comment]
I was thinking of that as well before. Having yet another store just for that purpose is also a bit verbose. But it seems like `isTainted($tainted)` could work! Will test that for the next alpha version and get back.

**Comment by ciscoheat** [comment]
Yes, this should work: https://svelte.dev/repl/851ed57bb079474c8291428db80ed0ac?version=4.2.10
Will add that as a parameter to the next version.

**Comment by mpost** [comment]
Nice. Looking forward to that. :)

**Comment by mpost** [comment]
One more note on the tainted calculation:

When having a zod schema with an optional value (`name: z.string().optional()`), it has the expected default value of `undefined`. However, when editing the field and than clearing the field back to having no content, the `name` value becomes `""` (zero length) string. This does not reset the "tainted" state correctly when using the above mentioned approach of

```
$: formDirty = false
$: $tainted, (formDirty = isTainted())
```

This is in contrast to a zod field without the `optional()` settings which is the empty string per default and also returns to the empty string when the inputs field content is erased.

**Comment by ciscoheat** [comment]
As the user inputs an empty string, that's what will be set as default, but Superforms got you covered: You can use a stringProxy in that case: https://superforms.rocks/api#stringproxyform-fieldname-options

**Comment by mpost** [comment]
That sounds like a respectable solution. It feels a bit artificial though. Declaring a field specific behavior outside of the schema, is not something i would shoot for. Another "solution" would be to declare the schema field as options and to give it a default of an empty string: `z.string().optional().default('')`. This would of course imply knowledge about the special requirements of the schema.

**Comment by ciscoheat** [comment]
It's hard to have the best of both worlds. If there's an empty string as default, the field cannot be undefined through user input. So if you want an empty field to mean undefined in the schema, you need a stringProxy.

**Comment by ciscoheat** [comment]
`isTainted($tainted)` should work now with alpha.47, can you confirm that it does?
