### ISSUE TITLE
Convert example to superforms 2.0

### ISSUE THREAD

**Issue by mpost** [ciscoheat/sveltekit-superforms#325]
I am trying to migrate the following example to work in 2.0. So far with limited success. Could we convert this to be included in the migration guide? :)

https://superforms.rocks/faq#i-want-to-reuse-common-options-how-to-do-that-easily

**Comment by ciscoheat** [comment]
I'm about to update the whole website, now that the v2 release is close. See if this works in the meantime:

```ts
import { superForm as realSuperForm } from 'sveltekit-superforms';

export type Message = {
  status: 'success' | 'error' | 'warning';
  text: string;
};

export function superForm<T extends Record<string, unknown>>(
  ...params: Parameters<typeof realSuperForm<T, Message>>
) {
  return realSuperForm<T, Message>(params[0], {
    // Your defaults here
    errorSelector: '.has-error',
    delayMs: 300,
    ...params[1]
  });
}
```

**Comment by mpost** [comment]
Thanks for your swift feedback. It is nice seeing how the snippets get simpler when evolving the library. For my use-case i was able to simplify it even more to:

```ts
import { superForm } from 'sveltekit-superforms'

export function megaForm<T extends Record<string, unknown>>(
  ...params: Parameters<typeof superForm<T>>
) {
  return superForm<T>(params[0], {
    // my params here
    ...params[1],
  })
}
```
