### ISSUE TITLE
Using zods z.string().trim() transform in 2.0 prohibits whitespace insertion

### ISSUE THREAD

**Issue by mpost** [ciscoheat/sveltekit-superforms#326]
When validating against a schema like

```
name: z.string().trim()
```

the validation also transforms the string with the `trim()` function. Thereby all the white-spaces are removed, prohibiting the insertion of spaces. The superform `validationMethod` is on the default `auto`.

However, removing the white-spaces in transit is desirable. Is there a best practice for such behavior or do we need to trim manually?

**Comment by ciscoheat** [comment]
With `auto` and `oninput` on the client, this is how it works, unfortunately. But you can use an extended schema in the form action that does all the trimming, perhaps.

**Comment by mpost** [comment]
What would an "extended schema look like"?

A possible solution is to use the `onSubmit` callback forwarded from sveltes `use:enhance`. Here we can modify the `formData` before it is send to the backend. Eg.

```
const superForm = superForm<T>(data.form, {
    onSubmit({ formData }) {
      formData.forEach((value, key) => {
        if (typeof value === 'string') {
          formData.set(key, value.trim())
        }
      })
    },
  })
```

**Comment by ciscoheat** [comment]
You can extend a schema like this:

```ts
const schema2 = z.object({
  name: z.string(),
  email: z.string()
})

const trimSchema = schema2.extend({
  name: schema2.shape.name.trim(),
  email: schema2.shape.email.trim()
})
```

And then use that schema in the form action. A helper function would make this even simpler.

**Comment by mpost** [comment]
At what place would you apply the extended schema?

**Comment by ciscoheat** [comment]
In the form action, when you call superValidate.

**Comment by ciscoheat** [comment]
I found a better way to handle this, so in the next alpha, data will only be trimmed on blur for text input fields. It should be the best for UX, and if the need arises in the future, an option could be added for transforming even on input.

**Comment by mpost** [comment]
Great. looking forward to that. Btw, the superforms project is doing a great job. Keep it up. 👍

**Comment by ciscoheat** [comment]
Check how it works now with alpha.47!

**Comment by mpost** [comment]
Nice. For the `trim()` it works as expected. 👍
