### ISSUE TITLE
rfc v2 DX

### ISSUE THREAD

**Issue by zhihengGet** [ciscoheat/sveltekit-superforms#327]
hi
```
const { form, errors, enhance } = superForm(defaults(zod(schema)), {
  SPA: true,
  validators: zod(schema),
  // ...
})
```
here, we need to define zod(schmea) 2 times, i think the DX isnt too good, i propose.
```
superForm({data?: superValided(DATA)，schema: schema, wrapFn?:defaults, adapterFn: zod }    // if spa is true,then we should default to use defaults
```
just an idea, lmk what u think... and obviously, we can  do `const s=zod(schema),` but we still need to apply this to both places

**Comment by ciscoheat** [comment]
If you have a `+page.ts`, you will supply the data with `data.form` even in SPA mode. It's a minor thing, so I'd like to keep it simple for now with the current API.
