### ISSUE TITLE
Zod enums create optional schema values

### ISSUE THREAD

**Issue by shellicar** [ciscoheat/sveltekit-superforms#333]
**Description**
Using nativeEnum or enum in 2.0 with strict = true produces a schema with optional values.

**Version**
2.0.0

**Reproducible**

`tsconfig.json`
```json
{
  "compilerOptions": {
    "strict": true
  },
  "extends": ["./.svelte-kit/tsconfig.json"]
}
```

Produces optional value (value?: Type | undefined)
```ts
import { defaults } from 'sveltekit-superforms';
import { zod } from 'sveltekit-superforms/adapters';
import { z } from 'zod';

enum MyEnum {
  ValueA = 'ValueA',
  ValueB = 'ValueB',
}

const mySchema = z.object({
  value: z.nativeEnum(MyEnum).default(MyEnum.ValueA),
});
type MyType = z.infer<typeof mySchema>;
// type MyType = {
//   value: MyEnum;
// }

const myFunction = (_type: MyType) => {
  // no-op
};

myFunction(mySchema.parse({}));

const values = defaults(zod(mySchema));
// values.data: {
//   value?: MyEnum | undefined;
// }
myFunction(values.data);
//         ^ Argument of type '{ value?: MyEnum | undefined; }' is not assignable to parameter of type '{ value: MyEnum; }'.
//           Types of property 'value' are incompatible.
//           Type 'MyEnum | undefined' is not assignable to type 'MyEnum'.
//           Type 'undefined' is not assignable to type 'MyEnum'.
```

Previously working code (repro)
```ts
import { superValidateSync } from 'sveltekit-superforms/client';
import { z } from 'zod';

enum MyEnum {
  ValueA = 'ValueA',
  ValueB = 'ValueB',
}

const mySchema = z.object({
  value: z.nativeEnum(MyEnum).default(MyEnum.ValueA),
});
type MyType = z.infer<typeof mySchema>;
// type MyType = {
//   value: MyEnum;
// }

const myFunction = (_type: MyType) => {
  // no-op
};

myFunction(mySchema.parse({}));

const values = superValidateSync(mySchema);
// values.data: {
//   value: MyEnum;
// }
myFunction(values.data);
```

> Note: Wasn't able to create a reproducible in stackblitz due to no parsing of .svelte files being configured

**Comment by Nelhoa** [comment]
Maybe same as #335

**Comment by ciscoheat** [comment]
Yes, this is a problem, but hard to solve. For the type to be correct, if an enum field is not optional or required, it must have a default value in the schema. But an existing default value creates an optional type, as that is the standard is most "toJSONSchema" libraries.

Previously, I was considering using the first enum value as the default, but that may not always be the intent. But I also understand that enums must be able to be required somehow. It's not a breaking change, so it can be a solution.

**Comment by ciscoheat** [comment]
It's not related to Superforms or Zod, but a type problem that doesn't map to form input. The inferred schema type is `{ gender: Gender }`, not `Gender | undefined`, so it must always have one of the gender values. 

And then in the form, with `bind:value`, it will use the default value. Defining a `Default` won't work either if you want to require only the Male or Female values.

For the next release, the first enum value will be used (as in v1), so enums can be required again. And this may vary between libraries (their JSON Schema generators), but for Zod, if the default value doesn't match one of the enums, it will set the field to required, so it will work in this case!

```ts
const schema = z.object({
  letter: z.enum(['a', 'b', 'c']).default('' as any)
});
```

**Comment by shellicar** [comment]
> It's not related to Superforms or Zod, but a type problem that doesn't map to form input. The inferred schema type is `{ gender: Gender }`, not `Gender | undefined`, so it must always have one of the gender values.
> 
> And then in the form, with `bind:value`, it will use the default value. Defining a `Default` won't work either if you want to require only the Male or Female values.
> 
> For the next release, the first enum value will be used (as in v1), so enums can be required again. And this may vary between libraries (their JSON Schema generators), but for Zod, if the default value doesn't match one of the enums, it will set the field to required, so it will work in this case!
> 
> ```ts
> const schema = z.object({
>   letter: z.enum(['a', 'b', 'c']).default('' as 'a')
> });
> ```

Is it a bug that this doesn't work. I just tested it in 2.3.0 and I get the same issue using zod.
```ts
const schema = z.object({
  letter: z.enum(['a', 'b', 'c']).default('' as 'a'),
});
const adapter = zod(schema);
const parsed: SuperValidated<Infer<typeof schema>> = defaults(adapter);
//    ^ Type 'SuperValidated<{ letter?: "a" | "b" | "c" | undefined; }, any>' is not assignable to type 'SuperValidated<{ letter: "a" | "b" | "c"; }>'.
```
From my understanding it worked in v1.0, but this doesn't work in v2.0.

The other way works by modifying the adapter, but it's pretty annoying as then the validation isn't entirely in the schema.

**Comment by ciscoheat** [comment]
Use the other method instead: https://github.com/ciscoheat/sveltekit-superforms/issues/333#issuecomment-1938881450

**Comment by ciscoheat** [comment]
Until there's a way to modify the inferred type with an option, it's how it must be. There's no way to use default without making the field optional. That's how most validation libraries work
