### ISSUE TITLE
Add VineJS as validator

### ISSUE THREAD

**Issue by matfire** [ciscoheat/sveltekit-superforms#334]
**Is your feature request related to a problem? Please describe.**
Not really
**Describe the solution you'd like**
Add a new validator using [VineJS](https://vinejs.dev/docs/introduction)
**Describe alternatives you've considered**

**Additional context**
I'd be willing to work on this integration if it is greenlit

**Comment by matfire** [comment]
Ok, I'll give it a try

**Comment by ciscoheat** [comment]
Great, let me know if you have any questions.

**Comment by matfire** [comment]
thanks! I have the basis down and am working on validating the tests xD
https://github.com/matfire/sveltekit-superforms/tree/feature/vine-adapter

**Comment by ciscoheat** [comment]
You need to add `'simple'` as an option, since it uses the RequireDefaultsOption. Check how the Arktype test does it.

**Comment by matfire** [comment]
Got it! now 1 test passes :). I'll keep working on the others.
looks like I have an issue with the date field, though. Since Vine is made to parse http request bodies, it cannot handle Date objects ? Would it be okay to filter out that section of the test data ?

**Comment by ciscoheat** [comment]
You mean that Vine won't accept `Date` as input? That's a bit unfortunate, since you can also use `superValidate` for any input (as in loading data from a DB), not just http requests. But if you can make a distinction in the test suite that the dates are strings in certain cases, I guess it's ok. Please make an attempt. :)

**Comment by matfire** [comment]
I'd imagine something along the line of:
- inside the schemaTest function, the different input objects could be duplicated
- adding a `dateAsString` optional param to `schemaTest` (so as not to break all tests) defaulting to false
- if that param is true, modify the different inputs so the date is a simple string
- execute the tests normally

**Comment by ciscoheat** [comment]
Sounds very good!

**Comment by matfire** [comment]
done! still some tests not passing, but getting close (mostly the default value for "name" not being taken into account and the regex not working the way I wanted it to)

**Comment by ciscoheat** [comment]
One thing I see is that since the adapter is "simple" (requires default values), you should pass the default values to the `createAdapter` function (but not on the client adapter)

```ts
return createAdapter({
  superFormValidationLibrary: 'vine',
  validate: async (data: unknown) => validate(schema, data),
  jsonSchema: createJsonSchema(options),
  defaults: options.defaults
});
```

I'll make a guide for adapters when this is done...!

**Comment by matfire** [comment]
Awesome, that fixed a bunch of them :)
Only one test remaining, probably has to do with how I handle validation errors

**Comment by matfire** [comment]
Alright, all tests are valid. Just one more issue and it should ready for a pr.
It's a type issue. Looking at the other validators' examples, I typed my function as follows:

```js
function _vine<T extends SchemaTypes>(
	schema: T,
	options: RequiredDefaultsOptions<T>
): ValidationAdapter<Record<string, unknown>> 
```
with SchemaTypes coming from `vine`.
The error is: `Type 'T' does not satisfy the constraint 'Schema'.`

**Comment by ciscoheat** [comment]
You can fix that by adding Vine's valid schema types (for an object, including side-effects) to src\lib\adapters\typeSchema.ts

**Comment by ciscoheat** [comment]
Added now in 2.2.0!
