### ISSUE TITLE
Loading Timers Broken

### ISSUE THREAD

**Issue by je-movers-market** [ciscoheat/sveltekit-superforms#336]
**Description**
The loading timers don't seem to be working correctly. Using v2 with Zod at the moment, and both delayed and submitting are true when I load up the form, before any submit event occurs. 

Tested on the StackBlitz example and got the same behaviour. Only added:
```
const { form, errors, message, constraints, enhance, submitting } = superForm(data.form);
```
```
{#if submitting} Submission loading icon {/if} 
```

And the text was there when the site/form loaded, before any interaction with it.

**Comment by ciscoheat** [comment]
`submitting` is a store, so you need to do `{#if $submitting}`!

**Comment by je-movers-market** [comment]
Well then.... thank you haha.
