### ISSUE TITLE
Checkbox workaround does not fire onChange event

### ISSUE THREAD

**Issue by mpost** [ciscoheat/sveltekit-superforms#337]
Running superforms 2.0.0

When creating a checkbox component as outlined here: https://superforms.rocks/components#a-minor-issue-checkboxes, the `onChange` listener of the SuperForm is not invoked when selecting the checkbox. Deselecting works as expected. The form itself is updated correctly.

**Comment by ciscoheat** [comment]
Can't reproduce this locally. Can you make a MRE on stackblitz? Here's a start: https://stackblitz.com/edit/superforms-2-testing-fryht2?file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2FCheckBox.svelte
