### ISSUE TITLE
File upload undefined

### ISSUE THREAD

**Issue by EmilZackrisson** [ciscoheat/sveltekit-superforms#338]
Hi!
I'm trying to implement the new file uploading feature and I'm having some problems.
It seems like the server doesn't receive the file, just an array with undefined. I tried copy and paste the example code and it doesn't work either, but it works on stackblitz.

This is the output from SuperDebug:
```
{
  title: "djhfg",
  content: "jkshdfkjsd",
  createdBy: "",
  attachments: [
    {
      name: "favicon.png",
      size: 1571,
      type: "image/png",
      lastModified: 2024-02-02T21:33:38.284Z
    }
  ],
  id: "",
  created: ""
}
```

... and this is console.log on the server:
```
{
  id: 'y4djcs',
  valid: false,
  posted: true,
  errors: { attachments: { '0': [Array] } },
  data: {
    title: 'djhfg',
    content: 'jkshdfkjsd',
    createdBy: 'v615zyol29loqu4',
    attachments: [ undefined ],
    id: '',
    created: ''
  }
}
```
and
```
if (!form.valid) {
			console.log('Invalid form', form.errors);
			return fail(400, withFiles({ form }));
}
```
Outputs: "Invalid form { attachments: { '0': [ ‘The file must be a file’ ] } }"

Any suggestions on how to fix this is appreciated.

**Comment by ciscoheat** [comment]
If it works on Stackblitz, it's hard to say what exactly in your code or environment is not making it work. Sometimes it's as simple as a missing name attribute on the file input field. 

Here's a working example of mine anyway, maybe you can figure it out from there: https://stackblitz.com/edit/superforms-2-file-uploads?file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2Fschema.ts,package.json

**Comment by EmilZackrisson** [comment]
I think it's something with superValidate() that doesn't seem to work for me. If I await request.formData(), the file is there.

+page.server.ts
```ts
const schema = z.object({
	image: z
		.custom<File>((f) => f instanceof File, 'Please upload a file.')
		.refine((f) => f.size < 1024 * 1024 * 10, 'Max 10 MB upload size.')
});

export const actions = {
	default: async ({ request }) => {
		const formData = await request.formData();
		const form = await superValidate(formData, zod(schema)); // Doesn't matter if i put in request instead of formData

		console.log((formData.get('image') as File).size); // Works
		console.log(form.data.image.size); // Doesn't work (undefined)
                ...
        }
}
```

+page.svelte
``` svelte
<script lang="ts">
	import type { PageData } from './$types';
	import Header from '$lib/components/Header.svelte';
	export let data: PageData;
</script>

<Header />

<form method="POST" enctype="multipart/form-data" class="pt-56">
	<input type="file" name="image" />
	<button>Submit</button>
</form>
```

**Comment by EmilZackrisson** [comment]
Solved it!
Needed to change
```ts
const form = await superValidate(formData, zod(schema));
```
to
```ts
const form = await superValidate(request, zod(schema), {
			allowFiles: true
});
```

Does it have something to do with SUPERFORMS_LEGACY option in vite.config.ts? Maybe add it to the documentation.

**Comment by ciscoheat** [comment]
Right, if you have set SUPERFORMS_LEGACY, no files will be allowed. It's mentioned [here](https://superforms.rocks/concepts/files#preventing-file-uploads), but as always you can never mention something enough, so I'll add it in a couple of more places.
