### ISSUE TITLE
onChange target is generic Element insted of HTMLInputElement or an element with value property

### ISSUE THREAD

**Issue by juanpablopiano** [ciscoheat/sveltekit-superforms#339]
**Description**
When using the new `onChange` event, if I try to access `event.target.value`, typescript will throw this error: `Property 'value' does not exist on type 'Element'. `

**If applicable, a MRE**
https://stackblitz.com/edit/superforms-2-testing-cvxhuj?file=src%2Froutes%2F%2Bpage.svelte
Stackblitz doesn't seem to highlight typescript errors, but it's there.

![image](https://github.com/ciscoheat/sveltekit-superforms/assets/59584304/7d03ea5e-519a-408a-8d04-bfadc3abda99)

Is it possible to provide a way to discriminate which type of input it is?

It would also be useful to have an accessor to the changed value

**Comment by ciscoheat** [comment]
I have to be certain that the input cannot be something else, before narrowing the type. In the meantime, you can use something like `if(e.target instanceof HTMLInputElement || e.target instanceof HTMLOptionElement)`

Nice idea about the accessor, will add that in a future release.

**Comment by juanpablopiano** [comment]
@ciscoheat  For update forms, could it be possible to have a data comparator?

Let's say I want to add a button that's disabled as long as the data of the form hasn't change. If it's different than the initial data before submitting, it should somehow be true (data changed).

**Comment by ciscoheat** [comment]
You can use isTainted for that: https://superforms.rocks/whats-new-v2#new-istainted-method

**Comment by juanpablopiano** [comment]
> You can use isTainted for that: https://superforms.rocks/whats-new-v2#new-istainted-method

You are the greatest, it works perfectly! Thank you very much.

**Comment by ciscoheat** [comment]
I'm gonna close this after reading the HTML specificationq `Element` has to be the default, since elements with `contenteditable` can also trigger the input event, so it can be pretty much anything.
