### ISSUE TITLE
Trouble using $posted store

### ISSUE THREAD

**Issue by ciscoheat** [ciscoheat/sveltekit-superforms#346]
**Description**

[This project](https://stackblitz.com/edit/superforms-2-testing-jmpvxw?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte) works locally but not on Stackblitz. I appreciate if this could be confirmed to work locally for others.

**How to reproduce:**

1. Click submit with an empty form. Posted should be true.
2. Enter a valid name and email, click submit. Posted should be true in SuperDebug, but is false on Stackblitz (true locally).

**Comment by shyakadavis** [comment]
Hi, @ciscoheat 

> I appreciate if this could be confirmed to work locally for others.

I don't know if I misunderstood the description, but the stackblitz flow is the same, in that it's `true` -> `false`. Surprisingly, even locally, this is the behaviour. (I downloaded the same shared repro above)


https://github.com/ciscoheat/sveltekit-superforms/assets/87414827/a0099e07-7064-4645-a8dd-8918a5a36a0d

Please let me know if there's anything else you want me to confirm/check out.

**Comment by ciscoheat** [comment]
Thank you, I realized what is the problem now. When the form is reset, the $posted value is also reset to `false`. It should be `true` if the form is posted, so I'll fix that for the next release.

**Comment by ciscoheat** [comment]
Fixed now with 2.2.1.
