### ISSUE TITLE
Dates become undefined if schema validation produces error in form action

### ISSUE THREAD

**Issue by sillvva** [ciscoheat/sveltekit-superforms#348]
**Description**
In both of these form submissions below, I had selected a date. If the schema produces an error in the form action, the date becomes undefined. Other fields do not have this issue as far as I can tell. Only dates. This means that such an error would require the user to re-enter the dates every time.

I also do not think this is a Valibot issue, as performing client-side validation does not create this side effect.

![CleanShot 2024-02-17 at 13 47 24@2x](https://github.com/ciscoheat/sveltekit-superforms/assets/5138384/fd46efc9-3190-4f37-a4a6-3f5b9305dee0)

MRE: https://stackblitz.com/edit/superforms-dates-issue?file=src%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment]
Thank you for reporting, will be fixed in the next release. And thank you very much for sponsoring! :)

**Comment by ciscoheat** [comment]
Should be fixed now with 2.3.0, can you confirm that it is?

**Comment by sillvva** [comment]
Yep! It works. Thank you :)

![CleanShot 2024-02-18 at 07 19 28@2x](https://github.com/ciscoheat/sveltekit-superforms/assets/5138384/023ffb4f-651a-4cad-8558-8348809f2b94)
