### ISSUE TITLE
Add possibility to pass options to validation libraries (Valibot)

### ISSUE THREAD

**Issue by vladshcherbin** [ciscoheat/sveltekit-superforms#349]
**Is your feature request related to a problem? Please describe.**
In valibot (and probably other validation libraries) it's possible to pass some configuration options - https://valibot.dev/guides/parse-data/#configuration.

I'd love to use `abortPipeEarly` in my forms to reduce validations when first error is found.

**Describe the solution you'd like**
I'd love to have a way to pass options to validation library, for example

```js
await superValidate(valibot(SignUpSchema, { abortPipeEarly: true }))
```

_Even better if this could be a global option since I'd love to use it in every form_.
I can have a helper for this, just a convenience if this could be somehow baked inside 🙌

**Describe alternatives you've considered**
Any way of doing this is great

**Additional context**
Sorry if this is already possible, I haven't found a way 🙈

**Comment by ciscoheat** [comment]
Sure, I'll add that as a config option in the next release. The adapters are made to be configurable like this.

If you want to reuse the option, you can do it like this: https://superforms.rocks/faq#i-want-to-reuse-common-options-how-to-do-that-easily

**Comment by ciscoheat** [comment]
Added now in 2.4.0, as a `config` option. Just note that the options must be added on the top-level, for [schema caching](https://superforms.rocks/get-started#schema-caching) to work.

```ts
// Top-level
const options = { config: { abortPipeEarly: true }}

// In the load functions and form actions
await superValidate(valibot(SignUpSchema, options))
```
