### ISSUE TITLE
Potential subscription memory leak from Superform client

### ISSUE THREAD

**Issue by fnimick** [ciscoheat/sveltekit-superforms#35]
It's hard to prove this one way or the other (I don't know of any tools which will detect or validate these), but while I was working with superforms, I noticed a couple subscriptions in the client that don't appear to be cleaned up.

The `Data.subscribe` and `page.subscribe` calls here: https://github.com/ciscoheat/sveltekit-superforms/blob/main/src/lib/client/index.ts#L405 and https://github.com/ciscoheat/sveltekit-superforms/blob/main/src/lib/client/index.ts#L447

We probably want to take the return values of the subscription calls, add them to an array, then return an `unsubscribe` function which runs them all. The developer is then responsible for calling `onDestroy(unsubscribe)` in their page component.

**Comment by fnimick** [comment]
Alternatively, we can wrap them in `onDestroy` in the superform library itself. https://geoffrich.net/posts/svelte-lifecycle-examples/

**Comment by ciscoheat** [comment]
Yes, onDestroy in the library sounds good, thank you for noticing! Will fix soon!

**Comment by ciscoheat** [comment]
Unsubscribe from `page` I can understand, but is it necessary to unsubscribe from `Data`, since it's contained in the `superForm` function and should be removed when there are no references to the form anyway?

**Comment by fnimick** [comment]
re: unsubscribe from `Data`, I'm not sure. I would err on the side of unsubscribing since there's no harm in doing it if unnecessary, but not doing it if necessary will lead to a memory leak.

Unfortunately I don't know of any way to check for these leaks.

**Comment by ciscoheat** [comment]
I think I plugged the memory leaks now in v0.6, using an array that runs all unsubscriptions upon `onDestroy`. Seems to work well.
