### ISSUE TITLE
formFieldProxy: Argument of type 'string' is not assignable to parameter of type 'never'

### ISSUE THREAD

**Issue by danielres** [ciscoheat/sveltekit-superforms#352]
I am trying to componentize my forms, but keep having this error.
In my app, the component calling the componentized `TextField`  is not being rendered (no error messages).

![Screenshot from 2024-02-19 13-20-14](https://github.com/ciscoheat/sveltekit-superforms/assets/168687/e8ec89fa-570e-4bcc-ba57-f06fac77ee60)

This happens with a copy-paste "as is" from the example: https://stackblitz.com/edit/superforms-2-componentization?file=src%2Flib%2FTextField.svelte

Same issue when I copy-paste the examples from the doc (https://superforms.rocks/components#using-a-formfieldproxy)

Dependencies & versions:

```
    "@sveltejs/kit": "^2.5.0",
    "@sveltejs/vite-plugin-svelte": "^3.0.2",
    "svelte": "^5.0.0-next.55",
    "vite": "^5.1.1",
    "sveltekit-superforms": "^2.3.0",
```

Thank you

**Comment by vladshcherbin** [comment]
Here's my reproduction with similar error - https://github.com/vladshcherbin/svelte-superforms/tree/reusable-components

<img width="832" alt="image" src="https://github.com/ciscoheat/sveltekit-superforms/assets/6711845/b94b8886-1044-449a-b6b5-89ca343290e8">

I've tried to use svelte `context` and store/retrieve form from there to avoid passing `{form}` to each input. Seems like the error is when it doesn't understand the shape of schema. Everything's working though.

If I pass `{form}` to all input components instead of a general context one or even change the `Input.svelte` generics from `Record<string, unknown>` to `Record<string, string>` the error disappears.

**Comment by ciscoheat** [comment]
Compare with the updated example, it works without any error for TS.

**Comment by vladshcherbin** [comment]
Updated example doesn't even use TS :) Add any type and it breaks, link from above - https://stackblitz.com/edit/superforms-2-componentization?file=src%2Flib%2FTextField.svelte:

<img width="1582" alt="image" src="https://github.com/ciscoheat/sveltekit-superforms/assets/6711845/d862d9a2-776f-47d2-9c9e-e77bb9ac9243">

**Comment by ciscoheat** [comment]
Yes, because Stackblitz doesn't support types well, especially in svelte components. Test it locally (with TS) and it should work fine.

**Comment by danielres** [comment]
Thank you, it's working like a charm now ! 😀🙏

**Comment by danielres** [comment]
Btw, just declaring the generics in the main script tag should work AFAIK. 

I can confirm this works just fine for me:

```
<script lang="ts" generics="T extends Record<string, unknown>">
```


*Without* this part:

```
<script lang="ts" context="module">
  type T = Record<string, unknown>;
</script>
```

**Comment by ciscoheat** [comment]
It works at runtime, but you will get type errors:

<img width="402" alt="2024-02-19 22_06_58-AutoComplete svelte - sveltekit-superforms-v2 - Visual Studio Code" src="https://github.com/ciscoheat/sveltekit-superforms/assets/130450/79a85c9f-e063-4e32-bf35-99671894ebc1">

**Comment by danielres** [comment]
Looks like I'm lucky, no type errors for me 🙂

In case this is useful:

- VSCode TS version: `5.3.2`

- devDependencies versions:

```
    "@sveltejs/kit": "^2.5.0",
    "@sveltejs/vite-plugin-svelte": "^3.0.2",
    "@total-typescript/ts-reset": "^0.5.1",
    "@types/node": "20.11.17",
    "@typescript-eslint/eslint-plugin": "^7.0.0",
    "@typescript-eslint/parser": "^6.21.0",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-svelte": "^2.35.1",
    "prettier": "^3.2.5",
    "prettier-plugin-svelte": "^3.2.1",
    "svelte": "^5.0.0-next.60",
    "svelte-check": "^3.6.4",
    "tslib": "^2.6.2",
    "typescript": "^5.3.3",
    "vite": "^5.1.1",
    ``

**Comment by ciscoheat** [comment]
Could your `no-undef` eslint rule be disabled?

Just a note, if you're using Svelte 5, then you should have the next version of the eslint plugin as well:

`"eslint-plugin-svelte": "2.36.0-next.5",`

**Comment by danielres** [comment]
(Thank you for the tip regarding eslint-plugin-svelte!)

Doesn't look like it, here is my `.eslintrc.cjs`

```
module.exports = {
  root: true,
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:svelte/recommended',
    'prettier',
  ],
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint'],
  parserOptions: {
    sourceType: 'module',
    ecmaVersion: 2020,
    extraFileExtensions: ['.svelte'],
  },
  env: {
    browser: true,
    es2017: true,
    node: true,
  },
  overrides: [
    {
      files: ['*.svelte'],
      parser: 'svelte-eslint-parser',
      parserOptions: {
        parser: '@typescript-eslint/parser',
      },
    },
  ],
  rules: {
    '@typescript-eslint/no-unused-vars': [
      'warn',
      {
        varsIgnorePattern: '^_',
        argsIgnorePattern: '^_',
      },
    ],
  },
}
``

**Comment by ciscoheat** [comment]
Nothing even if you enable that rule explicitly?

**Comment by danielres** [comment]
still no errors, even when enabling the rule explicitly

```
rules: {
+    'no-undef': 'error',
    '@typescript-eslint/no-unused-vars': [
```
