### ISSUE TITLE
Reset initial form data

### ISSUE THREAD

**Issue by philippone** [ciscoheat/sveltekit-superforms#354]
**Is your feature request related to a problem? Please describe.**
I use the client-side version of `superform(initialData, {SPA: true, invalidate: false, resetForm: false})` and would like to reset the initial data of the form.

**Describe the solution you'd like**
`superform()` could provide a method/store to update the initial data.

**Additional context**
I have a demo application where you have a form with one input field that has initial data ("initial value"):
https://stackblitz.com/edit/sveltejs-kit-template-default-4vvecd?file=src%2Froutes%2F%2Bpage.svelte

1. Change the initial data to another string (for instance "new value")  
2. Submit (= save data on server and reset form manually)
3. Click reset to latest saved data

The input field shows the first initial data ("initial value" ) instead of ("new value").

I could store the latest saved data in a local variable in my page and use it in every `reset({data: latestStoreData)` but it would be nice to manipulate the initial data without invalidateAll (page load reload)

**Comment by ciscoheat** [comment]
Looks like it should be possible to do this, which means that in the next version, updating the `initialData` it will reflect in the future resets. I'll have to make sure it doesn't break anything though, so I'm not sure yet.

**Comment by ciscoheat** [comment]
Should be fixed now with 2.5.0, check if you can modify `initialData` now and it will be the new base for resets.

**Comment by philippone** [comment]
Thank you! It's working.

TIL: With `Object.assign(initalData, form.data);` it's easy to update the whole object(do not modifying object reference) instead of assigning each property separately.
