### ISSUE TITLE
Installing Superforms Causes Cloudflare Deployment to Fail

### ISSUE THREAD

**Issue by MattHeslington** [ciscoheat/sveltekit-superforms#357]
Hello,

I'm just bootstrapping an skeleton Sveltekit project with necessary dependencies and deploying to Cloudflare Pages.
Adding sveltekit-superforms causes the following build/deployment error:

```
22:51:03.992	Installing project dependencies: npm clean-install --progress=false
22:51:05.850	npm ERR! code EUSAGE
22:51:05.853	npm ERR! 
22:51:05.854	npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
22:51:05.854	npm ERR! 
22:51:05.854	npm ERR! Missing: @types/json-schema@7.0.15 from lock file
22:51:05.854	npm ERR! Missing: esbuild-runner@2.2.2 from lock file
22:51:05.854	npm ERR! Missing: source-map-support@0.5.21 from lock file
22:51:05.854	npm ERR! Missing: tslib@2.4.0 from lock file
22:51:05.854	npm ERR! Missing: buffer-from@1.1.2 from lock file
22:51:05.854	npm ERR! 
22:51:05.855	npm ERR! Clean install a project
22:51:05.855	npm ERR! 
22:51:05.855	npm ERR! Usage:
22:51:05.855	npm ERR! npm ci
22:51:05.855	npm ERR! 
22:51:05.855	npm ERR! Options:
22:51:05.855	npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
22:51:05.855	npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
22:51:05.855	npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
22:51:05.856	npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
22:51:05.856	npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
22:51:05.856	npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
22:51:05.856	npm ERR! 
22:51:05.856	npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
22:51:05.856	npm ERR! 
22:51:05.856	npm ERR! Run "npm help ci" for more info
22:51:05.857	
22:51:05.857	npm ERR! A complete log of this run can be found in: /opt/buildhome/.npm/_logs/2024-02-21T14_51_04_828Z-debug-0.log
22:51:05.866	Error: Exit with error code: 1
...
```

I have tried the following steps to resolve the issue without success:

1. Delete the package-lock.json file and run npm install again
2. Run npm update to update the dependencies in package.json to match package-lock.json

Uninstalling superforms results in a successful build/deployment.

```
"sveltekit-superforms": "^2.4.0"
node v20.10.0
npm v10.2.3
```

Any very very much appreciated!
Cheers, 
Matt

**Comment by ciscoheat** [comment]
Haven't deployed on Cloudflare before, I think I need a simple repo that reproduces this problem before I can start figuring things out.

**Comment by shyakadavis** [comment]
Hi;

When I first this, I was worried, first because of the other issues I saw of validators being added regardless of whether you're using them or not, and also because I use CF for all my deployments; but I wanted to let you know that it worked just fine for me, and it might be an isolated issue.

But, to be fair, I didn't set up a complete Superforms flow - just bare necessities to see if I would run into that issue. And of course, I'm using `pnpm` like everyone else, so maybe it might be an `npm` issue - who knows 🤷‍♂️

**Comment by MattHeslington** [comment]
> Hi;
> 
> When I first this, I was worried, first because of the other issues I saw of validators being added regardless of whether you're using them or not, and also because I use CF for all my deployments; but I wanted to let you know that it worked just fine for me, and it might be an isolated issue.
> 
> But, to be fair, I didn't set up a complete Superforms flow - just bare necessities to see if I would run into that issue. And of course, I'm using `pnpm` like everyone else, so maybe it might be an `npm` issue - who knows 🤷‍♂️

Cheers. I didn't even implement any flow. It's was just a skeleton SvelteKit project with the single, bare-bones welcome page. Just purely having the dependency in package.json caused the deployment to fail. I couldn't work out what was causing the failure, and had to go through everything one-by-one to find the breakpoint.
Thanks for the info, I shall investigate further this afternoon

**Comment by MattHeslington** [comment]
> Haven't deployed on Cloudflare before, I think I need a simple repo that reproduces this problem before I can start figuring things out.

Sorry for the delay. Here's a repo which reproduces the issue. A skeleton SvelteKit project with just Tailwind, sveltekit-superforms and the Cloudflare adpter. 
[Repo](https://github.com/MattHeslington/superforms-fail)
[Live](https://superforms-fail.pages.dev)

Superforms is not used anywhwere, it's just a dependency in a the skeleton project. Uninstalling it will allow deployment on Cloudflare pages.

**Comment by MattHeslington** [comment]
> Haven't deployed on Cloudflare before, I think I need a simple repo that reproduces this problem before I can start figuring things out.

Apologies for the delay. Here are a couple of sample repos, one JS, one TS. They're both just the 'skeleton' option for SvelteKit projects, with Tailwind added. Superforms is not used anywhere - it's just a dependency in each project. Both TS and JS deployments result in the same error log (above) when superforms is a dependency

[JS Repo](https://github.com/MattHeslington/superforms-fail)
[TS Repo](https://github.com/MattHeslington/superforms-fail-ts)

**Comment by shyakadavis** [comment]
Hi, @MattHeslington 

This is very strange. I just deployed it, and got the same error 🙁 

And as suspected, I switched up `npm` for `pnpm` such that I'm deploying a `pnpm-lock.yaml` instead of a `package-lock.yaml`, and it works perfectly. 😅

> Check here: https://github.com/shyakadavis/superforms-fail-ts

I don't know the internals, but seems that Superforms has better `pnpm` support than it does `npm`.

Suggestion:

For now, does using `pnpm` violate your workflow? Because for me, the merits of using it outweigh the alternatives around. 🤷‍♂️ 

Anywho, hoping to here Adreas' input on this. 🙂

**Comment by MattHeslington** [comment]
> Hi, @MattHeslington
> 
> This is very strange. I just deployed it, and got the same error 🙁
> 
> And as suspected, I switched up `npm` for `pnpm` such that I'm deploying a `pnpm-lock.yaml` instead of a `package-lock.yaml`, and it works perfectly. 😅
> 
> > Check here: https://github.com/shyakadavis/superforms-fail-ts
> 
> I don't know the internals, but seems that Superforms has better `pnpm` support than it does `npm`.
> 
> Suggestion:
> 
> For now, does using `pnpm` violate your workflow? Because for me, the merits of using it outweigh the alternatives around. 🤷‍♂️
> 
> Anywho, hoping to here Andreas' input on this. 🙂

Thanks for checking it out, I really appreciate it. pnpm doesn't disrupt my workflow at all, I'll use that instead. Thanks for your help 👍🏻

**Comment by ciscoheat** [comment]
So we can conclude that this is a "feature" for upgrading to the superior pnpm. 😄
