### ISSUE TITLE
New reset-behaviour

### ISSUE THREAD

**Issue by v-morlock** [ciscoheat/sveltekit-superforms#358]
- [x] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
Hi, 

thanks for this great library. I think this is somewhere between question and issue. I recognized that the default behaviour has been changed to always reset the form upon submit in superforms 2. I get why this could be the new default, but I'm unsure how I can use this new behaviour to build a good "update" action. Let's assume I have a form that's supposed to update some entity. When submitting that, it makes sense to reset the form - however, I don't want to reset it to the state it had when the page initially loaded. Disabling resetting entirely also isn't perfect, as that would hide if an update in the backend somehow fails.

Here's a quick example that's supposed to mimic sth like a profile editor, where i "forgot" to write the updated email to the "db". You can set "resetForm" to either true or false, but in both cases, the form won't display the correct data as it's currently written to the database. 

- When resetForm is set to true, the form will always present the state as received on initial page load (even though the loader is called on each submit and returns the correct data as in db). 
- When resetForm is false, the form will just keep the data as entered but will not reflect that the email in "db" isn't actually updated

https://stackblitz.com/edit/superforms-2-testing-ng6jdi?file=src%2Froutes%2F%2Bpage.svelte

I recognized that i could overwrite the form data in the action - but i'm not sure that's the way I'm supposed to do? I would have expected the form to always use the latest data returned by the loader when resetting.

**Comment by ciscoheat** [comment]
Hi, glad you like Superforms! I'm not sure I see the problem when resetForm is false, as it usually is in a CRUD editor like this (compared to a login/signup form). You update the "db" with `db.name = form.data.name` (a successful update), and the posted data is sent back to the form, reflecting the update. What do you expect to happen?

**Comment by v-morlock** [comment]
Hi, a  crud form is exactly what I’m trying to accomplish (it just said „login“ because that’s what the template said initially). 

You‘re right that „resetForm: false“ does as expected in case everything is implemented properly. 

But as I tried to show in the example, the form won’t actually display what’s returned by the „loader“-function after the submit. Am I supposed to rewrite the data of the form object in my action?

My point is just that I would expect the form to actually display the latest content of the database after submitting, I think that’s what most users are used to, compare e.g. a traditional webapp where the page actually reloads after posting the form. 

In practise this would e.g. make a difference when there’s an error in the update logic (some form accidentally not being updated), or if the backend rewrites some of the inputs.

**Comment by v-morlock** [comment]
Jup absolutely, but it's not displayed in the form... Look at the example where i "forgot" to store the mail Adress. When you click on save, the loader returns example@example.com as mailadress, but the form still displays the mailadress you've entered. I would want the form to always display what the loader returned last to reflect the correct state of the backend

**Comment by ciscoheat** [comment]
I cannot see anywhere in the example that you forgot to write to the db, as this line is present: `db.name = form.data.name;`

**Comment by ciscoheat** [comment]
Since invalidateAll is true, it should update. I'll have to take a closer look.

**Comment by ciscoheat** [comment]
The example works for me locally, the email address is reset to the default by the load function, at least on Svelte 5. Can you check if it does the same for you?

**Comment by v-morlock** [comment]
I'm on svelte 4.2.11 and there it's showing the same behaviour as in the posted example, always keeping what's entered locally, no matter which value is being returned by the "loader". 

I'm also kinda unsure about the rationale of the behaviour of "resetForm" - why would one want to keep resetting a form to it's initial state (= the data returned by the loader on first load) instead of resetting it to the data currently returned by the loader? Without reading the docs, i would have assumed the flags behave like this:
- `resetForm: true` → resets to the value the loader returns once submitted
- `resetForm: false` → keeps the values entered locally, no matter what's being returned by the backend on submit

I'm sure there's a good reason things are implemented like that, but maybe you can quickly explain them to me? :) Thanks a lot!

**Comment by v-morlock** [comment]
Ah what i wrote is actually not fully correct, the form does indeed change the values with `resetForm: false`, but to the value of form.data that's returned by the action, not to the value returned by the loader

**Comment by ciscoheat** [comment]
There were some tricky logic behind this. The key is the `applyAction` option, which should be set to `false` in your case. Then it will not apply the form action, and the load function will not be overwritten by the updated form value. But, that logic was also not working, so it will be fixed in the next version.

Finally, resetForm can be useful if you have `invalidateAll: false`, in which case it will or won't reset without any load function.

**Comment by ciscoheat** [comment]
Sorry, after considering this, it cannot be done automatically since you can add status messages and errors in the form action, which should be displayed when returning { form }. If applying the load function instead, any modifications in the form action would be overwritten.

Since this has not been reported for almost a year, I'm considering partial updates of the data a rare case, you can work around it like this (in the form action): 

- Fetch the missing data from the DB in the form action, before returning { form }.
- A hack, available from the next version: `delete form.data.email` and that field won't be updated by the form action, so the load action data will remain. The compiler will complain, but it will work.

**Comment by v-morlock** [comment]
Alright, thanks for having a look. It’s more about being able to instantly see when there‘s a bug in the server action during testing. Right now, I always need to do a full refresh to see whether the value was actually updated on the server. 

I get why resetForm:false would always display what’s being returned by the action. 

But, imho it would be totally reasonable that resetForm:true always resets to the latest data returned by the loader - what’s the reason against that?

Just can’t really think if a case where the data returned by the loader would change but you wouldn’t want to reflect that in the form when it gets resetted?

**Comment by ciscoheat** [comment]
Maybe the `invalidateAll` can take an extra option, which will prevent the form action data from being used. It's complicated behind the scenes, so I have to see if it works without breaking anything.

**Comment by v-morlock** [comment]
Not sure how the action data is involved when resetForm is on true, as it's resetting the form to the data that was passed to client-superValidate on first page load.

I'd imagine the simplest solution would be to change resetForm to always reset to the latest data returned by the loader, if that's possible somehow?

**Comment by ciscoheat** [comment]
The page store can be updated by several sources, so it's complicated.

**Comment by v-morlock** [comment]
thanks a lot, that's great to hear!

**Comment by ciscoheat** [comment]
Added now in 2.6.1, please try and see if it works for you.

**Comment by ciscoheat** [comment]
Closing this, as the tests are passing.
