### ISSUE TITLE
Small typo in docs: reference to z despite switching the validation library to Joi

### ISSUE THREAD

**Issue by gregmsanderson** [ciscoheat/sveltekit-superforms#359]
**Description**

I noticed that upon selecting "Joi" the code sample leaves a reference to `z`.

If you visit https://superforms.rocks/get-started/joi and scroll down, the code sample for Joi has `z.object`.

```js
import Joi from 'joi';

const schema = z.object({
  name: Joi.string().default('Hello world!'),
  email: Joi.string().email().required()
});
```

... which naturally results in a console error when used ...

> ReferenceError: z is not defined

**Comment by ciscoheat** [comment]
Thank you, you can fix it directly in the repo: https://github.com/ciscoheat/superforms-web/tree/main/src/routes

**Comment by gregmsanderson** [comment]
@ciscoheat Done! https://github.com/ciscoheat/superforms-web/pull/27
