### ISSUE TITLE
In SPA mode, navigating to a page that triggers a redirect inside `onUpdate` fails silently

### ISSUE THREAD

**Issue by fnimick** [ciscoheat/sveltekit-superforms#360]
**Description**
Navigating to a page in `onUpdate` via `await goto(....)` fails if that page has a client-side load function that calls `redirect()`.

**If applicable, a MRE**
https://stackblitz.com/edit/superforms-2-testing-qf9uxu?file=src%2Froutes%2F%2Bpage.svelte

In this example, calling `await goto('/target');` fails because `target/+page.ts` has a load function that throws a redirect.

Either calling `cancel()` first, or instead calling `goto('/second-target')` which does not have a redirect, works fine.

**Comment by ciscoheat** [comment]
Fixed now in 2.6.1, forked the project and tested on Stackblitz.
