### ISSUE TITLE
Reverse In and Out type parameter in superForm return type

### ISSUE THREAD

**Issue by hazelnutcloud** [ciscoheat/sveltekit-superforms#362]
- [x] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
When using valibot with transform function that produces a schema with an input type differing from the output type, passing the schema into the superform() function returns a SuperForm type that uses the output type as its first type parameter. As a result, when consuming the form store returned by the superform() object, the types become the output type whereas I expected them to be the input types.

**If applicable, a MRE**
https://stackblitz.com/edit/superforms-2-testing-valibot-824118?file=src%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment]
Sorry, the Stackblitz example only has a three-line schema, did you save the correct one?

```ts
export const schema = object({
  digit: date()
});
```
