### ISSUE TITLE
FormPathLeaves<FormObj, Date> = never

### ISSUE THREAD

**Issue by sillvva** [ciscoheat/sveltekit-superforms#363]
**Description**
I believe there is a bug with the updated `FormPathLeaves<T, Type>` when using `Date`

**If applicable, a MRE**
[TS Playground](https://www.typescriptlang.org/play?#code/PTAEBUFEGV2goeAXAngBwKagDIHsDmAIgIZLGgC8oA3vKKAJYAmAXKAHYCuAtgEYYAnANx1Q3DAGcJxfBjYSkAhu3wj6TUnNAkkGNaE4TBAfja169Zmy59B++u2Lj5i5atEBffWXwSXSlQBtAF0RL0QAY1x2BVAAGwIdYjY8IlJyKnNGVlAARgAaUXEpGS0AIjLC9U1rDAB3bU0ACgBKKoMjATN4AEgrPMKex2dQMoAxAWJ2CIYJMs92nz9QEPgPRFRMHAJsDGIAN0lKUDHcAW4ABVIAC12DyQAeVKSAPhEQCwA9Y2R0LFSAHI8fgCO6HCTHU7nK5IW57cFPRLpfIcYGCN7wD70b6-LbPTRgo5UKGXG6EiSItJkFE6DAYrGgHGYsAAYQA8oRIBs-qAAEKcBhxJAASXYbN4ACsMBEkBCqLTQAAfUDQDBIB6cdgAa3YuDq7BeSpOgr0iAwAA80GckKBNlgAIJxOIAaQwKAp4ENVHAoAtunYTAhPuMoC1btwADMIKBaodhGbLdbbTyLgwIlrwH8HuAUc7feb-YHQI6XW6PS8vdG-RgAxDqCstYx2KBncE2FMUKAPKAQ+BAq2YxwMHGRMyINcplqIUhcKBrkgkGg-CAmMOAHQz4BxTgzKa8CLATUMaIAWjtJ-EAnwbhPyjPfwkESUaCQJ4AnMQ4vALVaBDa7aAACygiyAAquwx7sNmla0D0-ZNsWTquu60FtqAqbppmmDZrmGLhJiABUBF0AROCzLKoCfnEoBoDcELKJRza4JK0o2sQEIKAE+CUREESSBIZwSGuJHAN+iZ-smWwkjC1zZvmhYQsxUoyiiWFYFQHaVpxbigAAZL00CuCoMk4TQoARoKuhdKAADkVE2UIoBKfaaCYAGsZ2DRNxsDZDmSVoaldhihHEaApHYORXmwvRzZTE5LEypRHFGdxxC8fxgkorwnA2tEcSdnUDCwhwp5KaxELsTxfFSAwvBxFgaACLgmB-gwkjCWFKoMNwgrEAItqzrCWD1fcMWUSVq62gIGAYCiDBRiguCcPEuC4I2pC2tcWBlYllXkIoM2gJxO5IJw00dQRok-kmAHSWS8KPD61a1vFylIKpPIaewKBaSlekGSlJk5mZFlCoIPkjeCfnOa5NY5Oww6ebRsI+X5dpsIFHjBcAREkWRsTI9cY1xTtbHJVxVUZQIEhZTlTnsPloCFcVursCepMVRV6U1XVDVNS1SBtUJeOOgJTYRNuq7TltoAAPqCE11PmW1cRMOZZyveVjFq31kzuhdV3if+PJ3bC5IAOpFdckACIrHryXDikJe9ECfYxP3HNpKj-T0hlcUDKL1qDVkQw9EjQ5KLluTkNny7bgl+YTqOOejrtbFjo446F4WRVRlG28Q7oISTztJUdf1pdVAnUwbYm-sbUlnKSsL2gXKFPQWjuaypafqe7v0U-pvuAzcplB5Z4O2brhfh45MPRx5whRdcyf+RjPIZ4gHzgBO2rTrO86LsuwAKGlWq4HGEYJHUa5RNwwDEMAADsT8ACwAKy5AAzAAbE-z8AAYAAcb5X64iwMKCQ9pvrQWOLwVaI1mzPSLE0DuCkhxxh7FNTgWA2ARk-EYFoWDFA4MHPguIRhRwARZNECIpAHi9Bkg7F6Xt8CDABH6ZhRZWHwErAAAwACTUBkh4IRTDkEQl8lgqRPk1w2VEdQDhBYPB8KoTyP2bgZJshfJBOUNBejB0nnZNu4cjQ2UhpIGyZj7IiB6PPOG-gdLKgRiOXoSdy5cVsanDsYQ1FbGFBGBhPRtGC2iBCCRKoR6whCbowYFxppqwiWGRaUYYlhMGNATgkpBg7xrIMSAFC+4uMEIMAAap+UhVBNQ6j1OwXhxw0kxECPEjATBghcIhJkyUvQQyNIkIEGydobLtIicUgQvQei9i2nUnoPQ2DlO3FgCJfSBlDOCBMyZ44awbMXr0NgBTKHci2Bo4yo9ehoK7qTQYfSOmRP9jcG5mQJmGOsnZJ0DkJn2PchguwEz3G+VsT0VOYzbHrErBcl6-JLKinFG9CQPTQABIeH0lENkXk2VRRY0xyo3lxAxaAFZNlCbDJeHsqsncXpNGUBGQQoBQItFWLMn4szZnKiRSi2yXymD4tYSiGh0x6GEuJcEFEhKuUkpRGM1SpKWU9DZYEjlaKJ4CHxcYvW2Kp7vNFTosJAzhWSsRgIaVGy5WgCaACaIQInTEF5g8UChoImkxNUyu5mizmytlRa9gVq4g2vqnal4gwPWzNgsG2ZLy2CEvRaEZ1squWRp1U0my4qY1htme4wR1AhU3GGR4QIQibAgg8MEVRsaWWp0JWswFwb1hhplR6tg7LE001suizFYcrE4vsiiTN2bYS5vzdQQtghi18INXGaVLQJndFlfBBikACyTBlA8EsyFywolYS8NCXqfV+owNmfswQHUUqLE6j1zLg3yqCWmlFZbZnJsjrDAMGK709F5a+-ldD1R9uuMM7VoSk0psDa+qVr6+ytjLfQetHrlQ7s4Na214Gj23KpewGl-V6WMvPXeq9iq21TxMZ2zVeK+W0MFc2vVOaRUtkDT8o1EBD3QZg2auDCH-X2tudU3U+osNppDEi19LLb1ptlUqsGKqg0iZ6GqmeRHcUvqk7Mz95GAP9KJVRntQjnR5oLWiAQo7gOKaGIayTImkOCZ6Ex4NjbAkWeCc20zaaxNWQU4p8xHbrFars8p79FH1P9uo5m7Tg7h36ZLYZxToGjOgQsy8KdablTmstfB31tqOOOudoJkMJz8AmTs6x1L7GItSdDYpiNBK-PRurVJ+NFXVMDJTdVkT7ifPIr8-q0AQWdNDr0wZpraaK1+arXZ2tUmrMNro-FibkDoEoAPa2Y96CSEYDLSGVrP6-00bLSwV9V6LPCak85wQrmRPycc8G9b7WNM0fOx6rjtTblIawZd+r-nf3UedIaRet3ZXmZE1B3brrTmwmvSJgre75tHp+yy0rInytRuVcM-rwbatisfdHJHdmWtkd869jrn3kcesG694binRthoB9NhVDnW2I-baNOT3bQAvd0ZRgLuFx0lIYwt6teaF2KDSuqVdZZoIbpSlu0c10JK3SbjJNSpkLi3M3ccRXSTwxRnAAivsFx1lzPQrc0LEzezTv1xEvha4hHUtpQAJUkEgFRGyQym2uPL8HiHaO24UNBtgquT0QkzaF4tlu0M27tw72VIY3f+s9Chq3GGGW64jycWXNx5egRRJ7pAVmzBNn2J+ZgstCa5B945NSGMuwmp97czNceWzddr5n8PSe8xq5SaAKP+7PSxqdyn2Ervktsc7y8Q9Ge7fjbYM7+XwNM-Z9N37zrwf0N14t9QBvYe+Hd5bLc5JkZ28D8K0P1byfoSp6zB36CI-QAz+23v71KWIcx4iahpfmHE-Bp7yfvvWZ09X7H3enPygeecQBehMAATCXr3OXuTiylXmboOrXtpsECvmvgoE3uelvqMnpner2LHiHvHrxu-sfs3C7t-qPl7q+gAewEASATcF-BAWXtGNAbKrAfPgHr1hviJpHvvg-otl3M-rSq-llnSoJpQdQUwIXjcK-PQX8FARQXPugjvlGOfl3lJlwXfoPhfjriIfIV3GwbYPphwaobfruu7rgS-gnnZiGDFkZqIfnuIYTO-NIZgLIYprYcAfYTcD-E4QFBXmGiwegr5NgRAP-joS9MLu3ONiyiGMBFeBgOBJBJoW-tZmZIAXYRIbCE-N4VAaOBGJqDKJBEdGqAsjggwvQBCkWLblEAIEwA8LygYNqNxgaO0L7ugs7uSKLqIKUrcpPlmMDBcKSi8E0EpBjCiO4hcCiEATgvMkQlkPNGanaLvoTJQBQFQGUKwmUDMaIPQFEDEDaGgBFLEFQITGuBIGgMAUgE0GUGuBsfYKADsbEL6goMhMcPseRGuFaGgK0LcfcXsbgMoFZC8QcUgGuAkjuBgE0FsRYE0JXDwPBqQGcDnoEOaI4ioGhB2F2CiBEGdNNOwEgMUVoKwkaKFkQhQIaFkBYBYHMdCbxLCb6jOAIIEFibbDWHiRUhgO0isVUgGBgBZAjEwFOhSYKVVLSfCQyUyTiayYshyTQOEEKfQNNKdAILFDSdwHCfSYydiSyfiTGkKR4O0BSUpJCS0LcVSQsVGI8UgM8QAIQrGjCairi8mtIbH6JClWj-GCCBAWnITSmTGmhCkKlnRMSSi3HrD0ChmgABlKmvRhBAA)

Unfortunately, Stackblitz seems to be having issues with the TypeScript in my DateInput.svelte component. So here's a screenshot of the error, the schema, and the component code.

![CleanShot 2024-02-24 at 08 11 01@2x](https://github.com/ciscoheat/sveltekit-superforms/assets/5138384/ec4861c4-d634-4f62-a4f5-f7277ecd2ee5)

```ts
export const logSchema = object({
	id: nullish(string(), ""),
	name: string([minLength(1)]),
	date: date(), // This is type Date in the inferred type
	characterId: optional(string(), ""),
	characterName: optional(string(), ""),
	type: optional(union([literal("game"), literal("nongame")]), "game"),
	experience: number([integer(), minValue(0)]),
	acp: number([integer(), minValue(0)]),
	tcp: number([integer()]),
	level: number([integer(), minValue(0)]),
	gold: number(),
	dtd: number([integer()]),
	dm: object({
		...dungeonMasterSchema.entries,
		name: optional(string(), "")
	}),
	is_dm_log: optional(boolean(), false),
	magic_items_gained: optional(array(itemSchema), []),
	magic_items_lost: optional(array(string([minLength(1)])), []),
	story_awards_gained: optional(array(itemSchema), []),
	story_awards_lost: optional(array(string([minLength(1)])), [])
});
```

```svelte
<script lang="ts" context="module">
	type TRec = Record<string, unknown>;
</script>

<script lang="ts" generics="T extends TRec">
	import type { HTMLInputAttributes } from "svelte/elements";
	import { dateProxy, formFieldProxy, type FormPathLeaves, type SuperForm } from "sveltekit-superforms";

	interface $$Props extends HTMLInputAttributes {
		superform: SuperForm<T, any>;
		field: FormPathLeaves<T, Date>;
		empty?: "null" | "undefined";
		minField?: FormPathLeaves<T>;
		maxField?: FormPathLeaves<T>;
	}

	export let superform: SuperForm<T, any>;
	export let field: FormPathLeaves<T, Date>;
	export let empty: "null" | "undefined" = "null";
	export let minField: FormPathLeaves<T, Date> | undefined = undefined;
	export let maxField: FormPathLeaves<T, Date> | undefined = undefined;
	export let description = "";

	const proxyDate = dateProxy(superform, field, { format: "datetime-local", empty });
	const proxyMinDate = minField ? dateProxy(superform, minField, { format: "datetime-local" }) : undefined;
	const proxyMaxDate = maxField ? dateProxy(superform, maxField, { format: "datetime-local" }) : undefined;

	const { errors, constraints } = formFieldProxy(superform, field);
</script>

<label for={field} class="label">
	<span class="label-text">
		<slot />
		{#if $constraints?.required || $$props.required}
			<span class="text-error">*</span>
		{/if}
	</span>
</label>
<input
	type="datetime-local"
	id={field}
	bind:value={$proxyDate}
	class="input input-bordered w-full focus:border-primary"
	aria-invalid={$errors ? "true" : undefined}
	min={$proxyMinDate}
	max={$proxyMaxDate}
	{...$constraints}
	{...$$restProps}
/>
{#if $errors?.length || description}
	<label for={field} class="label">
		{#if $errors?.length}
			<span class="label-text-alt text-error">{$errors[0]}</span>
		{:else}
			<span class="label-text-alt text-neutral-500">{description}</span>
		{/if}
	</label>
{/if}
```

**Comment by ciscoheat** [comment]
Fixed now with 2.6.2.
