### ISSUE TITLE
Feature Request: Pass options to use:enhance

### ISSUE THREAD

**Issue by ElijahJohnson5** [ciscoheat/sveltekit-superforms#37]
Hello,

Really enjoying using the library. I am having some trouble where I want to be able to create the form at the top level and pass it down to components that handle using it. However these components want to set the options like `onUpdate` or `onResult` so I just have to pass the validation down to the component and create the form there.

If there is a better way to handle this that I am missing let me know. It is also hard to pass the form/validation all the way down to where the form actually is in my components since it may be deep in a component.

**Comment by ciscoheat** [comment]
There is a `fields` property returned from `superForm` that arranges the form data as objects with separate `name`, `errors`, etc properties. It has some kinks though, but it version 0.6.0 it will be much improved.

The events I'm not sure what you mean exactly, you want to be able to add events after calling `superForm`? How does the default `enhance` handle it?

**Comment by ElijahJohnson5** [comment]
You are able to use enhance like 
```
use:enhance={() => {
  do something before submit
  return () => {
    do something with result  
  }
}
```
Currently with super form you have to pass those options into the `superForm` method which makes it a little more difficult. If instead I could pass options to the superForm enhance method that would be very nice

**Comment by ciscoheat** [comment]
Ah, good idea, will definitely implement that in a near release. Many of the options should be usable there. Any other options except the events that you may find interesting to use there?

**Comment by ElijahJohnson5** [comment]
I would think they would overwrite the options passed in the `superForm` but am open to either way

**Comment by ciscoheat** [comment]
I'm thinking about what would happen if the action is used in several places. Is that what you had in mind, btw? :) If so, I think event chaining would be the best option, it's too easy to cause surprises when calling it in several unrelated places, otherwise.

**Comment by ElijahJohnson5** [comment]
Yes multiple places is how I was/am using it. Chaining sounds good to me

**Comment by ciscoheat** [comment]
I think that will work fine, I'll start preparing that for the next release!

**Comment by ciscoheat** [comment]
@ElijahJohnson5 you should be able to pass events in `use:enhance` now:

```svelte
<form method="POST" use:enhance={{onUpdated: ({form}) => ... }}>
```

Can you check that it works?

**Comment by ElijahJohnson5** [comment]
Yes it works great! Thank you

**Comment by ciscoheat** [comment]
Nice, closing this then. :)
