### ISSUE TITLE
Version 2.6.2 breaks my SvelteKit app, causing infinite loading on localhost

### ISSUE THREAD

**Issue by maoosi** [ciscoheat/sveltekit-superforms#370]
I'm facing an issue with my SvelteKit app after updating `sveltekit-superforms` to version **2.6.2**. The Vite development server starts as expected, with no apparent errors in the console. However, when I try to access the local app URL, it results in an infinite loading state. Same goes when attempting to ping the URL using `curl`, so not a browser-related problem.

My Superforms implementation is pretty simple and uses the provided zod adapter. The app was running fine on SvelteKit version **2.5.2** before the update. Downgrading `sveltekit-superforms` back to **2.5.0** immediately fixes the issue, allowing for normal access to the application on localhost. This indicates that the problem is specifically related to the latest release.

There are no errors or warnings to provide any leads; the current behaviour makes me think the latest version of `sveltekit-superforms` is potentially creating a deadlock or infinite loop that prevents the application from completing its loading process.

I haven't tried reproducing the issue on a fresh SvelteKit installation yet; I'm first posting to see if anyone else might have encountered the same issue since upgrading.

**Comment by ciscoheat** [comment]
Please try to make a MRE, I'll take a closer look then.

**Comment by maoosi** [comment]
I haven't been able to reproduce the issue with a fresh SvelteKit installation yet. I'll update this later if I manage to do so.

However, the problem persists on my side even after updating to `2.8+`. So far, downgrading to `2.5.0` remains the only solution I've found.

**Comment by maoosi** [comment]
@ciscoheat I have finally found the issue!

I still had some v1 imports using `/client` and `/server`. Removing these and importing directly from `sveltekit-superforms` resolved the infinite loading issue.

Might be worth adding this to the [v2 migration guide](https://superforms.rocks/migration-v2)?

**Comment by ciscoheat** [comment]
Good find, added to the migration guide now.
