### ISSUE TITLE
Form gets cleared after submit.

### ISSUE THREAD

**Issue by jordanopos** [ciscoheat/sveltekit-superforms#372]
When I try to submit a form, SuperDebug shows that the form is actually being populated, but on submit, the form values are empty. this is the code.

[https://stackblitz.com/edit/superforms-2-testing-w24id1?file=src%2Froutes%2Fschema.ts,src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2F%2Bpage.server.ts,package.json](url)

**Comment by ciscoheat** [comment]
The repo doesn't work, can you fix it and I'll take a look.

**Comment by magick93** [comment]
HI @jordanopos 

I'm also having the same problem - and `SuperDebug` shows `200` and form values populated. 
Are you able to fix your example so I can see if it is the same issue?

**Comment by magick93** [comment]
Setting `dataType: 'json'` resolved it for me.
