### ISSUE TITLE
Support for schema references ($ref)

### ISSUE THREAD

**Issue by shellicar** [ciscoheat/sveltekit-superforms#374]
**Description**
I updated to superforms v2 and after migrating everything, started getting `TypeError: Cannot read properties of undefined`
I narrowed it down to an object being undefined.
It seems that using a zod schema multiple times breaks it.

**Reproducible**
[https://stackblitz.com/edit/superforms-2-testing-py3ity?file=src%2Froutes%2Fschema.ts](https://stackblitz.com/edit/superforms-2-testing-py3ity?file=src%2Froutes%2Fschema.ts)
> schema.ts
```ts
import { z } from 'zod';

const otherSchema1 = z.string();
const otherSchema2 = z.object({
  value: z.string()
});

export const schema = z.object({
  obj1: otherSchema1,
  obj2: otherSchema1,

  obj3: otherSchema2,
  obj4: otherSchema2,
});
```

```
200
{
  obj1: "",
  obj2: undefined,
  obj3: {
    value: ""
  },
  obj4: undefined
}
```

**Comment by ciscoheat** [comment]
There's no support for schema references yet, so you have to clone the schema to use it like this.

**Comment by shellicar** [comment]
Are there other features that aren't supported in v2?
I've tried upgrading a medium sized project a couple of times and keep running into issues.

**Comment by ciscoheat** [comment]
This should be the biggest issue, cannot think of anything else. But if you find anything else, please open a separate issue about that.

**Comment by ciscoheat** [comment]
You could try to configure the JSON Schema generation for the adapter now with 2.11.0:

```ts
const form = await superValidate(zod(schema, { config: { ... }}));
```

The [$refStrategy](https://github.com/StefanTerdell/zod-to-json-schema?tab=readme-ov-file#options-object) option could perhaps be useful until refs are supported by Superforms.

**Comment by ciscoheat** [comment]
Added now with 2.12.6
