### ISSUE TITLE
Target attribute not supported on <form> with use:enhance

### ISSUE THREAD

**Issue by McAndze** [ciscoheat/sveltekit-superforms#375]
Hi, thank you for this cool tool. I'd like to use it in a widget that's embedded in an iFrame. In this case, I want the redirect to target `_top` such that the top window container is what navigates when receiving the redirect.

I was unable to find anything regarding the expected behaviour here, so forgive me if this should be more of a feature request than a bug. 

**Description**
When using `use:enhance`, the `target` attribute of the `<form>` is not respected. This makes the behaviour different to non-JS users.

**If applicable, a MRE**
I have modified the tutorial example a bit to throw a redirect and set a `target="_blank"` on the `<form>`. No matter what you set the target to, the redirect will be opened inside the preview. When removing `use:enhance`, the redirect opens in a new tab as expected.

https://stackblitz.com/edit/sveltekit-superforms-1-tutorial-15p547?file=src%2Froutes%2F%2Bpage.svelte

I realize I could probably tap into something like `onResult` and achieve this behaviour, but it seems generally desirable to use the same behaviour as the non-enhanced redirect behaviour.

**Comment by ciscoheat** [comment]
Closing, as this seems to be a SvelteKit issue (as it doesn't work with the built-in enhance as well). An issue is opened here: https://github.com/sveltejs/kit/issues/11931
