### ISSUE TITLE
Superdebug collapsed too much when without label

### ISSUE THREAD

**Issue by cycle4passion** [ciscoheat/sveltekit-superforms#376]
Superdebug Component Layout Change

Appearance with label prop via `<SuperDebug label="Account form" data={$form} collapsible={true} collapsed={true} />`. As is this looks ok:
<img width="850" alt="Screenshot 2024-03-05 at 2 49 39 PM" src="https://github.com/ciscoheat/sveltekit-superforms/assets/6192217/654f2e7a-72bb-43d6-9cb5-8e8da7904aae">

Appearance without label prop via `<SuperDebug data={$form} collapsible={true} collapsed={true} />`. Now without the label, the status code is shown partially.
<img width="848" alt="Screenshot 2024-03-05 at 2 48 54 PM" src="https://github.com/ciscoheat/sveltekit-superforms/assets/6192217/b5013551-6f49-43c8-8957-aa9df6456cec">

Expected  behavior: layout is the same regardless if label props is true or false

**Comment by ciscoheat** [comment]
Fixed now in 2.8.1 (and a copy button added as well!)

**Comment by cycle4passion** [comment]
still looks funny if label is missing.

<img width="815" alt="Screenshot 2024-03-07 at 6 06 28 PM" src="https://github.com/ciscoheat/sveltekit-superforms/assets/6192217/c4e031db-9719-4459-82bb-98e6427d1f0e">

**Comment by ciscoheat** [comment]
Must be something with your specific css then, I've tested it with three different css frameworks, unstyled and normalized, and it was fine. If you can find a fix, let me know.

**Comment by cycle4passion** [comment]
Using SkeletonUI. here's a Stackblitz. Looks the same in Chrome, and Firefox.

**Comment by ciscoheat** [comment]
Global css leakage... Hopefully will be fixed in the next release. And there won't be a slide transition, it's incredibly complicated to do with arbitrary height. (It's just a debug component anyway)

**Comment by ciscoheat** [comment]
Try again now with 2.9.0

**Comment by ciscoheat** [comment]
Seems to work in my tests with the same repo. Let me know if you still have problems.
