### ISSUE TITLE
SuperForms doesn't quite support input names including `.` (setError(), splitPath())

### ISSUE THREAD

**Issue by Leftium** [ciscoheat/sveltekit-superforms#377]
- [x] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
Bug: input (path) names with `.` always treated as nested objects; input names cannot include `.`

Expected: input (path) names with `.` should match even if not nested; input names should be able to include `.`

**If applicable, a MRE**

https://stackblitz.com/edit/superforms-2-testing-tzpke3?file=src%2Froutes%2F%2Bpage.server.ts

In the screenshot below, `Error from setError` is not rendered next to the input with name `user.email` because `setError()` assumes paths with `.` are nested objects.
- However `dataType` is not `'json'`
- If all instances of `user.email` are changed to `email,` setError() error is rendered as expected.

![image](https://github.com/ciscoheat/sveltekit-superforms/assets/381217/0b27bd77-c2cf-4646-9e5e-3d02099c9086)

----

**Why `.` is needed in input names:**

- Non-nested, non-object forms:
  - work without JS
  - slightly easier to work with
- However the input names reflect a nested structure that has been flattened:
  - For simple unflattening on the server, etc.
  - https://www.npmjs.com/package/flat#unflattenoriginal-options
  - [Lodash set/get/etc](https://lodash.com/docs/4.17.15#get)
  - Convention used by Felte

**Workaround:**
- Use another character like `-` instead of `.` in input names
- Convert input names to paths with `.` before passing to other API's like Lodash get()

**Comment by ciscoheat** [comment]
This cannot be implemented, as the whole nested data functionality (FormPathLeaves, proxies, the validate method, get/set in onChange, etc) depends on dot path access, as in normal JS syntax. You have to use another character, or add the errors manually and keep the form without proxies and non-nested data.
