### ISSUE TITLE
Support for "raw" JSON schema

### ISSUE THREAD

**Issue by Leftium** [ciscoheat/sveltekit-superforms#378]
**Is your feature request related to a problem? Please describe.**
SuperForms uses JSON schema internally, but there is no way to pass SuperForms a "raw" JSON schema.

"Raw" JSON schemas are useful for two use cases:

- Persisting/loading schemas from a database
- Dynamically changing schema at run-time. For example:
  -  A comment field that is only required if the optional parent (radio) input has a value.

**Describe the solution you'd like**
A JSON schema adapter like:

 `import { jsonschema } from 'sveltekit-superforms/adapters'`

**Describe alternatives you've considered**
- Using ajv to validate with JSON schema outside SuperForms, then manually syncing SuperForms via `setError()`/`$errors`
- TypeBox can export JSON schema, but cannot import JSON schema (https://github.com/sinclairzx81/typebox/discussions/421)

**Additional context**
Related discussion: https://discord.com/channels/1088090866649939990/1201800301607399515

**Comment by ciscoheat** [comment]
As this is very complicated, making ajv work with ESM and moduleResolution is the best bet. Could need some help with that.

**Comment by Leftium** [comment]
Ah, since SuperForms uses JSON schema internally, I thought a `jsonschema` adapter wouldn't be difficult to add... (I looked at the SuperForms code myself, but wasn't sure how to do it.)

> making ajv work with ESM and moduleResolution is the best bet. Could need some help with that.

I'd like to help, but I'm not sure what the problem is:
- Does SuperForms fail to compile if ajv is included?
  - I'm using ajv in my SvelteKit project without issue
- Is it just the bundle size because code-shaking is not possible?
  - If it's just the bundle size, is it possible to split the ajv adapter from the rest of the package so the bundle size only affects ajv users? I think ajv support with a larger bundle size would be preferrable to no support at all.

Also there seem to be [several other JSON schema libraries](https://json-schema.org/implementations#validators-javascript) listed since I last investigated. Could adapters be added for any of those? Like Hyperjump JSV or djv?

---

Also, I did get formdata validation with ajv working outside of SuperForms (in real-time onchange events on the client). I'm just having trouble updating SuperForms `$errors` with the validation errors on the client side. I've only managed to get it to work inside the `onUpdate()` event (in SPA mode).

**Comment by ciscoheat** [comment]
Since it's not tree-shakable (by not being ESM-compatible), it's basically included as long as it exists in the project as a dependency, no matter what library you're using. So I can't really add it until it's thoroughly fixed in the library itself.

Hyperjump looks nice, and seems modern, so it looks like a candidate. Basically any adapter can be used as a base, but typebox could be suitable. Type inference is probably not available in Hyperjump, but you could use [json-schema-to-ts](https://www.npmjs.com/package/json-schema-to-ts) for that, if it's tree-shakable. X) It can be a bit slow though, in my tests.

**Comment by ciscoheat** [comment]
https://github.com/vitalics/ajv-ts is another alternative.

**Comment by ciscoheat** [comment]
Maybe not, it seems to require ajv under the hood.

**Comment by AKuederle** [comment]
I am currently trying to implement something similar @Leftium. Basically, I building support for a form builder that defines its fields using json-schema directly. Having the option to directly pass "raw" JSON schema to superforms (or first class support a validation library that supports it) would be amazing! (Just wanted to add my +1 to this)

@Leftium would it be possible to share the workaround using ajv manually? Thanks in advance!

**Comment by Leftium** [comment]
@AKuederle 

0. Use a very minimal, basic, generic schema to satisfy SuperForms.
1. Get any errors from `const validate = ajv.compile(schema); validate(data)`
2. Format and feed these errors to SuperForms [`setError()`](https://superforms.rocks/api#seterrorform-field-error-options)

Note I got this to work with SuperForms SPA mode after submitting the form (in one of the events).
- I couldn't get real-time validation to work. I couldn't see any "hooks" I could use where `setError` was available.
- The `$errors` store is writeable, but updating it didn't seem to work well (my updates were either overwritten or ignored).
- I did not try with form actions.

My feature that required ajv + dynamic json-schema ended up being dropped. Otherwise I would have probably just rendered the validation errors manually myself and not used SuperForms for validation.

**Comment by ciscoheat** [comment]
Yes, here's the version before it was removed: https://github.com/ciscoheat/sveltekit-superforms/blob/bd221dd44fa41dadd30965d050975eee067191df/src/lib/adapters/ajv.ts

**Comment by ciscoheat** [comment]
The Typebox adapter (latest version) should be useful for making it use the latest interface and helpers: https://github.com/ciscoheat/sveltekit-superforms/blob/main/src/lib/adapters/typebox.ts

**Comment by sukeshpabolu** [comment]
so, which adapter can we use for json schema validation?

**Comment by ciscoheat** [comment]
Just found https://github.com/sagold/json-schema-library which looks promising, but I don't know about any details.

**Comment by noobmaster19** [comment]
Hi, am facing a roadblock on this issue as well. Any help needed to implement this?

**Comment by ciscoheat** [comment]
It's ready to merge, just need to find the time.

**Comment by ciscoheat** [comment]
Here is the validator being used, btw; https://github.com/ExodusMovement/schemasafe

**Comment by ciscoheat** [comment]
Added now with 2.13.0: https://superforms.rocks/get-started/json-schema
