### ISSUE TITLE
isTainted does not allow to validate the entire form

### ISSUE THREAD

**Issue by mpost** [ciscoheat/sveltekit-superforms#379]
Starting with superforms [v2.7.0](https://github.com/ciscoheat/sveltekit-superforms/releases/tag/v2.7.0) it is not possible to validate the entire form using `isTainted($tainted)`. The error is:

```ts
Error: Argument of type 'TaintedFields<T> | undefined' is not assignable to parameter of type '(T extends T ? boolean | TaintedFields<T> | FormPath<T> : never) | undefined'.
  Type 'TaintedFields<T>' is not assignable to type 'T extends T ? boolean | TaintedFields<T> | FormPath<T> : never'. (ts)
```

I would expect to get a boolean result informing of the validity of the entire form.

**Comment by ciscoheat** [comment]
It works at runtime, right? (just a type error)

**Comment by mpost** [comment]
Sorry, i had incorrectly setup npm dependencies. (cashing issue). Closing as "works as intended"

**Comment by mpost** [comment]
...or maybe not. i don't trust my local setup. anymore. 😆 Could you verify `isTainted($tainted)`?

**Comment by ciscoheat** [comment]
Seems to work fine for me, and no type error.
