### ISSUE TITLE
Support for Valibot schema: instance

### ISSUE THREAD

**Issue by saturnonearth** [ciscoheat/sveltekit-superforms#380]
**Is your feature request related to a problem? Please describe.**
Valibot supports `Instance`, it would be nice if the Superforms Valibot adapter did as well :) 

**Additional context**
https://valibot.dev/api/instance/

**Comment by ciscoheat** [comment]
There's a PR at https://github.com/gcornut/valibot-json-schema/pull/18 for this.

**Comment by ciscoheat** [comment]
Thanks to a great "custom conversion" addition to that library, it will be supported in the next release.

**Comment by ciscoheat** [comment]
Fixed with 2.10.5
