### ISSUE TITLE
Not able to use adapters from sveltekit-superforms

### ISSUE THREAD

**Issue by ymansfarroll** [ciscoheat/sveltekit-superforms#384]
I'm just able to use /client and /server but not adapters form sveltekit-superforms. 

- Cannot find module 'sveltekit-superforms/adapters' or its corresponding type declarations.

**Comment by ciscoheat** [comment]
Sounds like you have v1 installed, or its types are stuck after package updates. Did you try to delete node_modules, reinstall them and restart VS Code?

**Comment by ymansfarroll** [comment]
It did work, it seems that yarn get stuck weeks ago and I didn't realize at all. Thanks a lot.
