### ISSUE TITLE
Client side validation with zod: Errors don't get cleared when using 'regex' and 'optional' together

### ISSUE THREAD

**Issue by fabian-michael** [ciscoheat/sveltekit-superforms#389]
**Description**
Once you inserted an invalid value into a field with `regex` and `optional` in the schema, the error does not get cleared when you empty the field and thus the form is invalid until you insert a valid value.

**If applicable, a MRE**

https://stackblitz.com/edit/superforms-2-testing-dmk3cn?file=src%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment]
An empty field is the same as an empty string. Use a stringProxy to set it to undefined when empty: https://stackblitz.com/edit/superforms-2-testing-ns3m6n?file=src%2Froutes%2F%2Bpage.svelte

**Comment by fabian-michael** [comment]
Shouldn't that be the default, when using optional?

**Comment by ciscoheat** [comment]
There is no way to make it default if you use `bind:value`, as it will bind to the input field value, which is an empty string when empty.
