### ISSUE TITLE
Superforms hangs vite dev

### ISSUE THREAD

**Issue by ktarmyshov** [ciscoheat/sveltekit-superforms#390]
- [X] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
A clear and concise description of what the bug is, and, unless obvious, what you expected instead.
My App is getting more complicated and it seems that the vite dev hangs in superforms converter regularly. I even found a function cal to which I can comment and it will work out. I have 2 more similar function calls elsewhere - but 3rd one kills the vite dev.

**If applicable, a MRE**
Use one of these stackblitz templates to create a minimal reproducible example that you can link to here:
I would love to build something similar, but I don't know if similar conditions are possible to build

- [Zod](https://stackblitz.com/edit/superforms-2-testing?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte)
- [Valibot](https://stackblitz.com/edit/superforms-2-testing-valibot?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte)

vite dev --debug log

  vite:import-analysis 0.22ms [1 imports rewritten] node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/string.js +9ms
  vite:transform 0.27ms /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/string.js +9ms
  vite:load 9.50ms [fs] /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/number.js +0ms
  vite:import-analysis 0.08ms [1 imports rewritten] node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/number.js +0ms
  vite:transform 0.11ms /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/number.js +0ms
  vite:load 9.63ms [fs] /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/boolean.js +0ms
  vite:import-analysis 0.06ms [1 imports rewritten] node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/boolean.js +0ms
  vite:transform 0.08ms /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/boolean.js +0ms
  vite:load 9.75ms [fs] /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/date.js +0ms
  vite:import-analysis 0.06ms [1 imports rewritten] node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/date.js +0ms
  vite:transform 0.09ms /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/date.js +0ms
  vite:load 9.86ms [fs] /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/array.js +0ms
  vite:import-analysis 0.06ms [1 imports rewritten] node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/array.js +0ms
  vite:transform 0.08ms /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/array.js +0ms
  vite:load 9.97ms [fs] /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/object.js +0ms
  vite:import-analysis 0.06ms [1 imports rewritten] node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/object.js +0ms
  vite:transform 0.08ms /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/object.js +0ms
  vite:load 10.07ms [fs] /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/tuple.js +0ms
  vite:import-analysis 0.07ms [1 imports rewritten] node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/tuple.js +1ms
  vite:transform 0.09ms /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/tuple.js +1ms
  vite:load 10.19ms [fs] /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/mixed.js +1ms
  vite:import-analysis 0.05ms [1 imports rewritten] node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/mixed.js +0ms
  vite:transform 0.08ms /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/mixed.js +0ms
  vite:load 10.29ms [fs] /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/lazy.js +0ms
  vite:import-analysis 0.06ms [1 imports rewritten] node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/lazy.js +0ms
  vite:transform 0.08ms /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/lazy.js +0ms
  vite:load 4.16ms [fs] /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/common.js +3ms
  vite:import-analysis 0.01ms [no imports] node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/common.js +3ms
  vite:transform 0.06ms /node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/common.js +3ms

**Comment by ktarmyshov** [comment]
Minor update, if I comment the call to that particular function, and run dev without it and once chrome loads the page uncomment the function again and refresh -- all works fine. But as soon as I restart it - hangs again at the same place.

**Comment by ciscoheat** [comment]
Does it hang when it processes the `yup-to-json-schema` files? If you can reproduce it in a repo, I can take a closer look.

**Comment by ktarmyshov** [comment]
This issue never appeared any more, so closing
