### ISSUE TITLE
Using validators in +page.svelte with Async Validation, i.e., checking if email exisits is causing problem

### ISSUE THREAD

**Issue by akashlama1998-icloud** [ciscoheat/sveltekit-superforms#392]
- [x] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
I'm trying to use validators in +page.svelte with the Async Validation, i.e., checking if email exisits is causing problem. The default validations is overriding the errors set in onUpdated. Please check this sveltelabs [link](https://www.sveltelab.dev/adllb80c3e2ki2n?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte)

**Comment by ciscoheat** [comment]
What are the steps to reproduce the problem?

**Comment by akashlama1998-icloud** [comment]
1. Follow the [How to make a debounced "username available" check.](https://sveltelab.dev/github.com/ciscoheat/superforms-examples/tree/username-available-zod) example from the [SvelteKit Superforms Examples](https://superforms.rocks/examples) page.
2. In line 7 and 8 add the imports

    ```js
    import { schema } from './schema.js';
    import { zodClient } from "sveltekit-superforms/adapters";
    ```
3. In line 13 add this line `validators: zodClient(schema),`

    ```js
    const { form, errors, message, enhance } = superForm(data.form, {
      validators: zodClient(schema), // This line
      taintedMessage: null
    });
    ```

That's it.. basically the [How to make a debounced "username available" check.](https://sveltelab.dev/github.com/ciscoheat/superforms-examples/tree/username-available-zod) doesn't seem to use any client side validation.. and I have a requirement to use both client side validation with async validation as shown in the example and I couldn't figure it out how to do it. Can you please help me.

**Comment by akashlama1998-icloud** [comment]
Can you please give me a solution on what should I do if I want both check username validation with client validation.

**Comment by ciscoheat** [comment]
Make a separate variable for the username errors and assign to it instead of $errors.username.

**Comment by akashlama1998-icloud** [comment]
So that's the official way? Okay.. Thank you 🙏.
