### ISSUE TITLE
Error: Data returned from action inside /x is not serializable: Cannot stringify arbitrary non-POJOs When trying to upload file

### ISSUE THREAD

**Issue by tienpvse1** [ciscoheat/sveltekit-superforms#398]
- [x] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
I'm trying to implement file upload with Superforms, after post the form, my app throws an error:
```bash
Error: Data returned from action inside /x is not serializable: Cannot stringify arbitrary non-POJOs
```
Here's my implementation:
schema.ts
```typescript
//schema.ts
import { z } from 'zod';

export const schema = z.object({
	file: z
		.instanceof(File)
		.refine((f) => f.size < 100_000, 'Max 100 kB upload size.')
});

```
+page.server.ts
```typescript
//+page.server.ts
import { fail, message, superValidate } from 'sveltekit-superforms';
import type { PageServerLoad } from './$types';
import { zod } from 'sveltekit-superforms/adapters';
import { schema } from './schema';
import type { Actions } from '@sveltejs/kit';

export const load: PageServerLoad = async () => {
	const form = await superValidate(zod(schema));
	return { form };
};

export const actions: Actions = {
	async default({ request }) {
		const form = await superValidate(request, zod(schema));
		if (!form.valid) return fail(400, { form });
		return message(form, 'Posted OK!');
	}
};
```
+page.svelte
```svelte
<script lang="ts">
	import { superForm, fileProxy } from 'sveltekit-superforms';
	import { zodClient } from 'sveltekit-superforms/adapters';
	import { schema } from './schema';

	export let data;

	const { form, enhance, errors } = superForm(data.form, {
		validators: zodClient(schema), 
	});

	const file = fileProxy(form, 'file');
</script>

<form method="POST" enctype="multipart/form-data" use:enhance>
	<input type="file" name="file" accept="image/png, image/jpeg" bind:files={$file} />
	{#if $errors.file}<span>{$errors.file}</span>{/if}
	<button>Submit</button>
</form>

```
My packages version:
- sveltekit-superforms: 2.12.2
- @sveltejs/kit: 2.5.5
- svelte: 4.2.12
- zod: 3.22.4

**Comment by ciscoheat** [comment]
The `fail` function from Superforms should remove files. Can you check which object causes problems in what you return from fail?

**Comment by tienpvse1** [comment]
Hi @ciscoheat , I've just logged the form from the server side, which gives me the following output:
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/86212960/4339315c-572a-4457-bf4e-82dd6b15f611)
thanks for your reply!

**Comment by ciscoheat** [comment]
The above code works for me when testing. The only thing I can think of is if you're not importing `fail` from 'sveltekit-superforms' but from SvelteKit instead.

**Comment by tienpvse1** [comment]
Ok, this seems kinda weird, I switch to node version 20 and everything just works, but not for version 18.13.0
Thanks for your reply again :rocket: , I'm closing this issue now
