### ISSUE TITLE
Improve current validationMethod or add new one (oninput-after)

### ISSUE THREAD

**Issue by hankaguila** [ciscoheat/sveltekit-superforms#399]
Perhaps there's already a way to achieve this more "out-the-box" but I couldn't figure it out.

I'd like for form validation errors to clear the moment the value of the field in question changes after the invalid state was set.

Instead, I get this:

![current](https://github.com/ciscoheat/sveltekit-superforms/assets/95978910/48040dcb-e8b6-4473-86a4-047e0f3ced49)

But what I expect (higher user satisfaction IMO):

![expected](https://github.com/ciscoheat/sveltekit-superforms/assets/95978910/06c4b93f-26c9-44af-8628-ecd52c540510)

I'm achieving the later with the following, but it'd be great if I didn't have to type something like that for every form field:

```svelte
<script lang="ts">
  // imports ...

  export let loginValidated: SuperValidated<Infer<LoginValidation>>;

  const form = superForm(loginValidated, {
    validators: zodClient(loginValidation),
    validationMethod: "submit-only" // I have to set this for the below to work... oninput-after would be great here
  });

  const { form: fields, enhance, errors, constraints } = form;

  /* I have to add this to make it work as desired/expected */
  let count = 0;
  $: if ($fields.email && $errors.email) {
    if (count === 0) {
      count += 1;
    } else {
      $errors.email = undefined;
      count = 0;
    }
  }
</script>

<form method="POST" action="/?/login" use:enhance>
  <Form.Field {form} name="email">
    <Form.Control let:attrs>
      <Form.Label>Email</Form.Label>
      <Input
        {...attrs}
        bind:value={$fields.email}
        {...$constraints.email}
        aria-invalid={$errors.email ? "true" : undefined}
      />
    </Form.Control>
    <Form.FieldErrors />
  </Form.Field>
  <Form.Button>Submit</Form.Button>
</form>
```

Thank you.

**Comment by ciscoheat** [comment]
Experiment with the [validationMethod](https://superforms.rocks/concepts/client-validation#validationmethod) option. Superforms uses a "reward early, validate late" validation method, which is researched for a very high user satisfaction: https://medium.com/wdstack/inline-validation-in-forms-designing-the-experience-123fb34088ce

**Comment by ciscoheat** [comment]
It uses the validation schema after an error exists, so as long as the value is invalid (after an error), it will be displayed. It is researched to have a high user satisfaction: https://medium.com/wdstack/inline-validation-in-forms-designing-the-experience-123fb34088ce

**Comment by hankaguila** [comment]
Thanks for the info, but that's not what I asked. I did get the message though, I'll figure it out.

Nobody in my team agrees with this BTW; we're all in agreement that not resetting the error label upon edit is not in alignment with the design principle of feedback. I hardly believe we're the only ones.

Thanks again.

**Comment by ciscoheat** [comment]
I haven't done the research, so I cannot say much about it. :) Maybe you can add an `onChange` handler to simplify things.

**Comment by hankaguila** [comment]
Will do. Thanks for the tip 👍
