### ISSUE TITLE
Set multiple errors

### ISSUE THREAD

**Issue by jianyuan** [ciscoheat/sveltekit-superforms#400]
**Is your feature request related to a problem? Please describe.**
Currently, the `setError` method only allows setting a single error.

**Describe the solution you'd like**
I would like a `setErrors` method that allows setting multiple errors.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ciscoheat** [comment]
You can call it multiple times before returning, as stated in the docs: https://superforms.rocks/concepts/error-handling#seterror
