### ISSUE TITLE
Form resets by itself 3 seconds after onUpdated

### ISSUE THREAD

**Issue by rChaoz** [ciscoheat/sveltekit-superforms#403]
See here:

![autocomplete](https://github.com/ciscoheat/sveltekit-superforms/assets/8215371/0a56a929-e100-48c6-ad1a-b6ffecc9d2eb)

I've had it happen quite a few different times until I figured out what's happening. It's interesting to see that my textarea is also unfocused when this happens, maybe this can help narrow it down as SuperForms is calling `.focus()` on something.

Workaround:
```js
let inputValue = ""
$: $form.inputValue = inputValue
// replace every access to $form.inputValue with inputValue
```

**If applicable, a MRE**
I don't have one exactly now but I think it has something to do with my zod schema modifying the data using transformers.

**Comment by rChaoz** [comment]
Update: apparently `invalidateAll` being `true` by default might have caused this. Also, apparently `resetForm` is true by default! Why is this not in the docs?? Settings both to false fixed it, so strange..

**Comment by ciscoheat** [comment]
Here it is: https://superforms.rocks/concepts/enhance#modifying-the-useenhance-behavior
It's the SvelteKit default, that's why it's true as default.
