### ISSUE TITLE
v2.12.0 introduces out of memory (OOM) error when included in libarary built with svelte-package

### ISSUE THREAD

**Issue by hmnd** [ciscoheat/sveltekit-superforms#404]
- [x] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
As of v2.12.0, running `svelte-package` in a package containing the use of `FormPathLeaves` with a generic `T` param results in a memory leak and OOM error.

**If applicable, a MRE**
Run `npm run package` in the console [here](https://www.sveltelab.dev/x23zw5ay9aa1kxi)

**Comment by hmnd** [comment]
Woo! I'm issue #404!

**Comment by ciscoheat** [comment]
Will hopefully be fixed in the next release.

**Comment by ciscoheat** [comment]
See if it's working now with 2.12.4.

**Comment by hmnd** [comment]
@ciscoheat works perfectly now! Thank you so much for such a quick fix :)
