### ISSUE TITLE
Refine with Path creates nested error object.

### ISSUE THREAD

**Issue by GimpMaster** [ciscoheat/sveltekit-superforms#408]
**Description**
I was playing around with refine and the path as mentioned here in the docs

https://superforms.rocks/concepts/error-handling#setting-field-errors-with-refine

```
	.refine((data) => data.gpa == data.actScore, {
		message: 'Scores are not equal',
		path: ['gpa', 'actScore']
	});
```

Ignore what the refine is doing, obviously you wouldn't compare your gpa and actScore, but I was think that the error would be created on BOTH gpa and actScore inputs. However it nested the errors.

As in the picture below

![image](https://github.com/ciscoheat/sveltekit-superforms/assets/7818200/84179973-2176-4fe4-a128-d578215524ce)

I was hoping it would create errors on both the inputs?

If you needed nested capability wouldn't the path be something like 

`path: ['gpa/nested/one']`

Or is this a zod thing?

**Comment by ciscoheat** [comment]
The path is the splitted path to the error that you want to set, in your case `gpa.actScore`. You need multiple refines to set an error on both properties.

**Comment by GimpMaster** [comment]
Thanks. I figured as much. I also saw another post about having to manually taint both inputs.
