### ISSUE TITLE
how to set additional header data when we submit the form ?

### ISSUE THREAD

**Issue by amarezenebe** [ciscoheat/sveltekit-superforms#410]
i want to set additional header data when i submit the form
    //                 method: 'POST',
             mode: 'cors',
                 **headers: {
                        'Content-Type': 'application/json',
                         'x-csrftoken': csrfcookie()
                }
                credentials: 'include',**

**Comment by ciscoheat** [comment]
Superforms uses the [SubmitFunction](https://kit.svelte.dev/docs/types#public-types-submitfunction) from SvelteKit in `onSubmit`, so I don't think this is possible. Extra data can be sent with formData or in the action URL instead.

**Comment by ciscoheat** [comment]
This is possible now with [customRequest](https://superforms.rocks/concepts/events#customrequest)!
