### ISSUE TITLE
Validation doesn't work with different pages

### ISSUE THREAD

**Issue by falkomerr** [ciscoheat/sveltekit-superforms#414]
Validation does not work if you add a page other than the current page as form action.

I needed this to integrate forms with shallow routing, in the root layout.server I return

![image](https://github.com/ciscoheat/sveltekit-superforms/assets/105551615/24216198-a231-447e-ac88-e1700f9e030b)

then in this layout I render the modals by $page.state

form actions cannot be placed in layout.server.ts, so I put them in separate pages, as a result of which I needed to specify as action for the form not the current page.
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/105551615/5d46ea78-23a1-45d0-befd-3fb4ad3553b4)

the form action itself is triggered, but the result from it is not returned back to the form component

reproduction: https://www.sveltelab.dev/e3cs398dnxd4y7k

**Comment by ciscoheat** [comment]
Cannot reproduce this, when I console.log(form) in the event, it shows up as it should.
