### ISSUE TITLE
New Adapter: @effect/schema

### ISSUE THREAD

**Issue by geekodour** [ciscoheat/sveltekit-superforms#415]
Can we consider supporting https://github.com/Effect-TS/effect/tree/main/packages/schema ? If it looks like something we can support, willing to work on it!

**Comment by ciscoheat** [comment]
Of course, check one of the existing adapters to get started: https://github.com/ciscoheat/sveltekit-superforms/tree/main/src/lib/adapters

**Comment by ciscoheat** [comment]
A test suite should be added here: https://github.com/ciscoheat/sveltekit-superforms/blob/main/src/tests/superValidate.test.ts#L140

**Comment by geekodour** [comment]
great! thanks. will keep things posted here as I work on it!

**Comment by jkonowitch** [comment]
@geekodour Are you still planning to implement this adapter?

**Comment by geekodour** [comment]
@jkonowitch apologies for not keeping up. Please feel free to take this forward. Otherwise I do still plan to write this out if this doesn't go out as soon as I get back on working related projects.

**Comment by szethh** [comment]
hi there, I started work on this. will open a pr later today/tomorrow
