### ISSUE TITLE
How to set an error during onSubmit()

### ISSUE THREAD

**Issue by thobson** [ciscoheat/sveltekit-superforms#417]
I need to intercept the form submission and perform some work in `onSubmit`. This could result in a form or field level error.

I tried using `setError` on the client but this doesn't work because it expects `SuperValidated` but I have a `SuperForm` or `SuperFormData`. So what I'm currently doing is mutating the error store:

```typescript
const form = superForm(data.form, {
  onSubmit: async ({ formData, cancel }) => {
    // do stuff
    form.errors.update(errors => ({ ...errors, email: ['invalid email'] }))
    cancel()
  }
})
```

Are there any issues with doing it this way? Is there a better way?

Many thanks

**Comment by ciscoheat** [comment]
That works fine, you can also assign it directly, if you deconstruct the errors store:

```ts
const { form, errors, enhance } = superForm(...);

$errors.email = ['invalid email'];
```
