### ISSUE TITLE
Two forms in same page.  When a submit the form 2, data returned in form 1 is cleared.

### ISSUE THREAD

**Issue by Kevin170597** [ciscoheat/sveltekit-superforms#419]
Sorry if is not a bug.

I'm returning data after submitting a form as [docs](https://superforms.rocks/faq#from-a-form-action).

I have two forms in same page. The problem is when a submit the second form, data returned after first submitted form is cleared.

**Comment by ciscoheat** [comment]
Check the use:enhance options: https://superforms.rocks/concepts/enhance
