### ISSUE TITLE
ReferenceError: structuredClone is not defined

### ISSUE THREAD

**Issue by wody** [ciscoheat/sveltekit-superforms#42]
Since v0.6.0 I get the error (in Node v16)

ReferenceError: structuredClone is not defined

as the structuredClone call was alled - but that is only supported in Node v17+ as far as I see it.
https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility

**Comment by ciscoheat** [comment]
Yes, a fix is underway in a few moments.

**Comment by wody** [comment]
Yes that's working fine for me now. Thanks a lot for that super fast fix.

**Comment by ciscoheat** [comment]
No problem :)
