### ISSUE TITLE
Error with use:enhance when using on Safari IOS 13.6

### ISSUE THREAD

**Issue by asenta2812** [ciscoheat/sveltekit-superforms#427]
- [x] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
Device OS: **Safari IOS 13.6**
Repo: https://github.com/ciscoheat/superforms-examples/tree/components-zod
I got an error with `use:enhance` when using Safari IOS 13.6, causing the form to not be validated or submitted.

![Screenshot 2024-05-08 at 14 43 41](https://github.com/ciscoheat/sveltekit-superforms/assets/52541823/17a47d4b-76ba-4ae4-9440-ebd851f89735)

**Comment by ciscoheat** [comment]
I need to know where it crashes, so if you can debug in the browser, that would be great.

**Comment by asenta2812** [comment]
This bug only occurs when I build the project, so when it fails, I don't know exactly which file it is in.

**Comment by ciscoheat** [comment]
Can you break on unhandled errors and trace it back to the Superforms code?
