### ISSUE TITLE
SuperDebug CSS is included in SSR-only production build

### ISSUE THREAD

**Issue by verydanny** [ciscoheat/sveltekit-superforms#433]
**Description**

Super Debug CSS is included in production. My login form is going to be SSR-only, (CSR is false), so there should be no need to load css. I'm also not importing SuperDebug anywhere.

Should there be a `superForm` for server-only applications? Maybe this is configuration issue I missed? 

Example Repo: https://github.com/verydanny/idea-one/tree/main/app

![image](https://github.com/ciscoheat/sveltekit-superforms/assets/13333822/aad6537a-1ff8-4bef-b22c-3e4c108f1da9)

**Comment by ciscoheat** [comment]
As mentioned in the other issue, does it work if you import it from there?

```ts
import SuperDebug from 'sveltekit-superforms/client/SuperDebug.svelte'
```

**Comment by verydanny** [comment]
That's not the issue, if one does `import { superForm } from 'sveltekit-superforms'` it automatically imports `SuperDebug`'s CSS because rollup/vite can't treeshake CSS. The library file structure just needs a small edit, pretty simple. 

Honestly I'm more for creating a `superFormServer` because I try to keep my client code as small as possible. The current `superForm` is actually a little chunky. Here's my bundle before using `superForm` on client code vs. after:

Before:
![IMG_5524](https://github.com/ciscoheat/sveltekit-superforms/assets/13333822/a59bc6a7-c855-4a53-9200-c8732c15e1d7)

After:
![IMG_4954](https://github.com/ciscoheat/sveltekit-superforms/assets/13333822/518d7dcd-c53c-4261-be59-2903fbefe9b6)

This may not seem like a huge jump, but in some cases my route jumps 30% in size from a single library. When optimizing for really slow devices and networks, this is a bit painful.

**Comment by ciscoheat** [comment]
`superForm` isn't used on the server, so what did you have in mind for `superFormServer`?

I don't want to introduce a breaking change by moving the component, but I think the css can be fixed by inlining it, as most of its css is namespaced with the `super-debug` class. Feel free to make a PR if you like to contribute.

**Comment by verydanny** [comment]
@ciscoheat 

You would only be moving 2 lines. Just delete these 2 lines: 

https://github.com/ciscoheat/sveltekit-superforms/blob/d0b6fe45df43e2d6575535725666a38cf1c2312b/src/lib/index.ts#L1-L3

And then release a deprecation warning:

```ts
/**
 * @deprecated This import has been moved, instead import it from "sveltekit-superforms/superdebug"
 */
export const SuperDebug = () => {}
```

Or just release a `BREAKING CHANGE` changelog.

**Comment by ciscoheat** [comment]
@verydanny I've inlined the css, check if it's working now with v2.15.0. (No need to change any imports)
