### ISSUE TITLE
Use `customValidity` with `_errors`

### ISSUE THREAD

**Issue by macmillen** [ciscoheat/sveltekit-superforms#439]
**Is your feature request related to a problem? Please describe.**

I want to use the power of `customValidity` to not having to add more html to display my error messages.

``` ts
const schema = z.object({
  priceRules: z.array(
    z.object({
      priceCategory: z.object({
        value: z.string().min(1),
      }),
    }),
  ),
});
```

The problem is that I need to specify the name attribute for it to work.
``` html
<input type="text" name="priceRules[0].priceCategory" />
```

And because priceCategory is an object which gets an _errors object it doesn't trigger the customValidity tooltip.

**Describe the solution you'd like**
It would be nice if superforms could parse the `_errors` object and display a `customValidity` message.

**Describe alternatives you've considered**

**Additional context**
https://discord.com/channels/1088090866649939990/1245030280192987178

**Comment by ciscoheat** [comment]
Should be fixed now with v2.15.0, can you confirm that it is?

**Comment by macmillen** [comment]
@ciscoheat Thank you so much, it works perfectly! :rocket:

**Comment by macmillen** [comment]
@ciscoheat Thank you so much, it works perfectly! :rocket:
