### ISSUE TITLE
Cannot use `z.array()` as first-level schema

### ISSUE THREAD

**Issue by opack** [ciscoheat/sveltekit-superforms#442]
- [X] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
I try to use a schema to validate a simple array, but it fails if I don't wrap it in an object. Here is what does not work:
```typescript
const awardsSchema = z.array(
   z.object({
      id: z.string()
   })
)

const awards: Award[] = await awardsService.getAll()
const form = await superValidate(awards, zod(awardsSchema))
```
Causes a TS error on `awardsSchema`:
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/3687098/744bdc3e-a96c-437b-8f68-0442beaaa0ae)

But if I wrap the array inside an object, everything is fine:
```typescript
const awardsSchema = z.object({
   awards: z.array(
      z.object({
         id: z.string()
      })
   )
})

const awards: Award[] = await awardsService.getAll()
const form = await superValidate({ awards }, zod(awardsSchema))
```

I found that the issue #369 is kind of similar, although using the workaround that the OP did is not working in my situation.
I found nothing relative to this in the documentation.
I tried updating to v2.14.0 but no luck
I am left to think that maybe `ZodArray` is not a valid `ZodObjectTypes`, expected by `zod()` adapter?

Sorry if I missed something obvious 😅

**Comment by ciscoheat** [comment]
The validation schema wraps a single form as an object with properties, so you're correct, arrays cannot be used on top-level.
