### ISSUE TITLE
Submitting form with disabled field does not send field value

### ISSUE THREAD

**Issue by andonimichael** [ciscoheat/sveltekit-superforms#444]
**Description**

When pre-populating a form with data, any disabled form fields are not forwarded to the server in the POST request. This is a common use case e.g. when allowing users to edit their settings or profile, but not allowing them to edit their email address or primary key. Because the disabled field's value is not sent in the request, the schema fails to validate the POST request.

[Minimum Reproducible Example](https://www.sveltelab.dev/?files=.%2Fsrc%2Froutes%2F%2Bpage.server.ts#code=N4IgdApgzgNglgOwC5wOYIPYCcIgFygBmcMuBIAxhshMlPqANaIAm%2BIUAbhDEjwIYAjALQBXOAA5%2BIADQhBowoQhZ8AbQAsANhlaJMiQGYZATgCsB4wEYrOm1Zk2NjgAwOrLxx6-uXnjw7mriY%2Brv5WAOyu%2BgFeFt4aUSYxka7xLjF%2BrjKJOXZW8VaZvil2bjnpUR6FZTlVVgBMpkkhHklVLtblCWXu3jaZea594fraOU3ehsbjsTajQ3MNniYdrY3Rw9lTFoZNEV3W-TZezrF7rpMu6cVxMhcekydO900SnhH67zIRURrOF0%2BBg%2BUQuqy8-iyFwkIS0Fgk%2B0GNie4SuIQ0N1CJlaLj%2BdgagTWm2OTXB2Nc7VcXQcGOJJ3JbUWLnyhRG2wJzVOEKZKUCOI6AF0AL4iuSQWCIJBYChgCgAK3o5GIpAYlGofDoquYCDYeA43F4AhE4iksnkimUqjwmj%2BTQ0TQuWjOtkcHORWweDWMD2uwS8Tz6zp0Gk8hjO3QKxN98y8OjDORpOgiZUK4V6XPGWnqbMeaSpr1duztdo6fvsYS8HVus26y39oReNhZBa0Dk9XVMXPL3ZdZn0DxdjdSsX%2B2Rx7jrTa2MY84QsfYLJl8nZChnHdw8mVTsZkC8b5QZzxcOPXM6ycyh6PDK-u6yuKQ6XW3C6dO8afSufQsh-DhSewfSL8o23Kdcn3PkG2PMsI0hSFfFDK8x07Nd603St82qbk90jAZpwyN9yjAqxwwg7soI8U9%2BnPbpLxya8QlXO8uwjfIU2nYjbyQkwZno%2BtwSHQCuQXC4UNfKd31QiNv3WX9UJdWk5hw-DMJneT6lJepnUEl4UNHbwmLQmxHzzVT537Uk21hINXQ-djpOYv8dwUqTgO5KcUO4uikPdfiOJsbSOIiAzB2jZ5jjMgtGg7BiNzCzTTHXCQzjdDZYmEh0T0g8Iqw9RD9M7WIGSg8EJHTASTLCzx0t3TwNH0MxarGXjT0nQcOPBCJIUxWItFaVqyvCiqc0jaql042YcKKPDSly0xosLLz8sUhZqqirjTBSZ0%2BnWALnFWtrnQ6GlmrsmqcjGEIzAigd8kOrY9JWArjngrZ9tu9CLwKhoLAep6%2BluIdZNnU7RuXGK1vy8GXCubqXNB8a7WbXCLxm84GJ49amN8rT2L28zOP8rwAeUkKaQC2GQPkxzsY3CMATyx7wY2GnCcU5wgrktieznXd8Yhxmbx8%2BLWbp3mC1E6yJPdRT7P3RzQPJ1zVODdTOXKtmCYFvr0kF76uI7Rp5xxYVRXAVA4BQdBsDIIgSBttUaE1chtV1fUeD4GAhDESRpDkBQlBUdRMy%2BYwgiMN8wpI7ZnorQr0nWF6jKjICEiSB8TOU6i6kWSbidRwjKgq2oiI0hKKTVzo8KZYbBhrGuhntbJpmrtyprr10ViJaXM%2BXZHQvTcZDxzaGM5mMpmwmrnyJcqd%2BPIjZaUb44twIxMy%2B5y5R5zifWIzyiagrpjF6uE2hTFAAHHAkBQFQ0EwHBVWVe2qEdpBFSYVh2C4d2jW900-YtIHa0hgiw-EOK3QMHorgw2TncH0AYuTQg%2BF8EEXlAQoJ%2BKCUuZ5QxvFhPCRE0cUSSXRN1ek-JFgcjnjiJEzMWjlzntSCodJSK4iZEjSq7JCRdh6Cw9ebCPCnwvlfG%2BWBpSPztqqF%2BGo35ak-nqb%2BhpPbGh9maf2lp1D82QndEWDgkqcmSHAvGkUDofUIrxeMIsQKV0MuUCQfRsyr3uMYm6PCjqLUepY0xc8KZuUrlmSCmVwTxmql48Iw82zOF%2BquZ0TwgbHB0BIDo6Q0yuABC4u06IxhNSQl4%2B8Zinyt12Bk0wkS5JR3EiFXazDu7pw8IUmMClc7TScfGTy0TnENimhrOWscXIhPxmNNaIlwwwNsUBAZ4somI1innVpUSAQOi2pzIaRTOmrS9FMviwslKQMmSM2ZLTxLlHjJ6UBhs5rsnSEIkAAAlAAogAQQACIAFl7lgAALa6ltiqcg0jaCyOdvIt2SivYml9uaAOVo1AgJMYUVWPSR49nDDtGptZO5llSj3Wm2QERbDnv4DkTT8hkw%2BrsyKGLD6SQBpGeBXTFmlMsOSz8zEEH7jRe0yEks2pPAirkIiCLJKQNzCirFP13rliKvUH6a9BEijPiAc%2B-AKCMH4KgCAYAFTUAkX80AAKnYfx1F-A0HtwWqIAdCzRmz8phOpecEpXihXdxFciyO4r0UTkxRRGlp1aSGN8oJeMHSvG0pxipTh%2BylnnQbmMYMMSPHaPKRVfQvl0xRojjo8xuScY-gqv%2BIxYt2zrUsdRf66z8ahqLlAvp5bg0nTaXU6MmdQyOudCvY5bZSRNthq2xNMU8nMXLSpCMCbQnturecJ4cT2IdtHZ0jpCaipR2lRWrZrNuk0XzmSxkEa4x8pstyckIl%2Bx82aSjJx-qcQrooRcReB9CZDz8WMyud6VYR1lpw0Vzax6uA4WyetJbnDLoJRQ7CDF6g6BAxmp1RMjmk3RckncA54gpRWKuB0p74VwYvZ25hIHCq3rtD9B9kYn1nhfd6GZRFmzkaopR9hsUAPEZqVYCDO5oMLKA04jdcY204f7qddyXHIadNsZTPjRbo3Sz8ixAi1S70kf4Te8ub7xZYZ9CnTOEmCzjEA6J0t7LZPseE1JsTqVZN9F3iOvZLGmkyUnScmZ%2BmBZeJXammVHp%2BP1OrWCTaat9LXt00p0V7qfVpt0G2P44QKluu9dPBw2F0jLKHMGLtrpGWNG9bJo4oCmm4JyBh1j%2B6MKCYHO5gLQa0QV23C5m8g6k4i3SWZ0tDSXQDieJ5jwjL70V0yGe116Q2t9qWnrEN4Y4Jwb0OxVlOD2LoYzhMkpWiB3ODEuerdPHmR3FyISgLBaNb%2BvqJB0IMHgN7TXg1BuCbF2dPW4UOZeGPATw6Eh0z47TB7VqjoMwv6NBZIXQ2tb4bN0lC2y9gTD6C6%2BsazY0KtVCgPfg%2Bm-jJgLvXYx3V1buhJYpVm5GMCM9tOt0kx9tHu5gw-eMGYKJ8aY1Y6Tet-EtkZbr1k-LKmQnifK2zqz8TJPWP5Nh8NtdBzydXQx1d8YdVAfcaZ4el1dw80RoLc5LTHaEm87oTwhTqO9oSsK2daX-YROuYqUpDXqSzufYp0MX7u4Dcy4Zwmvn3PNdXq6ZCBjTSZ2KWs82vZevdx4kN8b2XBnze%2BJ5z7ukxkI0I8ObhhD1upc-cS7TmN%2BXpz9Ul2U27dqxXhZyipBorLB5osJtb8XlPM90%2Bd%2BZ33cnjm65a%2Bd3cl217-fD2b5Nfv5O40F7H0r24mlI6Tyj1vNuzCXe%2B7uaN%2Bfc2vfJcBkPh5Eei%2BjeTrv4x7dh-r7BvuYO8Mp7%2B3GzP1ivVOTp-bq7%2B%2BQePYQx77roHVNB%2Bn3bmvTvTf1fv8jvCb3OcN1EVRZQtXU0Uq8vtJc-sbsgcP1XJDEICjcfsM938783w8dTpldQoC1EDd8fsZl7c0C%2B4ocykyc9pf1U9DdUDv9sdiCeNJpSdK029t9kDY0xNHoLlxt0CWcTlvN55E5hwcUGdS1JtFc5tlp%2BFFYM0Vsk1Gh2UoQ38Z8kC592CvodYLl5VTYoBxFyAWA4AcAKAkBsAABPVUfgc%2Bc%2BMAFgMAIFX5Z%2BdUQFd%2BEAF2E1H%2BZRP%2BSFdRIBG0bOaEJhKdNJCOfIA9BcAVJfPdHOMfTbPDGsUQtuDocJNnH6E7KWbFCZb8RFbFbOXIelMVH0axIzVFALLmSNUuQxHsE7VxZ-V3dLePeg0ZAxfebYMtfhDzIdSlLoXkDaPrSKG1Dg-SLuGebXIqdLOEOSB0SYPom8MIylHTJFMo9cR0BzIcWzV0awPWUTGY-IgXeYxomtZMLEEzEmc5G1DYgWLYsZTXXYskRYt4eLJhabCLYJSY9YnWGKC4iqVJa4%2BhAI74RhLYcOWeFIpzNYhaTYv4LBT4%2BozeG4mtb4NCCLUA5iIrCGM4tQq5Zo7PVEBlZDF4haMwY2BVOQcwywgACyQE%2BRgF1XsNficJcIUVNV-ghTUUARhS0FDC6ESMPGZ2FUpUlmnn0C0CuF0G5QIhoUpTaLPGMFbHYIAzW2FNhFFMKgSN0AVM7HZOgis05DBCCxZgpSnBlK8WBJYzMEkzvSiCFPWg1P5zPEhPAk2ENNkjoz7R9GdFiyaEdPuC61BzpDKgEUE0Hm9ICmbEMAhJhPqBXmdJzmIR81ORLFVKtMhEoigztIGM1Mi3MznW2jkhFXa0ZSjKe0109JsBxBSQIjW0TgjEjPXHswzi%2BJcC422LPChwyM2FHzLjnluBlK7zjOzktIM29Ifz9IAJr2qIPBVNDKQg1MJxXRVP7Meg1PKKPCJVqKyCeL%2BHX0P19P-2rRj3tMMnpBVOcmyxTIzNLRSx9J0nlMTL6SRxQ24NgWLOok3OxUlI5FGgTh2JgjgPjEtMnI3SHJ3IiMHi6OBgkknOnJVIjUFLVMgu6LIhXITO8DguqJCnFPnJuVYAgAAA8bDoAkAbCnCn4pEHDDVnCQVFEzUVF-4oUNFrQR1gpcySthkrg4jP0nTqxMsAyuLL9FduTejzk3UUsoIRJ1gNcBoD4UICTMSwKXIsDvxqwEJYoiQqihi4xEI71apRiHA-y8SloAylK9swK6VMldMqMzoqiThNMvAjhKQ0ILhUCNK7QtKWwdKJjQTRMlhsTCMnJaoisNBzKpc5U2odKB4qoaREscR0SNBIqMSYrdxCTTZ4BBBVQ9CDCjCsBTDyAsLcLbCQBiL-lSK8r6TQUqKPCWSrVrQPjak9iAjv1YYJlJi%2BgHETETNNdLLVz44cyeFmKQo3Suk48GyTEygo4wQ4wyhIzU0StOy8xA1ZjuRVL4lBL5DMg4iM9NCiSQAsAMBRA%2BAnC0qIBDCTDVQABqT2Ywnagiyi%2B2Aq-VIqukiixk9w5ky1OitQa0sjZY7A3EzYXySEaUspSpYpJCjg5tRinq8WdYRIjlHokvMvKDCvOlS6KK0srFQon6lCR9cI4cdqVfRG3YZG7IFCz6hyFZecomnmA8rU80kGm5E65VDVMAKAFQbgLAQi6kki2kuRY1Bktw81GirwmFBi7q1LYahXNI3o8ysY-iiNYaH6RlP4wavRfwvyS8wKUlCuArC5XI1W3wIrXSd9QwazDA1nGsEMwmqiPeEW1W5izZe8xrCWl4UqWG5tE8%2B6LiporG0rWovWHW4S-WxGwCi8Ec1jZ1R22TdGn1SvC2rqNGnE9yPEz0eQrW326BHhPWyGxPaIhDXdAMl84A11SO%2BeZIzW-baE6OhK5orqmTJiyWylbBZtPmVOzeFYv0USnHLOo-HO7bQmQnEOqSqK4WmuiG4te8gjGidjM5eu9OtujKBuTzcejO8EM2uBGO5o3iizWunUz3WKZikmbhYGaqRW725lHpNW9mDWvbR0dLOa1IhbTShMVyhM4tJaSzCOHZFO8ypEmG0aeoI4ySg9B2-HZwZ2makdN2kcIlI4eLdcD7fRPndrQhahLzNBWbYqN7fCD7Qsg%2BMSCemrNshGwJMTMbTLUvLKHIHmRev0ZeiKgSyu-oPWaSy2ry626ybejeXjRcH4qpHewmaqaW9YEouWp%2Bl%2B0G0QkeXyYvXsQZLrNDMuB%2Bli9omwWyoTRBhaeK6%2B5%2BvSrWT80yH67%2B4zER7BNjfBhO5S3kp208m0tc4EmkGLdiFRhB4MUh5OihpXILC8djeK%2BKphnR3hyaI-QiCayCGYL3eOqCHxwegWEddykMe4LoIu9EfISU7nLIDRxvLUh250LWiRjBsYKqO0bJVB0EnWsAuhyJzEpmc3fID%2BylT2sjJWtxgxoo0cduzqcJlEze3evCLWyaehEY2KdITrKMGIDkZuXSWK0bdQxhxKxVem9VTVa6jmwqrm4FHm0qpki1Wi7wj69i-NfR-CP6-MYstqYG8m1GqOrp0W0e6dCuJhKev2oh9uo2su90QVCOV1CZNei5%2BeSOtRxRoAixwKaGwxh5tO1un1dugCv-YO3c-OoFhowvYuziXxgqMG1hn6wEnG4B3QW4Jc4yR5siAOzu7c2F4C%2BFsQiOjp1e%2BhyENFjev5ve2lPet28EVFyGXRwaMxgFt1Mp1pnFiF1W%2BWup1R1snzEcHivxFfI9W4haTR%2B27FgfdppF9EWCYozkGsRJx%2B1F4mvZlXHccm5CzwLFgurkabQqJtL%2BmxjjC0icb0MoLV7W%2BMw1zwa0oa9-S0k1hFlusLZF1SlOHhqUjomeh2tVxTRcaGrIFC91tymSu29IIZ8WMoepsVuHCcN4kU%2BJ5hWkaykWS3JyMsiNVs8onFLPFhhWJWKiWojbLugeCMl2ssp-I8AyRumtXrc5zN2Su80kcU2%2ByME5g%2BREnG4G9hw5oMsWM%2Bi8iskp4Iu5%2B6DhKxtqTzR0D09LMwQpmNJ11oyrO4JLdCckAZjdCwGU4ZWd-4kcBd9Vh20BGUw0poKXIpi5Dtvqe19Mo9udpYDN6N2O3CQ1zZQnRNjQult1rVn0ZMwIhCs8kBj4EIcOfRXs6916WlUUo5gZjtt1toktsHZ9n4FJ9cRc-zGmnDt1ymYZ7ltMqO8oE5mBlBsEYWX0ZehN1uFJudV1u1%2B4AafqwvAnfIGjgIrQcyzG0xWHSyAsfaeoNVi8S48RolUBEt6xKqFIFjsxHS9jl55pv0CaPj2sPLC0tUl9%2B4Jj3MESTjkNoVnObT9NztyaYxgrIqSUyaY9wG%2BHODMB12u7RO0zwVnGLT%2B1HTzN95oWbkfs-9jByYr92qHKMkOZF19UyETDmL-T3QIJPJzNpcnrPTm8uomTYEm8KGvz1T2U6h1L0tPLh8xXJ8pekrk6Nqp0jcqE3CNzssk9u2rz3WnXFuIvDOfGATzOypLNUThys9CT2tFulzi8WTzGeC8brIbCZTkTjM09n1vlv0-%2B4kNEmKHEH9hp6b4mOl94zLzy%2BNjOdy9TkA9r8qduLrkdUZ49ym7XGMUdhz9fJ8ymeb9z38zzgfbznbVb0x5SPWXV7ZYLvEgDlujbgLqLtOFpWLxU%2BCnG6zThT1lRkti5l0OC-FoIne8m6NrV2Lt1-qoj4Uj6j0tUhoOJgoVoWYMYx0TFVxFmNNg1spIIEthzyEUELirjmiVd9gnlWdvhsYMMwFylxF31tFCaZZVdSva8gJe0xEmiXptHkagsL1kX5b5EuBcF91PwgTWtrYCIIz9HyLzkXSmQcn-wJh6nnWYm0nzE3Z8rnFDtmsN7htisURvL3R-eoSM9WLKqFGsE-byIm19%2BzXjyvxsiUCjifaDxwTNKf3rGKC58vxanfGdd1COsVFpmBuyTmbmYBqn1n7VP-njP%2BP%2BH11Na1jaVrt8la6e97ykv9aAx1JWsi8IbCD6RsTmYIpzPgPpCCaQdlI4doPpOA9lNuu0TANH4-0o4C8kb4GJtruyBfaQSc9t%2BiQnvoDvvy9odzzK71Wqd8frWTDihcVi7nGtVhfvhF4UJQDkeK7Ze%2BqP37yNE-S0j8lW2%2BaBiY-8uU-2fvxBPcjF72v6VpC21EJ-lM0qbaltGgsHOjnmPIv4xU8vVkFhGG7-9vubuSbBvxf6g1Ce0AqGLV2HzcgSUXSe9qnwyZ%2BgsB6hUGqBzwFPRs%2Bt5ZPsVhIFmYu8%2B5KCD3wT59Jtu-1fDJH0R4Z1qorAtfuwP96b8ge4kN0I7xPibUoAFAUkhAE%2BT8B2aSoSRCsxkQPV1m11Z6ls0FqaJ0Ww9a5onUmLuUt2oWf2n1zIaQcB6MlKlAYJtqLhOW93XqrLCGqeMoBZ5YwTnECCZB0w-FCnlMXy7IM0oTdGZJw16RBs4m3jZNlCTiZBV%2B0eENbmhA2ShCGCpNCIS5Su7oNuubjeKgw1lS0tT4CqRVFACQD8AUAFAVKvoUOoZUsqRAfgJwDgAvwwA58BAKgGWZ3VVmRqV2FoP5qeFWS6gL0K0CGQwhgQuHH4O4A7ANBagngGYY4GMAHAfgHpL4E0FmGeBBhjgYYSEFWFm9MamwgwDkBkDbDMIEudYWxncAjDXwRwu4PigiChVDhOwoYecJCCnC9hDQfQC8KeH3CqoDwjYZ8IWHTYxi8DOsB8McAjCQRRQdGD8LOGgjMo4IkYaaUcCJJvwQwOEauCiCoioRrw3YZ8IxFTQTAHpJMLEk7B6ZvQ6I7ETCIOEYiqR5IiEZiM%2BGGIAQdIikdCDN5ZtyeiIg4WMQRHUjHhFInkb8L5GTgJcjWcoq%2BAxGGB3hNIkYYYF8DGB%2BR0I2kSYwxGy8OIyotYVKOeEajK68ovYREFJA6AdROIrUWhAxE04mRtIjEZq3LhmjDRFI8YLaNpGeQHRIw2xHKK1GWjZ8BIVoPbmdGwdpSko3kbSKBDKjdAFgX0Z0lxHsiCQdgZuASCqAvNLRBo90cmMDEuidKRwc0WCK1EIj5hZ%2BUBpmM1GpjCxAoi0VqJMAGingCTAsaYCaBkNwxhkKsdSOrEYj8R2QAkP4FYHvk9E6oosdWPU5TDqxvUase-mWAxB7R2Y%2BjrWK1Ey45Cf6asVNFxE9iSxWY3sZsipE2pcGzYlMcuOLEKiwRboTcY0DsBkjexvwaseWImDViwRS4vcbuKxG9iAqu4SYdOJSBhitRBvTtnGBPE7j5xGwXEVYA7ChwbxewmXOKL2ghBbhNlUETblxHOBLRAYn8WqLmFbjVx3QEcduNvG-jrIuI-iG8LbGGB-AEgGIERJQk-jnQ1gVNHBONGUhIxVE1cdmLok-iZRnSBMVqPWL7Akx9E3sbL3wjiipxXEsiXBMSRXi3xAkzCSWWrELCssu4XQPWHZHKNSJ4k-iT%2BKVFaihxuI0SUxOUmYTIJUkusJOXabLAzg4zY1okk4k-irsC4U0V-xgnZjAgkwcyZhP-GSSdKjEzCUmEyDfjxJmkzCTaIwl7Co%2BCEpye%2BJ8n3jEJ-kv4a0DjCTdWC4YlsS5J%2BA-QgpYU4KQ%2BLDHJT6ROgMUe6MFJm8HQXkvYQRPLKUiIpfI6cW5JSmVSjRp4v4CkDlHaSAp5QUKX8IKnVSfxeojuIpNeFJA3RvYpJGb2HDoSxJrw4CTiOeF3icRUQexPOPZHNwc2BojKWVN7F-j3xu4CqW1NSlMTepKk1wR3zkYEhJgj43rhzGkkYjIJyoqoOTlsCjSKRAE%2BcWwjimlTSxy0xaUGImlLSmJzU26dtnjDwSY0lo7aZtKBl7DpKBxesYDJAkOBLRrUj6cDJxE3Tnp4U5aSPEen-SnpK4pGe1NrFrYwxUMssV9MRk6TXpIw-RC2IamfDna-U3wHaAhkbTdR97Qmi2OJmXQoMXpasQjJGELBHpqEiYQTJGHghwxnodwPhOGl0zPhbGGIC83FwhYUZ6M96YTICmggYZCsnERgmpH%2BAHgQIHzMqL5njSbcU4BYd8CXgLitR-M7OOGPirczMZcM2GSBOVkXD4Q1gS8WtCtmYSIKKwWmbbIpkcz5ZnMxbrxLlk-8XQ7IjmE2Ndl7CfZ2QOJuM3WlezvpZvQUnjNFkUi-Jq4ryKTKTk-jXwWgH7AZxbH4gDAa2RyVVNunFycR3Y5sW2DymTBDJgcxuBiO%2BBUjY5tI6bFSMjkWz2504j0l1PFmq0LozKScheONn3TI5r4WucnMVENB7Z3onuRSOmneAxm9wTub2KJR7Rwwe0MuXHJVkUiTAfaXIPWP2Dhd7hPqRufjPnFBACgBo6VmYD%2BCezt5ioi%2BWMXrEByJ5GMnSbPPvkuiDR-QeeQOKHH9hXQFY38b7IglRAPxHIKkVlLvlvyApkYcOWLK3kwLPhQ062XsP6lUjngrA-MNPL7E6xgRgcpCc9mbE4L4Fc80hKCVpBUiSFxozeRaN1muh4xH8pBYgpAU-BWFloiCUwvYU2JXw9C5uSMKqB1gAkcUn4JXRvlXjmZ2o40SbNfnPDnAkcmcnONIWKjVJsis3tGAaCwcZoki5RcwtpHO1BZ9CuBa4JQVOTJFRKWhXoqsWsL2mocwOafN7EMjMsJjQmEzM6n6Jv5HdWIKTPdGBFoZXC3FrgoCXKjtYAShEXYrUVzBgFSFAnIRKwkJzfx90nBaopUl3TlRmc4KZXPiAZyzgPjYJcaPfKRyk4yoyRXE1HGOAmkM06BQxChnNZmJr4fFBcHrH8RTFsCuCW6DiYOLUFnwspabLZkfiiFuiy6MlBAYZLCpKhIqcIoIXZiAazY1hY%2BJwmcRBZNisZX8OiHij2Fgc6-pYqGH5LlpwcrZdUpKmriDRA0uwDKSbkBLVlfIjjnsoslHKNJfYrNpsscWeKhljgdEaPNDjky559CjBaMLOk4g5R54axb9SOXMT-xDykKVcsrgNzOFJEi6fsOfzhjWlCC2kTLktKRzpK-4-hc8OSXXKgxBK0FRqXDESA-lWyzBl0FxUxoDirE3sUcr3BTSSsuI-sEUqjEFLTAy8rOTsszYWydh8YjWTor0TnjRmPKj8WDPfFErWgRynfDys0VzLBxUq%2B4LoFDhyrA5EKhiVUsHHxAXl3SlhQkuWDSrZhXeM8XFOpXvLLRPyoMWGLwmRBiJMQHBUVIkj4g1hSqgkO4GymoTiJuqm2Z-J9WvDdg9CgZRyDPGWknR0YbFWpMjnk4%2BV649wAiPUnTiPJ54-1WipJnUrYxak1oBsKWXTKHxUKtRS2Kilmt2Y8494ZhlsmFrjRHwAtXqsnkZrYOdy31aCr1hxSBEUy-ZUYoXlsSxYFqvpf4qCDhiT2MiutS2uTEBKml1arlc2vRBeBU1%2BqkhSYp0V5rR1%2BCJtSXL9X4lU0kk9UQEv5lXAHl%2BK5dWoolHELhxwK6wCcKTVXLJwrawOZaXeVOiV14k7bHFPWCsKFJEC6RaEFNHUrcIBIM4O-lSDbCa1yXMYa3LUlQYdlhQ4oYyVlDUBiAqALVERVUEdD1B3NboU9V6EVU3qQ9K5vYLo4VhfIB2UWIS2baZ17suvUljRAhx7ZiN0JI7O-1Oxr08NjLOugOHEoAl7GikX3OQlFZ0MyNGddupRq3IHk-SEOOgjEXlgkxBqI%2BF8kHROQsbjejcRuI6Fxw8EfaDSX5vHXkhKURNl5EmOJp2zhEys6INeCqOHgMYt2Km0sAWVSHsMv0yKH9EYzD7EiwyjoRxHo1hwzRXSWPGTPyiF7%2BkD4-fKjWJvnajdcIhOLkuLwAL1lZRXIJAf40DW94IwvG1hAG2QHqxHo1VXlogmqxItOqz6alolo3iEalyLVcjuQJkyS8x%2B3HDNtVpmwz1D2jnMzJJoQzwk1%2BFmGrfxsiHHRIBudA%2BBsk-7ZFISdGzIqZ0Y0O0NaA4YeKM2rZh1bm3HEMoA3I11VvybWi8kmXmxwF%2BWtMXwKuT55yQAtvOILVfhJZhaL2EW%2BIrHD42907K1rGTBNrFYI9TsWvVYs8UrbBbagB3XwvsCrFCyBqeW7bRtt4YJYBcTZEyhAn0Z9NxiOmv0r01WKpEWq9tJvCFD24mJmM7gjdKyiKi397IubZeBVE21vt3cziwoEr2UwY6mNi1GtGNpWSHZvtbm37afRogHa-NFmY7X3V3IcIFNcqFopFqgq3aCc927LCRtzLLUcSYHcJoVoozFbgSmWqYGUUj6VF6B9Gwsj50Z1HFRd0JX%2BkRvG0D5etz-aZkbBsEMs4dlKcRsYykbTVHBY3Nvr4xuRvwX4iG5DTqhUF6oHY6GtZphr5rUU%2BhlVNQDIVLQb0BoknOlPxmlwh5oW4%2Be6IXGAqD9P0lmreCvQ3Ryl4hbST3i23z4vATpFmIRmsmkIBCk0bnSPhBJxjSFhOghPrRHkp0%2BVGQEQcvctkr3uIF8p0M8ZB28369oG5dMKNGjehuJ3a3GDTmh081ctQoJBAXAElvq58wE3IZVq21iBAggh-SJvZKir3xCXcnWzLSTFuAN6mMc%2BzzeeEEK3AK9a%2BlvbARFgAEOJs1QUh0BUyMhT9A%2BiVkPoCbL5%2BEDgM8fRsf1Dhz9L%2B0jE6UEYb5M0KnDfewU97ZRYE%2BKBBl3Xl070q8dSKiPFwHyldQl%2BUD4sfWOT5li8DHLrP0mMajUrgVfRA7AmBh%2BZD0vmypPzxGiC8TtIdELaJsM3hbZK5aKLYcWM1s4k9I6RxrjX7ylbU2kZXA0zsJxCHISUkkeADoqKtUAsVuA7FZSMxho51aQ5PNJ23aw42KJ2y-PZzMTqHdt13f0vNrf11UQqDg5geBXkPIGSNBBpRjika5z9-mLnLQ2ob9TuJpJjhwQuobQPuate5gmnUYfdLoC2Qh7KELIcT1FauDjGVPQtRYzQhkoGm5lPJRWQ%2BhI2jVKHdyzB37h7mlhhIfNTPAB8bkDQvgPBoQAu68qt1T3Y4Qw2uEwUfunDd4VY3m6bm52xg2SzKxHzBNs9TiPpt51zi7tP-AMvWwiJoxaWVtOwWwyMERanNF%2BXQKPrCbhGwWPrHw3PTa0SUnI3DTg85usHMNbB%2BGsYxMat3bkkjeEFQz1BmN278w-g%2BaDVWFwNdqDi4ANt0YG2%2BVH67SXiNgx3BDbG%2BDh8Uk4eCF3GCYk0YDOiFtCXiBUoQm1DnVSF6QbOCAsbPiC6ATweUqGAmpcggF5DtWszIUEAA)

Example use case:
```
+page.server.ts

userSettings = await getUserSettingsFromDb(...);
const userSettingsForm = await superValidate(userSettings, zod(userSettingsSchema));
```

```
+page.svelte

<Form.Field {form} name="email">
    <Form.Control let:attrs>
        <Form.Label>Email</Form.Label>
        <Input {...attrs} bind:value={$formData.email} type="email" disabled />
        <Form.Description>To update your email, please contact support.</Form.Description>
    </Form.Control>
    <Form.FieldErrors />
</Form.Field>
```

**Comment by jjones315** [comment]
That is how HTML works, you can add hidden fields for hold the values you don’t want editable, or switch to the json datatype

**Comment by andonimichael** [comment]
Ah I see this in the dataType [docs](https://superforms.rocks/concepts/nested-data#datatype):

> This also means that the disabled attribute, which normally prevents input fields from being submitted, will not have that effect. Everything in $form will be posted when dataType is set to 'json'.

Thank you.
