### ISSUE TITLE
Putting dataType: 'json' to enable nested data in a enctype="multipart/form-data" always return value from input type="file" undefined

### ISSUE THREAD

**Issue by TheBous** [ciscoheat/sveltekit-superforms#450]
In my SvelteKit project, I'm using SvelteKit-Superforms to handle form submissions. The form includes a nested data structure and an image upload field, with enctype="multipart/form-data" set to handle file uploads. However, when I set dataType: 'json', the image field always returns undefined and the image never reaches the server. This issue occurs despite the correct configuration of the form and the expected behavior of handling multipart data.

**Comment by ciscoheat** [comment]
Hi, that feature [is tested](https://github.com/ciscoheat/sveltekit-superforms/tree/main/src/routes/(v2)/v2/nested-files) and just confirmed to pass, so I'll need a MRE to see the difference. You can use one of the templates [here](https://superforms.rocks/examples), but please check with the test first if you've overlooked something.
