### ISSUE TITLE
File not available after validation in SPA mode

### ISSUE THREAD

**Issue by AKuederle** [ciscoheat/sveltekit-superforms#459]
I am trying to use a file input in SPA mode.
While the formData seems to be updated correctly, once submitted (and successfully validated), no file information is present.

Not sure if I am doing something wrong, or if this is a bug. Any help is much appreciated :) 

## Reproduction

I modified the file upload example to be purly client side. Issue can be reproduced by selecting a file, and then hitting submit. The message that should display the submitted form data shows no file information.

https://www.sveltelab.dev/q3nc7s4qqzustmz?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment]
You can't JSON.stringify a `File`, you need to access its properties directly. Try `setMessage(form, form.data.image.size)` for example and you'll see the real value.
