### ISSUE TITLE
Superforms errors store not updated when navigating to same page via CSR

### ISSUE THREAD

**Issue by konstantinblaesi** [ciscoheat/sveltekit-superforms#467]
**Description**
See reproduction repository, follow these steps
- open [Root page](http://localhost:5173)
- click link [Trigger error](http://localhost:5173/?error) on the **Root page** to trigger client side navigation/rendering
- the errors for form1
  -  are missing in the superforms errors store ($errors1)
  - present in the sveltekit page store
- refresh the [Trigger error](http://localhost:5173/?error) page
  - now the superforms errors store ($errors1) has the form errors too

[Reproduction repository](https://github.com/konstantinblaesi/sk-issues)

<details>
  <summary>After client side navigation/rendering ($errors1 empty):</summary>
  <img src="https://github.com/user-attachments/assets/2db40f00-bbc0-4d06-a5e5-6f6f7fe83296">
</details>

<details>
  <summary>After server side rendering ($errors1 has correct data)</summary>
  <img src="https://github.com/user-attachments/assets/aef28db3-a2c5-4df9-bee6-4c40555a00f1">
</details>

<details>
  <summary>Code (same as git)</summary>

```ts
// src/routes/shared.ts
import { object, string, z } from "zod"

export const Schema1 = object({
    value1: string().min(1)
})

export type Schema1 = z.infer<typeof Schema1>


export const Schema2 = object({
    value2: string().min(1)
})

export type Schema2 = z.infer<typeof Schema2>
```

```ts
// src/routes/+page.server.ts

import { setError, superValidate } from "sveltekit-superforms"
import { zod } from "sveltekit-superforms/adapters"
import { Schema1 } from "./shared"


export async function load({ url: { searchParams } }) {
    const triggerError = searchParams.has("error")
    const form1 = await superValidate(zod(Schema1))
    const form2 = await superValidate(zod(Schema1))

    if (triggerError) setError(form1, "value1", "bad value1")

    return { form1, form2 }
}

export const actions = {
}
```

```html

// src/routes/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import SuperDebug, { superForm } from 'sveltekit-superforms';

	export let data;

	const sForm1 = superForm(data.form1);
	const sForm2 = superForm(data.form2);

	const { errors: errors1 } = sForm1;
	const { errors: errors2 } = sForm2;
</script>

<SuperDebug data={{ $errors1, $errors2, $page }} />

<br />
<a href="?error">Trigger error</a>
<br />
<a href="/">Remove error</a>
```
</details>

**Comment by ciscoheat** [comment]
This is a tricky edge case; since you're adding errors in the *load function*, when the page is reloaded client-side, superForms listens to page updates through the same subscription as a page invalidation (after form submission), and cannot know the difference. 

Hopefully I can add a fix for the next release, you can make it work until then by setting `resetForm: false` on the affected forms.
