### ISSUE TITLE
Is there a way to avoid using superValidate to create forms?

### ISSUE THREAD

**Issue by Serpentarius13** [ciscoheat/sveltekit-superforms#468]
**Is your feature request related to a problem? Please describe.**
I dont want to bind my form components to any routes. Right now it sometimes requires a lot of coupling and props drilling for page-level data.form to reach form component

**Describe the solution you'd like**
I want to instantiate forms without using superValidate

Looking back at react-hook-form and vee-validate, they don't require me to use any server load function to instantiate the form. I understand that this is for accessibility for users with no javascript enabled, but is there any way to use forms just with javascript as I could do in React and other frameworks?

**Comment by konstantinblaesi** [comment]
Prop drilling is avoided with svelte context

**Comment by Serpentarius13** [comment]
> Prop drilling is avoided with svelte context Maybe context and [SPA mode](https://superforms.rocks/concepts/spa#single-page-applications-spa) works for you?

Yeah, sorry, guess I haven't read the docs thoroughly. Thanks for letting me know! :)
