### ISSUE TITLE
Updating a value twice hides change event

### ISSUE THREAD

**Issue by AndreasHald** [ciscoheat/sveltekit-superforms#470]
**Description**
If you update a value twice after each other, the value is updated as expected however the changeEvent will be swallowed. glancing at the code I believe it is because the first change updates the value, so when the second compares changes there is none.

However it creates situations where is you accidentally update the value twice, no change event whatsoever is fired.

**If applicable, a MRE**
[Reproducible example](https://www.sveltelab.dev/hdyczpieozywhkh)

**Comment by ciscoheat** [comment]
Should be fixed now with 2.19.0
