### ISSUE TITLE
File is converted to to the string `[object File]` on upload

### ISSUE THREAD

**Issue by Stadly** [ciscoheat/sveltekit-superforms#476]
- [x] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
When uploading a file, it is converted to the string `[object File]`.

**If applicable, a MRE**
https://www.sveltelab.dev/blxbdjjlfoofcc8

Steps to reproduce:
1. Select a file in the `<input>` element.
2. Observe that the file is correctly populated in the `SuperDebug`.
3. Submit the form.
4. Observe in the server output that the string `[object File]` was received at the server, instead of the actual file contents.

**Comment by ciscoheat** [comment]
You're missing `enctype="multipart/form-data"` on the form element.

**Comment by Stadly** [comment]
Well, that's embarrassing 😳 Thanks a lot!
