### ISSUE TITLE
$submitting isn't reset when there is an error.

### ISSUE THREAD

**Issue by niemyjski** [ciscoheat/sveltekit-superforms#485]
- [X] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
I made a request which threw an exception during onUpdate. `submitting` was not reset and so I always have a loading spinner.

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/1cadb8ba-6b19-4e0c-9d0b-be37e6c8897e">

On side note, I tried to look where submitting was set (didn't see any references)

**Comment by ciscoheat** [comment]
I can't reproduce this, using this test: https://github.com/ciscoheat/sveltekit-superforms/blob/9cbf06f91281eb0270c9b3ed11a835fccb902765/src/routes/(v2)/v2/spa-error/%2Bpage.svelte#L4
When I do the test, submitting is reset to false for all events.

**Comment by niemyjski** [comment]
I'll try to create a sample. Also while looking at this, noticed you cannot use onError to update the message as form is missing.

```       
 onError({ form }) {
          setMessage(form, 'An error occurred while logging in, please try again.');
      },
        ```

**Comment by ciscoheat** [comment]
Yes, there is no data to update as an exception was thrown, you have to set `$message` or other stores directly.

**Comment by niemyjski** [comment]
Here is a sample https://www.sveltelab.dev/wio08v2eu7gokiy  that shows off this issue and 4 other issues when using SPA mode

1. can't set form errors from onError or other functions defined (on change etc..),
2. updating form.data doesn't work
3, Have to set result.status instead of just throwing an error or setting a form error.
4. focus lost on input text box
5. submitting not reset.

**Comment by ciscoheat** [comment]
Here's an updated version of the sample that explains most of the problems you're having in the comments: https://www.sveltelab.dev/g1vrs75tk8e7lkb

Relevant code part, for reference:

```ts
const { form, errors, message, enhance, submit, submitting } = superForm(
  defaults({ email: 'test@test.com' }, zod(schema)),
  {
    onError(event) {
      console.log('=== onError ===');

      /* 
        1. It's not possible to use the SuperValidated data from onError, 
        as it can be caught in onSubmit where it doesn't exist.
        
        You need to update the stores directly.
      */
      $message = JSON.stringify(event, null, 2);

      // Cast the error, as its type isn't unknown.
      const error = event.result.error as Record<string, unknown>;

      $errors = error.errors as Record<string, string[]>;
    },
    async onUpdate({ form, result }) {
      console.log('=== onUpdate ===');

      if (!form.valid) {
        console.log('Invalid form, returning early.');
        return;
      }

      const isSuccess = Math.random() >= 0.5;
      console.log('isSuccess', isSuccess);

      if (isSuccess) {
        // 2. Updating form.data does work, the data wasn't modified in your example:
        // 5. This only works if resetForm: false. Otherwise the form will reset.
        form.data = {
          name: form.data.name + ' Updated',
          email: form.data.email.replace('.com', '.org')
        };
      } else {
        const madeupProblemDetails = {
          type: 'https://example.com/probs/validation-error',
          title: 'Validation Error',
          status: 422,
          detail: 'There are validation errors in your request.',
          instance: '/your/instance/uri',
          errors: {
            name: ['String must contain at least 2 character(s)'],
            email: ['Invalid email']
          }
        };

        const shouldThrow = Math.random() >= 0.5;
        console.log('shouldThrow', shouldThrow);

        if (shouldThrow) {
          // 3. This will update the status in the next release:
          result.status = 422;
          throw madeupProblemDetails;
        }

        setError(form, 'name', ['random error']);
        result.status = 422;
        result.type = 'failure';
        // 3. Cannot set data to anything else than a SuperValidated object. In general, tamper as little as possible with the result
        // 4. Focus will be kept when this is commented out.
        //result.data = madeupProblemDetails;
      }
    },
    SPA: true,
    validators: zod(schema),
    resetForm: false
  }
);

const debouncedSubmit = debounce(500, submit);
```

Most of these problems aren't bugs, so if you're using this in a commercial project, please consider making [a donation](https://superforms.rocks/contributing#donations).
