### ISSUE TITLE
Deprecation warning on latest Sveltekit build : "The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0."

### ISSUE THREAD

**Issue by MarArMar** [ciscoheat/sveltekit-superforms#486]
Thanks you for this awesome lib that I am very pleased to use and is very helpful 👍

**Description**

Using "sveltekit-superforms": "^2.19.0" ; "@sveltejs/kit": "^2.5.28", ; "svelte": "^4.2.19",

On Sveltekit build, I see this deprecation warning , seems to be for "yup-to-json-schema" :
 
"transforming (296) ../../node_modules/sveltekit-superforms/dist/adapters/yup-to-json-schema/converters/index.jsDeprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0."

More info: https://sass-lang.com/d/legacy-js-api

**Comment by ciscoheat** [comment]
Thank you, hopefully it's easy to fix for the next release. Glad you like Superforms. :)

**Comment by ciscoheat** [comment]
This may be a configuration issue not related to Superforms, not sure yet. https://sass-lang.com/documentation/breaking-changes/legacy-js-api/
