### ISSUE TITLE
zod defaults not dynamic

### ISSUE THREAD

**Issue by ak5** [ciscoheat/sveltekit-superforms#487]
- [x] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
dynamic defaults always the same

**MRE:**
Couldn't figure out how to link my specific example, but if you replace the given schema.ts with this one, you will see the id never changes
```
import { z } from 'zod';
import {nanoid} from 'nanoid'

export const schema = z.object({
	id: z.string().default(nanoid),
	name: z.string().min(2),
	email: z.string().email()
});
```

**Comment by ak5** [comment]
yes, it's just not what I would expect, 

now I need to change the defaults on each form in load and reapply some logic in onSubmit() or something, it's cumbersome :)

**Comment by ciscoheat** [comment]
It will work in [strict mode](https://superforms.rocks/concepts/strict-mode), since that won't apply default values to the validated data:

```ts
const form = await superValidate(zod(schema), { strict: true })
```
