### ISSUE TITLE
Export ClientValidationAdapter in 'sveltekit-superforms/adapters'

### ISSUE THREAD

**Issue by bfovez** [ciscoheat/sveltekit-superforms#488]
In a effort to factorize some code, I would need to pass a ValidationAdapter (server-side) or a ClientValidationAdapter (client-side)  to a function.
Unfortunately, it seems that ClientValidationAdapter is not exported in 'sveltekit-superforms/adapters' (contrary to ValidationAdapter).
Is it possible to export ClientValidationAdapter in 'sveltekit-superforms/adapters'?

**Comment by ciscoheat** [comment]
Sure, I'll add that for the next release.

**Comment by bfovez** [comment]
Many thanks!

**Comment by ciscoheat** [comment]
Added now in 2.19.1
