### ISSUE TITLE
json datatype only validates in a formData object, not a regular object

### ISSUE THREAD

**Issue by jdgamble555** [ciscoheat/sveltekit-superforms#489]
**Description**
If I use ```dataType: 'json'``` on the client, and pass the data to the server, the data only gets validated if it is a `request` object, not a regular object.

For example:
```ts
const form = await superValidate(request, valibot(mySchema));
```
This schema has no problems validating.  The request object contains a `formData` object.  You can see `__superform_json` only gets checked using a `formData` object [on this line](https://github.com/ciscoheat/sveltekit-superforms/blob/cf38c1c7bf5c922a37333906670db60b9b899d40/src/lib/formData.ts#L110).

But what if I need to modify the data first?

Example:
```ts
const _formData = await request.formData();

// https://github.com/fabian-hiller/decode-formdata
const formData = decode(_formData, {
    arrays: ['tags'],
    files: ['photo']
});

const form = await superValidate(formData, valibot(mySchema));
```
You can see now the `formData` is no longer a request object, but a regular parsed object.  Now, `__superform_json` won't get parsed at all.

Since `superValidate` accepts BOTH a request object and a regular object, so should the `json` validator.  Otherwise, there is no way to modify the form data before passing it to the `superValidate` function.  This means there are NO work arounds.

J

**Comment by ciscoheat** [comment]
If you transform the form data to an object, that's what will be validated, not the request. It could come from a DB or anywhere else. 

It's not meant to combine `FormData` and the `__superform_json` data (which is encoded with [devalue](https://github.com/Rich-Harris/devalue)). The validation schema is for one of them, not both.

But if you want to bend the rules, you need to call superValidate twice:

```ts
// This will validate __superform_json
const form1 = await superValidate(_formData, valibot(superFormSchema));

// This will validate the transformed FormData
const form = await superValidate(formData, valibot(formDataSchema));
```

So YES, there are workarounds. 😀

**Comment by jdgamble555** [comment]
I think using `devalue` directly is what I was looking for.  Thanks!
