### ISSUE TITLE
Support for VineJs 2

### ISSUE THREAD

**Issue by VL07** [ciscoheat/sveltekit-superforms#491]
Considering [VineJs 2.0.0](https://github.com/vinejs/vine/releases/tag/v2.0.0) has been out since March, it would have been nice to have support for it in the VineJs adapter. 

When I tried using VineJs 2 with the VineJs adapter I only got TS type errors, and the `package.json` for this project requires (peer dependency) version `^1.8.0`. So to my understanding it's not currently supported.

You can still just use version `1.8.0` because it still has the same functionality. But I believe it would be good to mention this in the docs so you don't accedentally install the wrong version like I did.

**Comment by ciscoheat** [comment]
Hopefully I can support both versions. Do you know if there are any breaking changes between the major versions that will affect how you use it with Superforms?

**Comment by ciscoheat** [comment]
What errors do you get? I'm testing with 2.0 and it works fine for me, so I'll just add it to the peer dependencies.
