### ISSUE TITLE
Bug in Tutorial?

### ISSUE THREAD

**Issue by thunderbug1** [ciscoheat/sveltekit-superforms#494]
I am going through the Tutorial of the CRUD example [here](https://superforms.rocks/crud#reading-a-user-from-the-database)

It has this code passage:
```
import { superValidate, message } from 'sveltekit-superforms';
import { zod } from 'sveltekit-superforms/adapters';
import { error, fail, redirect } from '@sveltejs/kit';
import { users, userId } from '$lib/users';

export const load = async ({ url, params }) => {
  // READ user
  const user = users.find((u) => u.id == params.id);

  if (params.id && !user) throw error(404, 'User not found.');

  // If user is null, default values for the schema will be returned.
  const form = await superValidate(user, zod(crudSchema));
  return { form, users };
};
```

What is confusing to me is this comment: `  // If user is null, default values for the schema will be returned.`
It is not true, because when the user is null we throw an error in the line above and so we won't return an object with the default values.
How does this work?

**Comment by ciscoheat** [comment]
`params.id` is the key here, so if you don't specify an id in the route the user will be `null`, which will set up an empty form for creating a new user.

**Comment by thunderbug1** [comment]
Ah ok, thanks for clarifying.
