### ISSUE TITLE
effect adapter errors when using Schema from Effect

### ISSUE THREAD

**Issue by valterkraemer** [ciscoheat/sveltekit-superforms#497]
- [X] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
`effect` adapter errors when using `Schema` directly from `effect` instead of `@effect/schema`. This is the recommended way of doing it since [Effect 3.10](https://effect.website/blog/releases/effect/310/)

```
Argument of type 'Struct<{ name: typeof String$; }>' is not assignable to parameter of type 'AnySchema'.
  Property '[TypeId]' is missing in type 'Struct<{ name: typeof String$; }>' but required in type 'Schema<any, any, never>'.
```

<img width="549" alt="Screenshot 2024-10-31 at 17 28 00" src="https://github.com/user-attachments/assets/746428f3-788d-45d8-98d8-800f91c117c0">

**If applicable, a MRE**
https://www.sveltelab.dev/8utko5i2yydzzjo

**Comment by ciscoheat** [comment]
Those eternal updates... I'll put it up for the next release.

**Comment by valterkraemer** [comment]
> Those eternal updates... I'll put it up for the next release.

Great! Appreciate it!

**Comment by ciscoheat** [comment]
There are some breaking types in the 3.10 update that I cannot figure out. @szethh can you take a look at an update for the adapter, perhaps?

**Comment by szethh** [comment]
sure, i knew this was coming ahah 😅

right after we merged the adapter pr they combined `Schema` into the greater `effect` namespace. 

will do this over the next week

**Comment by ciscoheat** [comment]
Thanks, I'll make a Superforms release today, just so you'll be using the latest version. :)
