### ISSUE TITLE
Global Override not working

### ISSUE THREAD

**Issue by JosephYesWaste** [ciscoheat/sveltekit-superforms#499]
Hi, 

We have recently moved our emails over to Microsoft Exchange. Since this was done the contact entries from SuperForms have not been forwarding to our email. The SMTP settings are disabled and we have tried using a non domain-specific email address as an alternative; however this is also not receiving contact form submissions.

When I try to use the global override in the settings the tick box does not apply, so I am wondering if there is something that can be done to get contact form submissions forwarding again. I can see submissions in the entry log, so we are not losing any data, but ideally we would be notified of submissions as we were previously.

I hope to hear from someone (I am not a dev, but know a little bit about a little bit - if that makes sense).

Best regards, 
Joseph

**Comment by ciscoheat** [comment]
I don't know about a global override, at least that's not a Superforms thing. You need to debug the form action and see if a mail gets sent.

**Comment by JosephYesWaste** [comment]
There is a global override section in the settings. I can confirm that ther is no mail being sent though.

Best,
Joseph

[xs+jvZ+Ty+5DQAAAABJRU5ErkJggg==]
Yes Waste
p:
0800 058 25 22
a:
Yes Waste Ltd | Unit 16 | Monckton Road Industrial Estate

Wakefield | WF2 7AL
w:
www.yeswaste.com<http://www.yeswaste.com/>  e: ***@***.******@***.***>

YES WASTE is the trading name of Yes Waste Ltd, a company registered in England and Wales with company number: 06150145
VAT No: 174898937
Waste carrier's registration: CBDU117809



From: Andreas Söderlund ***@***.***>
Date: Friday, 1 November 2024 at 11:39
To: ciscoheat/sveltekit-superforms ***@***.***>
Cc: Joseph Bell ***@***.***>, Author ***@***.***>
Subject: Re: [ciscoheat/sveltekit-superforms] Global Override not working (Issue #499)

I don't know about a global override, at least that's not a Superforms thing. You need to debug the form action and see if a mail gets sent.

**Comment by ciscoheat** [comment]
What settings, and what does it override?

**Comment by JosephYesWaste** [comment]
Apologies Andreas, but are you familiar with SuperForms? There is a section in the settings area for Global Overriding – within this area there is a setting that allows you to change the the email address that contact entries are forwarded to across all forms; however, the settings are not saving for one reason or another.

Best,
Joseph

[xs+jvZ+Ty+5DQAAAABJRU5ErkJggg==]
Yes Waste
p:
0800 058 25 22
a:
Yes Waste Ltd | Unit 16 | Monckton Road Industrial Estate

Wakefield | WF2 7AL
w:
www.yeswaste.com<http://www.yeswaste.com/>  e: ***@***.******@***.***>

YES WASTE is the trading name of Yes Waste Ltd, a company registered in England and Wales with company number: 06150145
VAT No: 174898937
Waste carrier's registration: CBDU117809



From: Andreas Söderlund ***@***.***>
Date: Friday, 1 November 2024 at 11:49
To: ciscoheat/sveltekit-superforms ***@***.***>
Cc: Joseph Bell ***@***.***>, Author ***@***.***>
Subject: Re: [ciscoheat/sveltekit-superforms] Global Override not working (Issue #499)

What settings, and what does it override?

**Comment by ciscoheat** [comment]
Sorry, but I don't think we are talking about the same Superforms. This is the form validation library for SvelteKit.

**Comment by JosephYesWaste** [comment]
Understood – the SuperForms I am talking about is for WordPress contact forms

Best,
Joseph

[xs+jvZ+Ty+5DQAAAABJRU5ErkJggg==]
Yes Waste
p:
0800 058 25 22
a:
Yes Waste Ltd | Unit 16 | Monckton Road Industrial Estate

Wakefield | WF2 7AL
w:
www.yeswaste.com<http://www.yeswaste.com/>  e: ***@***.******@***.***>

YES WASTE is the trading name of Yes Waste Ltd, a company registered in England and Wales with company number: 06150145
VAT No: 174898937
Waste carrier's registration: CBDU117809



From: Andreas Söderlund ***@***.***>
Date: Friday, 1 November 2024 at 11:54
To: ciscoheat/sveltekit-superforms ***@***.***>
Cc: Joseph Bell ***@***.***>, Author ***@***.***>
Subject: Re: [ciscoheat/sveltekit-superforms] Global Override not working (Issue #499)

Sorry, but I don't think we are talking about the same Superforms. This is the form validation library for SvelteKit.

**Comment by ciscoheat** [comment]
Cleared that up then. :)

**Comment by JosephYesWaste** [comment]
To some extent, yes. I take it this is not the right place to be asking questions about SuperForms then? lol

Best,
Joseph

[xs+jvZ+Ty+5DQAAAABJRU5ErkJggg==]
Yes Waste
p:
0800 058 25 22
a:
Yes Waste Ltd | Unit 16 | Monckton Road Industrial Estate

Wakefield | WF2 7AL
w:
www.yeswaste.com<http://www.yeswaste.com/>  e: ***@***.******@***.***>

YES WASTE is the trading name of Yes Waste Ltd, a company registered in England and Wales with company number: 06150145
VAT No: 174898937
Waste carrier's registration: CBDU117809



From: Andreas Söderlund ***@***.***>
Date: Friday, 1 November 2024 at 11:59
To: ciscoheat/sveltekit-superforms ***@***.***>
Cc: Joseph Bell ***@***.***>, Author ***@***.***>
Subject: Re: [ciscoheat/sveltekit-superforms] Global Override not working (Issue #499)

Cleared that up then. :)

**Comment by ciscoheat** [comment]
Not the WP plugin, but this one is pretty nice as well, you should try it out sometimes if you ever change platform. 😁
