### ISSUE TITLE
`Valibot 1.0.0-beta.3`: TypeError: schema._run is not a function

### ISSUE THREAD

**Issue by lumosminima** [ciscoheat/sveltekit-superforms#503]
![Screenshot 2024-11-05 131802](https://github.com/user-attachments/assets/3f3e4ee7-52e9-403e-b978-7084eb329192)

**Comment by ciscoheat** [comment]
Valibot is beta, and have had at least two type changes during this last year, that's why this happens. I hope it can be released in a stable version soon. I'll update its dependency to the latest version in the next Superforms update.
