### ISSUE TITLE
Valibot superForm Client params type not compatible

### ISSUE THREAD

**Issue by narahunter13** [ciscoheat/sveltekit-superforms#505]
![image](https://github.com/user-attachments/assets/3a36e23b-0815-4ab3-a181-e81ebbf26dff)

**Comment by dpaulflavius** [comment]
add the imports and schema definition

**Comment by narahunter13** [comment]
Params in valibot is SupportSchemas. But, the schema return object valibot. I have added 'import' and the schema

**Comment by dpaulflavius** [comment]
> Params in valibot is SupportSchemas. But, the schema return object valibot. I have added 'import' and the schema

It wasn't a suggestion, I meant you to show us the schema definition and how you imported everything to make sure it matches :D
post the entire code

**Comment by NaviTheCoderboi** [comment]
> ![image](https://private-user-images.githubusercontent.com/44825321/383873532-3a36e23b-0815-4ab3-a181-e81ebbf26dff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzQ2OTIsIm5iZiI6MTczMTA3NDM5MiwicGF0aCI6Ii80NDgyNTMyMS8zODM4NzM1MzItM2EzNmUyM2ItMDgxNS00YWIzLWExODEtZTgxZWJiZjI2ZGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDEzNTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYzZhMGRmYjNmNDg4Njk5YWJlYzA5YTdhMjBlODI1MDcxOWU1NjUyNTZmOGUwYmFiODVkZTRhMmU5NTM3YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T98j5X6kKkBmrfIbVFqE6lPGcVwsqBwLXwCpgxmt75k)

i also getting such error
![image](https://github.com/user-attachments/assets/563bfc12-6730-4395-bf63-4edf7856aea8)

**Comment by ciscoheat** [comment]
@NaviTheCoderboi can you post the schema you're getting an error with here?
