### ISSUE TITLE
Value does not sync from parent to child component

### ISSUE THREAD

**Issue by mateeyow** [ciscoheat/sveltekit-superforms#507]
- [x] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
When we do `Componentization` of the form, the parent will not be able to subscribe to any changes from the child component.

Please see MRE here - https://www.sveltelab.dev/wl0rfm8u6rfld7z.

Notice that when I type to any fields the `SuperDebug` field does not get updated. Am I missing something? Thanks
<img width="659" alt="image" src="https://github.com/user-attachments/assets/8942c994-a77f-4966-874b-3f5b237eb113">

**Comment by ciscoheat** [comment]
Hi, you're creating a new instance of superForm in the component, that's why it's not working. You need to pass the `SuperForm` object created in +page.svelte instead of the `SuperValidated` data.

**Comment by mateeyow** [comment]
Got it, thanks!
