### ISSUE TITLE
Server side validation on fields

### ISSUE THREAD

**Issue by gerhardcit** [ciscoheat/sveltekit-superforms#514]
**Is your feature request related to a problem? Please describe.**
When filling in values in a form, I need to validate fields by doing some remote fetch on the server to see if it's valid.

**Describe the solution you'd like**
How do I set errors on the server side for a field and send it back to the client?

**Describe alternatives you've considered**
Tried something like this
```typescript
const adminValue = form.data.admin;
const valid = await validateAdmin(adminValue);
if (!valid) {
    form.errors.admin = ['Invalid admin version'];
    return fail(400, form);
}
```

**Additional context**
Often form input would require some lookups and double checking before we can accept the form.
Not sure I'm missing something, but the docs does not seem to be clear on that?

**Comment by gerhardcit** [comment]
Documentation shows this
```
if (form.data.email.includes('spam')) {
      // Will also return fail, since status is >= 400
      // form.valid will also be set to false.
      return message(form, 'No spam please', {
        status: 403
      });
    }
```

should it not be able to attach the "No spam please" message to the email errors ?

**Comment by gerhardcit** [comment]
ok, found it..

```
if (!valid) {
    form.errors.admin = ['Invalid admin version'];
    return fail(400, {form});
}
```

duh...

**Comment by ciscoheat** [comment]
[setError](https://superforms.rocks/concepts/error-handling#seterror) is also a convenient way of setting form errors.
