### ISSUE TITLE
how to return custom errors (eg prisma errors)

### ISSUE THREAD

**Issue by bobbymannino** [ciscoheat/sveltekit-superforms#52]
the form validation works great but how can i return an error unrelated to data validation? do i have to use `export let form`?

my case is this:
```
return fail(409, { usernameAlreadyExists: true, form });
```
i cannot seem to find the usernameAlreadyExists error anywhere except on form coming from sveltekit? I have a feeling i am doing something wrong but am not totally sure, any help would be appreciated

**Comment by ciscoheat** [comment]
Hi, since you return it in a form action, it should be available on `$page.form` after submitting.

**Comment by ciscoheat** [comment]
You can use [one of the events](https://github.com/ciscoheat/sveltekit-superforms/wiki/Event-order) to fetch it, maybe `onUpdate` in your case so you can choose to cancel the update if something went wrong.

**Comment by bobbymannino** [comment]
Thank you
