### ISSUE TITLE
Zod v3.24.0 update breaks Superforms

### ISSUE THREAD

**Issue by notramo** [ciscoheat/sveltekit-superforms#527]
It's technically a breaking change (that mandates SemVer MAJOR version), released by the Zod project with a SemVer MINOR version. See https://github.com/colinhacks/zod/issues/3901

**Comment by colinhacks** [comment]
This typically happens where there are multiple versions of Zod in a codebase. Try running `pnpm why zod` to see which versions exist in node_modules and why they were installed.
