### ISSUE TITLE
superValidate fails when Zod schema includes async refinements/transformations

### ISSUE THREAD

**Issue by abastardi** [ciscoheat/sveltekit-superforms#57]
If the Zod schema includes an async refinement or transformation, `superValidate` fails with the following error:

```
Error: Async refinement encountered during synchronous parse operation. Use .parseAsync instead.
```

**Comment by ciscoheat** [comment]
This is just about to be fixed! Check back in about an hour. :)

**Comment by ciscoheat** [comment]
There, 0.6.2 released which uses async validation now. (Can't believe I missed that...) Can you confirm that it works?

**Comment by abastardi** [comment]
It works! Thanks.

On a related note, is there an easy way to prevent running expensive refinements and transformations in the initial call to `superValidate` in the `load` function?

**Comment by ciscoheat** [comment]
If you send null to superValidate and have no effects on the schema itself, it will just return an empty entity without validation, that could be a way. Otherwise, extending the schema and override the expensive methods is another way.
