### ISSUE TITLE
Throwing error for a specific field

### ISSUE THREAD

**Issue by akiarostami** [ciscoheat/sveltekit-superforms#6]
This is more of a discussion than an issue, but since discussions are not enabled here, I'm posing as an issue.

I am not sure if this is something I missed in the documentation, or we don't have this feature, but I can't find a way to throw an error for a specific field.

In my case, if the user tries to save an existing value for a unique field, I want to be able to throw an error for that field specifically, which should show up in $errors. 

Is there currently a way to do that?

Thank you.

**Comment by ciscoheat** [comment]
There is a way, hidden deep in the documentation (it needs some cleanup for sure):

```ts
import { setError } from 'sveltekit-superforms/server';

return setError(form, 'field', 'Not unique!')
```

> It returns a `fail(400, { form })` so it can be returned immediately, or more errors can be added by calling it multiple times before returning.

Currently documented here: https://github.com/ciscoheat/sveltekit-superforms#server

**Comment by akiarostami** [comment]
Thank you!

**Comment by quinnvaughn** [comment]
@ciscoheat This is still documented but it's wrong. There is currently no field option for setError. 

It is (form, error, options). I don't know how to set a field error any more.
