### ISSUE TITLE
Array of strings values defaults to empty array

### ISSUE THREAD

**Issue by oganexon** [ciscoheat/sveltekit-superforms#60]
First of all, great lib !

I am trying to group several inputs into an array of values, an array of strings. For the example, the array will be of size 2.

```ts
const schema = z.object({
  string_array: z.string().array().nonempty(),
});
```
```html
    <input type="text" name="string_array" />
    <input type="text" name="string_array" />
```
![image](https://user-images.githubusercontent.com/52361520/227061994-a7431a6d-fe0a-48d1-bfd9-4a7172d26120.png)

When submitting the form, I get empty arrays instead of strings. 

![image](https://user-images.githubusercontent.com/52361520/227062012-c55b7672-cb5b-447f-81c5-358e3e2141d1.png)
With one of the inputs filled in:
![image](https://user-images.githubusercontent.com/52361520/227062040-82b92319-2c14-45b8-ab9f-cfaa7b910d55.png)
![image](https://user-images.githubusercontent.com/52361520/227062050-367b9be6-57b6-4339-bfcd-d373903cbaff.png)

I may have made a mistake somewhere, and if so please tell me how to do it the right way!

Reproduction repo : https://github.com/oganexon/superform-string-url-array-bug

**Comment by ciscoheat** [comment]
I think that the `nonempty` modifier may cause some trouble, it may not be fully supported by the zod class parser. Can you try to remove it and see if it works, and if it does, use `min` instead of `nonempty`. It should work though, so I will make sure it does for the next release.

**Comment by oganexon** [comment]
I just removed `.noempty()`, it does not change anything unfortunately :/

**Comment by ciscoheat** [comment]
Yes, confirmed that posting an empty value returns an array! It must have something to do with the type being detected and coerced as an array if empty. Will take care of that straight away.

**Comment by ciscoheat** [comment]
v0.6.3 just released which should fix this. Let me know if things are fine now!
