### ISSUE TITLE
Feature Request:  Submit function

### ISSUE THREAD

**Issue by ryoppippi** [ciscoheat/sveltekit-superforms#75]
Sometimes I want to submit a form when the input value changes, not when the button is pressed.
ex:
``` svelte	

<script lang="ts">
  import type { PageData } from './$types';
  import { superForm } from 'sveltekit-superforms/client';

  export let data: PageData;
  let button: HTMLButtonElement

  // Client API:
  const { form } = superForm(data.form);
</script>

<form method="POST" on:change={()=>button.click()}>
	<input type="text"  bind:value={$form.text}>
	<button type="submit" hidden  bind:this={button}/>
</form>
```

If you create a `submit` function like
```typescript
const { form, submit } = superForm(data.form);
```
It makes my life easier!!

**Comment by ciscoheat** [comment]
I wish that was possible, but since `superForm` knows nothing about the form element it's used on, and also that `use:enhance` can be applied to several forms, that can't be done. But in the example, does it work to simplify like this:

```svelte
<form method="POST" on:change={(e) => e.currentTarget.requestSubmit()}>
```

**Comment by ryoppippi** [comment]
Oh, I didn't know that!
it might be the best one! Thanks

**Comment by samuba** [comment]
@ciscoheat I have another use case for this: 
I want to have a confirmation prompt where the user can decide if he really wants to submit the form. 
e.g. "Are you sure you want to overwrite these values?" OK-Cancel

Any ideas for this?

btw. I absolutely love the work you have done with this :-)

**Comment by Bewinxed** [comment]
> Oh, I didn't know that! it might be the best one! Thanks

Here's how I do it.

```ts

<script lang='ts>
let renewFormEl: HTMLFormElement;

// if you want to trigger submit on change
$: {
{...$form}
renewFormEl.requestSubmit();
}

// if you want to submit on mount (this is what I used in my case
onMount(() => {
		renewFormEl.requestSubmit();});
</script>

<form bind:this={renewFormEl}>
...
</form>
```

**Comment by phobetron** [comment]
There are some valid (though unfortunate) scenarios where form will need to be programmatically submitted (such as, to work around limitations in some component libraries like SMUI) and the afore-mentioned work-arounds do _not_ work well if you have any async calls fired during the submit that need to be coordinated/synchronized with other logic. 

I think this should be possible even when there are multiple forms, as Superforms itself does support multiple forms (according to the documentation) and I could see this working similarly to what is outlined in that doc.

**Comment by ciscoheat** [comment]
With 1.0 and its refactoring, this may be easier to achieve, so I'm reopening this.

**Comment by ciscoheat** [comment]
What's problematic is that there is no actual connection between a html form element and superForm. So in this simple case (assume no html form in the component):

```ts
const { submit } = superForm(data.form);
```

Where should `submit` post? With what method? How about form encoding types? And also, how should the `$form` data be processed? Converted to urlencoded, unless `dataType` is `json`?

There are a lot of scenarios that needs to be handled with `submit`, that makes it look rather similar to `fetch`.

**Comment by ciscoheat** [comment]
Will close this now due to the issues mentioned above, and that you can use the standard [requestSubmit](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit) to submit. The [validate](https://superforms.rocks/concepts/client-validation#validate) method can also be used if you want use `fetch`.
