### ISSUE TITLE
Exclude Form Fields And Fail

### ISSUE THREAD

**Issue by n00ki** [ciscoheat/sveltekit-superforms#77]
**Is your feature request related to a problem? Please describe.**
When dealing with form submissions on the server, we often want to prevent sensitive data (e.g. passwords) from being sent back to the client.

**Describe the solution you'd like**
A simple helper method that resets specified fields and returns SvelteKit's native `fail`.

Maybe something like this on the server:
```ts
function excludeFieldsAndFail(form, fields: array, status = 400) {
    for (const field of fields) {
        form[field] = ''
    }
    return fail(status, { form })
}
```

and on the client side:
```ts
if (!form.valid) {
    return excludeFieldsAndFail(form, ['password', 'passwordConfirmation'], 401)
}
```

Thoughts? :)

**Comment by ciscoheat** [comment]
I'm trying to steer away from top-level only functions now when nested data is available, so the fields array will have to support that, which makes it, I think, a bit convoluted to add as a simple helper, at the same time it's simple enough to make a helper like you did, that fits a specific project.

**Comment by ciscoheat** [comment]
Thank you for nice suggestions! Keep them coming. :)
