### ISSUE TITLE
superValidate loses Zod types with top-level transforms

### ISSUE THREAD

**Issue by abastardi** [ciscoheat/sveltekit-superforms#81]
With schemas that look like `z.object({...}).transform(...)`, `superValidate` loses the precise Zod types that Zod would be able to infer via `schema.parse`.  For example:

```
		const schema1 = z.object({
			first_name: z.string(),
			last_name: z.string()
		});
		const form1 = await superValidate(request, schema1);
		form1.data; // inferred type: { first_name: string, last_name: string }

		// When adding a single transform, superValidate fails to pick up the properties added by the transform.
		const schema2 = schema1.transform((v) => {
			return { ...v, full_name: `${v.first_name} ${v.last_name}` };
		})
		const form2 = await superValidate(request, schema2);
		form1.data; // inferred type: { first_name: string, last_name: string } -- missing full_name

		// When adding a second transform, superValidate loses all typing information, falling back to `{ [key: string]: any }`.
		const schema3 = schema2.transform((v) => {
			return { ...v, initials: `${v.first_name[0]}${v.last_name[0]}` };
		});
		const form3 = await superValidate(request, schema3);
		form3.data; // inferred type: { [key: string]: any }
```

Note, Zod itself does not have any problem with this:

```
		const form3 = schema3.safeParse({});
		if (form3.success) form3.data // inferred type: { first_name: string, last_name: string, full_name: string, initials: string }
```

**Comment by ciscoheat** [comment]
After digging a bit, I realize this is a difficult problem. Since `transform` doesn't add any type information to the schema of the `ZodObject` created by `z.object` afaik, `superValidate` cannot parse it for default values and other metadata. Unfortunately I think this means that `transform` cannot be used on validation schemas.

**Comment by ciscoheat** [comment]
Well, it can be used, but if you add any new fields, they won't be a part of the `data` in the validation object returned from `superValidate`.

**Comment by abastardi** [comment]
Got it. Will likely avoid top-level transforms. Thanks.
