### ISSUE TITLE
remove empty fields

### ISSUE THREAD

**Issue by xmlking** [ciscoheat/sveltekit-superforms#86]
I have to implement  this [lib](https://github.com/xmlking/svelte-starter-kit/tree/main/src/lib/zodfd) for following common usecases  , because  my backend(Hasura GraphQL) set missing fields during **create** time to database specific defaults (created_at, created_by …)
Similarly I have to set **empty** fields to **null** during **updates**.  To prevent replacing data fields with nulls.

- Preprocess FormData/URLSearchParams/Params with remove empty fields (for CRUD create operation)
-  Preprocess FormData/URLSearchParams/Params with set empty fields to null (for CRUD update operation)
- 
wonder if capability is natively available in super forms ?

**Comment by ciscoheat** [comment]
Hello, this should be possible, on both server and client!

To preprocess `FormData` on the client, use the [onSubmit](https://superforms.vercel.app/concepts/events#onsubmit) event, using the `data` parameter.

```ts
const { form } = superForm(data.form, {
  onSubmit({ data }) {
    // Check values
  }
});
```

On the server, you can do like this:

```ts
export const actions = {
  default: async ({ request }) => {
    const formData = await request.formData();

    // Check if create/update, then modify values here

    const form = await superValidate(formData, schema);
  }
} satisfies Actions;
```

**Comment by ciscoheat** [comment]
You could also modify `form.data` after validation, if that's more convenient.

**Comment by xmlking** [comment]
Thanks @ciscoheat will try tomorrow

**Comment by xmlking** [comment]
Yes. Thanks

**Comment by xmlking** [comment]
@ciscoheat 
Since you added `empty: 'null` option for proxyFiles,  wonder it make sense, to also add  top level option for whole `superForm`!
your suggested option works but, it adds lot of noice to our code when dealing with large nested object. 

<img width="835" alt="image" src="https://github.com/ciscoheat/sveltekit-superforms/assets/627951/95a5d22a-5a47-4dce-b897-c648ca0eb4c5">

**Comment by ciscoheat** [comment]
Hi, I had this in mind, also so you could have the `taint` option for the proxies, but they are standalone functions, which means that they have to be included in the object returned from superForm, for it to work. Maybe it will be a feature of 1.x in the future. For now, I think a helper function is the best.

**Comment by xmlking** [comment]
Will it make sense to have those empty=null/undefined options also on formFieldProxy / fieldProxy? 
thinking it make a bit easy to handle them in custom input components !

**Comment by xmlking** [comment]
started my migrating from `felte` to `superforms` this weekend.  so for got following components implemented.
https://github.com/xmlking/svelte-starter-kit/tree/main/src/lib/components/forms
wanted to share to get your feedback. 
Thanks

**Comment by ciscoheat** [comment]
> Will it make sense to have those empty=null/undefined options also on formFieldProxy / fieldProxy? thinking it make a bit easy to handle them in custom input components !

These two have a 1:1 mapping between types, so it's not possible to make such a conversion as with a string proxy, which has a well-defined value for empty.
