### ISSUE TITLE
How to use reset method form superForm function

### ISSUE THREAD

**Issue by noah-integrityinspired** [ciscoheat/sveltekit-superforms#90]
While looking through the interface the `superForm` function I saw that it returns a `reset` method. Which does reset the form to the initial value set in the load function, but only one time - after that it no longer resets. 

I did try looking through the docs, but did not find a section on this - so I wanted to know if this was ready for usage, or if I was using it incorrectly

For the code below, when I bring up the page the name field has `foobar`. If I change it to `foobar1` and click the reset button, it goes back to `foobar`. However if I repeat the steps the reset button does not return it to `foobar`; it stays `foobar1`. If I reload the page the reset button works again, but only for the 1st time. 

Hope that makes sense; let me know if I can do add anything else 

`+page.svelte`
```svelte
<script lang="ts">
	import type { PageData } from './$types';
	import { superForm } from 'sveltekit-superforms/client';
	import SuperDebug from 'sveltekit-superforms/client/SuperDebug.svelte';
	export let data: PageData;
	const { form, enhance, reset } = superForm(data.form);
</script>

<button on:click={() => reset()}>Reset</button>
<SuperDebug data={$form} />
<form method="POST" use:enhance>
	<label for="name">Name</label>
	<input type="text" name="name" bind:value={$form.name} />
	<div><button>Submit</button></div>
</form>

```
`+page.server.ts`
```ts
import type { PageServerLoad } from './$types';
import { z } from 'zod';
import { superValidate } from 'sveltekit-superforms/server';

const schema = z.object({ name: z.string() });

export const load = (async () => {
	const form = await superValidate({ name: 'foobar' }, schema);
	return { form };
}) satisfies PageServerLoad;
```

Edit: also I just realized this I filed under `Feature Request/`enhancement`; my apologies, I think I should've done `Something Else` - sadly can't seem to change it on my end

**Comment by ciscoheat** [comment]
Hi, I'm testing your code without any modifications, but it works as I expect it. I change the field value, click reset, and the form resets to `foobar`. It works multiple times. Can you describe in detail the steps you take for it to fail to reset?

**Comment by noah-integrityinspired** [comment]
Well this is embarrassing; based on your comment I tried messing with the package version and now it works. My apologies @ciscoheat - this is a really neat project and I want to be respectful of your time.

I think I may have gotten tripped up by the semvar versioning; my original project is using `^0.6.5`; changing to `^0.6.17` fixes the issue. I didn't think that should have mattered since I thought the caret pulled in minor versions, but upon further reading apparently the caret behaves differently from version 0 packages? (As doing `^0.6.5` does reproduces the issue)

Apologies again - thank you for your time!
