### ISSUE TITLE
redirect via actionResult() with sveltekit-flash-message

### ISSUE THREAD

**Issue by choibles** [ciscoheat/sveltekit-superforms#94]
**Is your feature request related to a problem? Please describe.**
Hi, have been enjoying `sveltekit-superforms` a lot; thanks for the library! Had a use case come up recently that left me a bit stumped. We're using superforms with `sveltekit-flash-message`, and most of the integration seems to be working well. That said, there was one flow which I don't think is currently possible given the current state of the two libraries.

Specifically, when POSTing to an API endpoint (`+server.js`) with superforms, it doesn't appear possible to return an `actionResult('redirect')` call and simultaneously set a flash message. (`actionResult()` with "redirect" as its first parameter only accepts a location and status as the second and third parameters, respectively).

The different parts of this all seem to work in isolation. 
- Throwing a `redirect()` from `sveltekit-flash-message` in an endpoint works (and properly sets the flash message).
- Returning an `actionResult('redirect')` in an endpoint also works, but there's no way to set the flash.

Throwing the `redirect()` from `sveltekit-flash-message` in the endpoint doesn't work, however, when it's called via SuperForms (which is actually documented [here](https://superforms.vercel.app/api), as SuperForms expects an `ActionResult`).

**Describe the solution you'd like**
It seems like it _should_ be possible to setup a redirect with a flash message in an endpoint, unless there's something I'm not understanding. Would be nice to potentially extend the `actionResult()` function from this package to accept a message parameter. 

Admittedly, I understand that such a message parameter on `actionResult()` would only be useful in the context of implementing the `sveltekit-flash-message` package, and furthermore that the package maintainers might prefer to keep `superforms` and `flash-message` as independent as possible (besides the fact that they work so well together).

But still, would be nice to have them work together in this instance. Interested to hear your thoughts. Thanks in advance for the consideration.

**Comment by ciscoheat** [comment]
Hi, happy to hear that you like Superforms *and* sveltekit-flash-message! :) 

You're absolutely right, that's a case I haven't thought about. I wish the integration between the packages was simpler, it gets tricky since I don't want to introduce sveltekit-flash-message as a peer dependency, but I'll see what I can do about this. 

Merging the flash message functionality into Superforms isn't a bad idea, it would make it even more super. Maybe for the 1.0 release!

**Comment by ciscoheat** [comment]
Good news, I managed to extend the actionResult function without any breaking changes, so in the next release, later today, sending a flash message will be possible.

**Comment by choibles** [comment]
Brilliant! Thanks so much for the quick turnaround!

**Comment by ciscoheat** [comment]
Glad to help. :)
