### ISSUE TITLE
Multiple forms with use:enhance

### ISSUE THREAD

**Issue by milimyname** [ciscoheat/sveltekit-superforms#95]
**Description**
I got 2 forms and I did according the [docs](https://superforms.vercel.app/concepts/multiple-forms#multiple-forms). The first form works fine but when I include **use:enhance** to the second one. It blocks actions. I gave 

```
1. First Form
<form method="POST" action="?/addBooking" use:enhance>
Result: OK.

3. Second Form
<form method="POST" action="?/updateUser" use:enhance>
Resutl: Nothing. Tried to log the form from actions but nope.
```

**Comment by ciscoheat** [comment]
Please check out the [multiple forms](https://superforms.vercel.app/concepts/multiple-forms) page on the website again, I've updated the example to make it clearer how it should work. 

I think in your case, you're using the same `use:enhance` function for both forms, they each need the enhance function from their respective `superForm` call.

**Comment by milimyname** [comment]
Haven't expected a response. Thanks! The issue was about the validators option of zod schema.
