### ISSUE TITLE
Console error using window.fetch on form submission

### ISSUE THREAD

**Issue by bmccorm2** [ciscoheat/sveltekit-superforms#97]
When i submit my form, I am getting the console warning below.  Am i doing something wrong here?

```
Loading http://localhost:5173/consumption/input?/create using `window.fetch`. For best results, use the `fetch` that is passed to your `load` function: https://kit.svelte.dev/docs/load#making-fetch-requests
```

**+page.server.ts**
```
import type { Actions } from './$types';
import { CREATE_CONSUMPTION } from '$lib/server/queries';
import { GRAPHQL_URL } from '$env/static/private';
import { error, fail } from '@sveltejs/kit';
import { superValidate } from 'sveltekit-superforms/server';
import { z } from 'zod';

export const prerender = false;

const inputSchema = z.object({
	price: z.number().gt(0).lt(100).default(NaN),
	gallons: z.number().gt(0).lt(50).default(NaN),
	miles: z.number().gt(0).lt(1000).default(NaN),
	notes: z.string()
});

export const load = async () => {
	const form = await superValidate(inputSchema);
	return { form };
};

export const actions: Actions = {
	create: async ({ request }) => {
		const form = await superValidate(request, inputSchema);
                console.log(form)
	}
};
```

**Comment by ciscoheat** [comment]
Hi, that's a SvelteKit warning, in the `create` form action you're deconstructing `fetch`, which could result in that warning, but you're not using it anywhere?

**Comment by bmccorm2** [comment]
You're right it is a svelteKit warning.  About the fetch - i try to distill it down to the smallest parts to show the error and i forgot to take the fetch out (later on i submit to a db).  I updated the original post with it taken out.  

And i've played around with it a bit more.  I'm getting the error in FF but not in chrome so i think we can say browser eccentricity?  I just wanted to make sure that superforms was not making a fetch call anywhere and that i needed to be passing the Sveltekit fetch to it.
