### ISSUE TITLE
Form Payload size 

### ISSUE THREAD

**Issue by fnfbraga** [ciscoheat/sveltekit-superforms#99]
**Description**
When submitting a form with a payload above a certain size (aprox. 1MB) the `__superform_json` serialized object gets trimmed and the parsing and validation fail.

**Comment by ciscoheat** [comment]
This should be fixed now in v0.8, I had to split the serialized string in chunks before sending it to the server. Can you confirm that it works?

**Comment by fnfbraga** [comment]
@ciscoheat unfortunatelly I can still reproduce using 0.8.1

**Comment by ciscoheat** [comment]
The payload seems incomplete, it looks like it starts in the middle of the serialized string.

**Comment by ciscoheat** [comment]
I really hope this is fixed now with v0.8.2, just released.

**Comment by fnfbraga** [comment]
> I really hope this is fixed now with v0.8.2, just released.

WORKS 👍

**Comment by ciscoheat** [comment]
Finally! Closing this now :)
